### ISSUE TITLE
Move window by grabbing video

### ISSUE THREAD

**Issue by lightonflux** [celluloid-player/celluloid#273]
One of the most useful feature in mpv is that you can move the window by grabbing the video. So you don't have to move the mouse to the title or header bar. You also don't need to press the shortcut of your window manager. 

Would it be possible to include/enable this feature in gnome-mpv?

**Comment by gnome-mpv** [comment]
It is possible, but it'll have to be non-default as it may interfere with gestures support, which I intend to implement some time in the future.
