### ISSUE TITLE
Deadzone/very slight mouse movement handling while fullscreen

### ISSUE THREAD

**Issue by carmanaught** [celluloid-player/celluloid#286]
I've been recently configuring an input.conf and mpv.conf to work with plain mpv initially, then subsequently with gnome-mpv and one of the changes I made for mpv was setting up an osc.conf with a deadzone ('deadzonesize') value so that moving the mouse doesn't trigger the OSC until it's much closer to the actual controls.

Is this something that could be implemented in gnome-mpv for both the headerbar and bottom floating controls? Alternatively, some sort of small movement detection (also configurable for mpv's OSC as 'minmousemove') requiring a few pixels of movement (maybe over a certain amount of time) before triggering the floating controls would probably work.

The convenience of something like this would be where, for instance, vibrations from speakers trigger very slight mouse movement.

**Comment by teohhanhui** [comment]
I think the real issue is that there is no way to load the osc.conf in gnome-mpv now.
