### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by bertob** [celluloid-player/celluloid#353]
Thanks for making this great app!

Though it is very descriptive, the current name is a bit unelegant, and doesn't really fit in with other apps on the GNOME platform. Good app names are usually a single noun that's related to the app's domain (e.g. "Fragments" for a torrent app, or "Peek" for a screen recorder).
https://developer.gnome.org/hig/stable/application-basics.html.en

Would you be open to renaming the app? I'd be happy to help brainstorming a new name (and potentially making a new icon that fits better with it). Some of the apps I've named/branded recently are [Fractal](https://gitlab.gnome.org/World/fractal/) and [Teleport](https://gitlab.gnome.org/jsparber/teleport).

**Comment by TingPing** [comment]
> Would you be open to renaming the app? I'd be happy to help brainstorming a new name (and potentially making a new icon that fits better with it). Some of the apps I've named/branded recently are Fractal and Teleport.

Sorry to jump in here but I have a few other applications in need of a proper name (an IRC client, and Torrent client) so I'd appreciate some ideas also. I'm on gimpnet if that would be a better place to discuss than here.

**Comment by gnome-mpv** [comment]
> Would you be open to renaming the app? I'd be happy to help brainstorming a new name (and potentially making a new icon that fits better with it). Some of the apps I've named/branded recently are Fractal and Teleport.

Yes. Do you have any suggestions for a new name?

**Comment by bertob** [comment]
@jimmac and I had a little brainstorming session this morning. Our favorite was "Projector". It's short, simple, and related to video in a way that's not domain-specific (like e.g. cinema-related names). It's also a physical object, which is great for the icon :)

@gnome-mpv What do you think?

**Comment by bertob** [comment]
@TingPing sure, i'm on #gnome-design and #gnome-hackers

**Comment by TingPing** [comment]
I think Projector does have a chance to be confusing because projectors are something computers can use so a user might at first believe this app would be to configure one or something.

**Comment by bertob** [comment]
@TingPing dunno, I think that's highly dependent on the icon. As long as it looks like a media app rather than a settings panel icon I don't think it would be a problem in practice.

"Reel" sounds good too though, and would also provide ample opportunities for app icons.

**Comment by gnome-mpv** [comment]
I agree with @TingPing that Projector may be confusing.

I like Reel but there's a [web server](https://github.com/celluloid/reel) already using that name.

**Comment by bertob** [comment]
@gnome-mpv I don't think that would be a real problem. Most desktop environments don't mix settings panels with apps anyway, and app names are almost always next to the icon.

As for pre-existing projects by the same name, as long as they aren't used in the same context (e.g. if both were video players) that's not usually an issue. In this case I think it should be fine since the other project isn't even a user-facing app.

That said, here are some more options I like:
* Theatre
* Frames
* Popcorn

**Comment by gnome-mpv** [comment]
> As for pre-existing projects by the same name, as long as they aren't used in the same context (e.g. if both were video players) that's not usually an issue. In this case I think it should be fine since the other project isn't even a user-facing app.

I'm more concerned about how distros are going to handle packaging. I think it would be nice if the name of the app/package/executable are the same.

>That said, here are some more options I like:
>- Theatre
>- Frames
>- Popcorn

I think the word Theatre is a little bit too common. Frames sounds fine although it may evoke the image of picture frames rather than film frames.

How about Flick?

**Comment by bertob** [comment]
> I think it would be nice if the name of the app/package/executable are the same.

Are there pre-existing packages called "projector"? At least on Arch there's nothing by that name.
After doing a quick search on Github and the web I'm fairly confident that there are no other user-facing apps by that name out there, at least not well-known ones.

> I think the word Theatre is a little bit too common.

I think that's probably true for most nouns, and not really an issue usually. For example, "peek" is also a very common word, but it works great as an app name. There's actually [another video player app named "Cinema"](https://github.com/artemanufrij/playmyvideos). The bigger issue is probably that it's too closely related to movies/cinema, while this app isn't really focused on movies.

Flick in the singular sounds a bit weird. "Flicks" could work, but it feels a bit too colloquial to me and I'm not a huge fan of how it sounds. Also, it has the same problem as other movie-related names.

Maybe we should look at materials and technologies related to video for some more interesting names. "Celluloid" could be cool, as it's related to movies but a bit more abstract than other options.

**Comment by gnome-mpv** [comment]
I think Celluloid is a good option. I like how it sounds, and there doesn't seem to be another application with this name.

**Comment by gnome-mpv** [comment]
@bertob 
Would you be able to make an icon to go with the name? Something that's recognizable at small sizes like a film reel would probably work well as a motif.

**Comment by bertob** [comment]
Ok great! I'll be happy to make a new icon.

**Comment by bertob** [comment]
Hi, sorry for the long radio silence. The reason for that is that we've been working on developing a new GNOME icon style, so I didn't want to make an icon in the old style since it would have to be changed soon anyway. We're not shipping the new icons until 3.32 (early next year), but the guidelines are going to come much earlier than that, and some third-party apps are already adopting the new icons.

This is what we currently have for GNOME MPV/Celluloid:

![image](https://user-images.githubusercontent.com/1908896/43787596-aa187a50-9a6b-11e8-83aa-02c8570a1d6f.png)

One of the guidelines with the new style is for visual media to be represented with gradients, so that's why video players have them. We will probably still iterate on this, but I wanted to keep you in the loop since it's been forever since I promised a new icon :)

**Comment by smithfred** [comment]
Celluloid is a great name! :+1:

@bertob - the proposed icon seems a bit generic (especially since GNOME MPV isn't the default GNOME video application) - maybe something that riffs on the Celluloid name a bit more obviously? I know the current one technically does, but that is also used as a fairly generic "video thumbnail" in a lot of places. A reel to reel projector maybe? A loose roll of celluloid? Or maybe they're too clichéd as well :laughing:

**Comment by bertob** [comment]
@gnome-mpv The icon initiative is getting more serious, and we're starting to push out icons.

How do you want to do the rename and icon change? Both at the same time or staggered, so people have time to adjust to the changes?

**Comment by gnome-mpv** [comment]
> How do you want to do the rename and icon change? Both at the same time or staggered, so people have time to adjust to the changes?

I think staggered would be better. We can change the icon next release and rename the release after that.

**Comment by smithfred** [comment]
Is Celluloid going to be the new name out of interest?

BTW re. the icon, most of the icons on https://developer.gnome.org/hig/stable/icon-design.html.en (and in the above screenshot) have a small "3D effect" at the bottom, giving them a thick/chunky feel. I don't know if the above icon is intended to be the final one, but maybe it's worth considering something similar?

**Comment by gnome-mpv** [comment]
>Is Celluloid going to be the new name out of interest?

yes

**Comment by spider623** [comment]
will it support 240fps glorious anime playback with it? I'm all in for it

**Comment by adrianheine** [comment]
I think this can be closed now! :)

**Comment by gnome-mpv** [comment]
b89c1256c0924dc1a173a2fe6eaa5c41813b589f
