### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by ghost** [celluloid-player/celluloid#398]

**Comment by Bindea** [comment]
Thanks , What about the prefetch metadata option does that collect metadata from the internet like VLC?

**Comment by gnome-mpv** [comment]
>What about the prefetch metadata option does that collect metadata from the internet like VLC?

Metadata prefetch in `gnome-mpv` is done by partially loading the file, so no connections will be made to any third-party services.

**Comment by Bindea** [comment]
Thank you both for the clarification...

This can be closed unless you like to leave questions for users to read.

Thanks.
