### ISSUE TITLE
Odd behavior on Wayland

### ISSUE THREAD

**Issue by biswasab** [celluloid-player/celluloid#413]
Overview Description:
On Wayland, gnome mpv is unable to determine the display fps :
![screenshot from 2019-02-01 18-45-44](https://user-images.githubusercontent.com/17230826/52533053-2ef7b800-2d54-11e9-81f1-cdf4cfea2952.png)
Howver, mpv detects it correctly:
![screenshot from 2019-02-01 18-46-50](https://user-images.githubusercontent.com/17230826/52533070-59e20c00-2d54-11e9-9cdc-97c0cce685a8.png)

Long pressing the "i" key which bring up this info almost breaks the video but this is not present on mpv.
Having said that cpu usage is much higher than mpv/gnome-mpv on xorg.

mpv options used it both cases:
--vo=gpu --hwdec=auto --gpu-context=wayland

Steps to reproduce:
1. Login to gnome wayland session
2. play a file in gnome mpv
3, long press the "i" key and note the readings.

Expected results:
It should behave the same way mpv does.

Actual results:
cpu usage was much higher, display fps was 0 and long pressing the "i" key breaks the video.

Additional information:
OS: Fedora 29 ( present on both flatpak and rpmfusion build, the flatpak build has a weird shadow border around the normal borders)
GPU: Present on both Radeon Rx 550 and AMD radeon R5 gpu that I tested.

**Comment by gnome-mpv** [comment]
>  On Wayland, gnome mpv is unable to determine the display fps :

Fixed in 74cf8bf173729974331a8b3e08225419608ee294

**Comment by gnome-mpv** [comment]
> Long pressing the "i" key which bring up this info almost breaks the video but this is not present on mpv.

I can reproduce this, but I don't know what's causing it yet. As a workaround, you can press `Shift+i` instead of `i` and the text will stay on the screen until you press `Shift+i` again.

**Comment by biswasab** [comment]
@gnome-mpv Thanks. I will try with the patch and let you know.

**Comment by biswasab** [comment]
> I can reproduce this, but I don't know what's causing it yet. As a workaround, you can press `Shift+i` instead of `i` and the text will stay on the screen until you press `Shift+i` again.
I tried with the patch and shift+i , It seems frames are still dropping(output). I'm not sure what's causing this. Also frame timings are still unavailable.
![screenshot from 2019-02-12 13-55-38](https://user-images.githubusercontent.com/17230826/52621724-07c4f600-2ece-11e9-80bc-028ecf66276d.png)

**Comment by gnome-mpv** [comment]
> Also I don't understand why it is forcing opengl-cb. Isn't gpu the best vo for mpv?

`opengl-cb` (recently renamed to `libmpv`) is the only VO that can be used to embed video under Wayland.

**Comment by biswasab** [comment]
@gnome-mpv Sorry for the long silence. Looks like the problem might be with the mutter(compositor). I will open a new bug if I find something. Meanwhile the first part of the bug is solved so I will close this bug.

Thank you.
