### ISSUE TITLE
Weird window Shadow on Wayland

### ISSUE THREAD

**Issue by alosarjos** [celluloid-player/celluloid#419]
Overview Description: On Wayland Session, when the window has the focus, it draws a weird shadow.

Steps to Reproduce:
1. Start a Wayland Session
2. Open Gnome-MPV
3. Focus the window by selecting it

Actual Results:
![Captura de pantalla de 2019-03-15 13-24-58](https://user-images.githubusercontent.com/29999427/54431174-f9186b80-4725-11e9-928d-82e2b0456dad.png)

Expected Results:

A more subtle shadow I guess like this?

![Captura de pantalla de 2019-03-15 13-27-47](https://user-images.githubusercontent.com/29999427/54431244-32e97200-4726-11e9-9616-b6defee03d57.png)

Version: 0.16

Additional Information: Arch installation, AMD GPU on Wayland

**Comment by gnome-mpv** [comment]
I can reproduce this, but only with AMD GPUs, so this is probably a bug in AMD's driver.

**Comment by alosarjos** [comment]
MPV by itself is not showing it (Read about people claiming it was due to OpenGL accelerated windows). Some bug on GTK maybe?

**Comment by gnome-mpv** [comment]
>Some bug on GTK maybe?

That's also possible. In any case, it's not a bug in celluloid/gnome-mpv since we don't have any control over the shadow.

**Comment by biswasab** [comment]
Those shadows are more odd and intense on the flatpak version than on the native version.

**Comment by myfreeweb** [comment]
I've been seeing this for a long time on any OpenGL + GTK windows indeed. Your report here actually pushed me to investigate :)

Mesa >=18.0 supports 10-bit color buffer formats, and they have 2-bit alpha. (R10G10B10A2) Obviously you can't have much smoothness if transparency is encoded with two bits, that's just 4 levels of transparency. Sooo they decided to return these formats first, presumably to troll everyone who just naively picks the first compatible format, expecting R8G8B8A8. (Which is good! Don't expect that!) And GTK was one of those naive toolkits.

Just sent a pull request to GTK: https://gitlab.gnome.org/GNOME/gtk/merge_requests/941

**Comment by gnome-mpv** [comment]
No longer reproducible as of GTK 3.24.10.
