### ISSUE TITLE
Search playlist

### ISSUE THREAD

**Issue by gsantner** [celluloid-player/celluloid#420]
When there are lots of e.g. music tracks added in the playlist window it always takes some time to quickly jump to some other specific one because you need to look through every item manually.
I couldn't find any keybinding or a menu option to search through the playlist.

**Actual Results:**
No search / find in playlist option.

**Expected Results:**
Search option available. E.g. ctrl+f?
Filtering by filepath would be enough for the case, but can also be on metadata.

**Version:**
gnome-mpv_0.16-1~bionic1_amd64

**Comment by kentherzz** [comment]
I would like to upvote this suggestion, brilliant idea!
