### ISSUE TITLE
Keybinding for +- (numpad) doesn't work

### ISSUE THREAD

**Issue by gsantner** [celluloid-player/celluloid#421]
**Overview Description:**

Added keybinding to input.conf:
```
+ add volume 2
- add volume -2
```

because I want to control volume by +- keys. Sadly it only works for the keys on the left, but not at numpad.

I also added additional bindings for KP_ADD / KP_SUBSTRACT, but no reaction.

It would be great if the +- keys also do work for the numpad keys, or alternatively support for binding them separately.

Version: 0.16

**Comment by gsantner** [comment]
Thanks! :D

**Comment by gsantner** [comment]
@gnome-mpv Saw the file, may I suggest to also add Kp_Divide and Kp_Multiply to mapping?

**Comment by gnome-mpv** [comment]
@gsantner 26a8ec7c5fed66334151c66a4ff243168cb1c6f2
