### ISSUE TITLE
Feature Request: Minimize to systray (and systray icon/menu)

### ISSUE THREAD

**Issue by hhhorb** [celluloid-player/celluloid#423]
Self explanatory, I'd like to use gnome-mpv to play music files. so I don't need the window. Bonus would be track-change notifications. Thanks for your work, it's brilliant.

**Comment by TingPing** [comment]
MPRIS is the better interface to control it as a music player. Then just minimize the window..

**Comment by hhhorb** [comment]
Thanks for taking the time to consider this, I know feature requests are a pain in the behind.

Having the window minimized but still in the app switcher is what I'm trying to avoid, I want the window closed to systray so it is out of the switcher but still accessible via a systray icon. Vlc, SMPlayer, I believe even Spotify all have this option, as do almost every music player (Rhythmbox, Cantata, etc...)

I run openbox-session and xfce4-panel, there is no session-manager on my system. mpris controllers available with no desktop environment are limited (playerctl, xfce4-sound-menu-plugin) and don't include a min-to-systray option.

My current workaround is to use SMPlayer as the mpv frontend so I can minimize the player to tray, and use xfce4-sound-menu-plugin to control it, though I might ditch the plugin and create shortcuts for playerctl instead.

Consider this issue [Won't Fix] if you don't think this feature should be added. Again, thanks for your response, gnome-mpv is really a beautiful front-end.

**Comment by gnome-mpv** [comment]
Seeing that GtkStatusIcon has been deprecated since 3.14, I don't think it's worth the effort to implement this.

For track-change notifications, you can use [`notify.lua`](https://github.com/rohieb/mpv-notify).
