### ISSUE TITLE
Configuring script options (mp.options)

### ISSUE THREAD

**Issue by teohhanhui** [celluloid-player/celluloid#425]
Overview Description:

In `mpv`, there is `script-opts` directory, where we can configure the settings to be passed to each script: https://mpv.io/manual/master/#mp-options-functions

It seems like this is broken because of `--no-config` option being used: https://mpv.io/manual/master/#options-no-config
which prevents `--config-dir` option from having any effect: https://mpv.io/manual/master/#options-config-dir

**Comment by teohhanhui** [comment]
My current workaround is to set it under "Extra MPV options":

```
--script-opts=acompressor-default_enable=yes
```

**Comment by gnome-mpv** [comment]
3fca44d3a4a9ea734a8b4666122c1b05fc208458

**Comment by teohhanhui** [comment]
Unfortunately, the `script-opts` directory is still not having any effect. I'm not sure why.

**Comment by teohhanhui** [comment]
If I enable `--mpv-options="--log-file=$(pwd)/mpv.log"`, I see:

> [   0.534][d][acompressor] reading options for acompressor 
> [   0.534][d][acompressor] script-opts/acompressor.conf not found. 
> [   0.534][d][acompressor] lua-settings/acompressor.conf not found. 

https://gist.github.com/teohhanhui/c30405750abbd1ef8e23d58ef8dd85a9

**Comment by gnome-mpv** [comment]
Looks like you need to set `--config` for it to work.

**Comment by teohhanhui** [comment]
Sorry, I'm not sure what you mean. There's no `--config` option? And celluloid already sets the `--config-dir` option correctly, as far as I can tell.

**Comment by gnome-mpv** [comment]
It's a semi-undocumented mpv option; the opposite of `--no-config`. I tried setting `--config` in addition to `--config-dir` and it started working correctly. It will also make mpv bypass our script/config loading mechanism though, so it can't be enabled by default yet.
