### ISSUE TITLE
YouTube videos cannot be played

### ISSUE THREAD

**Issue by hellorich** [celluloid-player/celluloid#427]
Overview Description:
A fresh install via of Gnome MPV from flatpak installed in Ubuntu 19.04 won't play YouTube content. Tested a vimeo link and playback was successful.

Steps to Reproduce:
1. Install Flatpak on Ubuntu 19.04.
1. Install the Flatpak version of Gnome MPV.
2. Open location with any YouTube video in clipboard and hit open
3. Attempt playback

Actual Results:
An error popup with the message 'Playback was terminated abnormally. Reason: unrecognized file format' appears.

Expected Results:
Video should playback. Procedure with a vimeo was successful.
Version: 0.16

Additional Information:
I tried installing youtube-dl separately via command line and it was failing playback with a message about tokens. A search on the youtube-dl issue tracker found this is a recent issue. I wonder if there's been an update to YouTube which has broken something temporarily?

Link to issue: https://github.com/ytdl-org/youtube-dl/issues/20758

**Comment by gnome-mpv** [comment]
The bundled `youtube-dl` probably needs to be updated. I can successfully play youtube videos with `youtube-dl-2019.04.24`.

/cc @TingPing

**Comment by BrainBlasted** [comment]
I've got an update ready. Here: https://github.com/flathub/io.github.GnomeMpv/pull/15

**Comment by TingPing** [comment]
Updated to 2019.04.24
