### ISSUE TITLE
[MPRIS] Custom media key actions

### ISSUE THREAD

**Issue by teohhanhui** [celluloid-player/celluloid#432]
Overview Description: The media key actions defined in `input.conf` have no effect

Steps to Reproduce:
1. Load `input.conf` (see additional information)
2. Try to use media keys

Actual Results: Media key actions seem to be hardcoded: https://github.com/celluloid-player/celluloid/blob/b89c1256c0924dc1a173a2fe6eaa5c41813b589f/src/media_keys/gmpv_media_keys.c#L185-L215

Expected Results: Media key actions should match what's defined in `input.conf`

Version: 0.16

Additional Information: https://github.com/teohhanhui/mpv-config/blob/4ebdf57cdca47326c2c79015f2f39c1197a49337/input.conf#L17-L25

**Comment by gnome-mpv** [comment]
Can you try pressing every media key (without anything playing) and post the log messages here?

**Comment by teohhanhui** [comment]
"Enable media keys support" option doesn't seem to change the output in the log (same when enabled or disabled):

```
** (gnome-mpv:16115): WARNING **: 20:27:22.520: Failed to run mpv command "keyup AudioPlay". Reason: error running command.

** (gnome-mpv:16115): WARNING **: 20:27:24.550: Failed to run mpv command "osd-msg playlist-prev weak". Reason: error running command.

** (gnome-mpv:16115): WARNING **: 20:27:24.654: Failed to run mpv command "keyup AudioPrev". Reason: error running command.

** (gnome-mpv:16115): WARNING **: 20:27:26.794: Failed to run mpv command "osd-msg playlist-next weak". Reason: error running command.

** (gnome-mpv:16115): WARNING **: 20:27:26.864: Failed to run mpv command "keyup AudioNext". Reason: error running command.
```

Also:

    $ sudo libinput debug-events --show-keycodes

And pressing the keys give:

```
 event5   KEYBOARD_KEY      +5.83s	KEY_PLAYPAUSE (164) pressed
 event5   KEYBOARD_KEY      +5.91s	KEY_PLAYPAUSE (164) released
 event5   KEYBOARD_KEY      +9.40s	KEY_PREVIOUSSONG (165) pressed
 event5   KEYBOARD_KEY      +9.49s	KEY_PREVIOUSSONG (165) released
 event5   KEYBOARD_KEY     +11.08s	KEY_NEXTSONG (163) pressed
 event5   KEYBOARD_KEY     +11.15s	KEY_NEXTSONG (163) released
```

So I'm guessing I'm just using the wrong keycodes in `input.conf`? :laughing:

**Comment by teohhanhui** [comment]
They seem to be properly mapped here: https://github.com/mpv-player/mpv/blob/36600ff1633871a996fe05b8e0ff0b22c2ebb0f9/video/out/wayland_common.c#L324-L336
