### ISSUE TITLE
Add Esperanto (language) in Zanata

### ISSUE THREAD

**Issue by F3nd0** [celluloid-player/celluloid#433]
Hello!

Would you please add Esperanto (the international language) to the languages available for Celluloid in Zanata? The language code is ‘eo’. Thank you!

**Comment by gnome-mpv** [comment]
I added Esperanto to [Zanata](https://translate.zanata.org/iteration/view/celluloid/master). You can follow instructions [here](http://docs.zanata.org/en/release/user-guide/translator-guide/) to start translating. Let me know if you have any questions.

Thanks!
