### ISSUE TITLE
Include flatpak manifest in repository for easy cross-distro building

### ISSUE THREAD

**Issue by BrainBlasted** [celluloid-player/celluloid#435]
Hey there - I would love to do some work on Celluloid, but the thing preventing me from getting started is that I can't build it in GNOME Builder without hunting down all the dependencies manually. Within upstream GNOME we have a process that includes having a flatpak manifest in the repo, so when cloned by Builder (or other IDEs with flatpak support) building and running is always as simple as pressing a button. This makes it much easier to get started contributing to applications, and makes testing new things simple as well.

Would you be interested in having a manifest in the repo? If so I'll put in the work to get one working :)

**Comment by gnome-mpv** [comment]
Actually, we already have two working flatpak manifests. [One for tarball releases](https://github.com/flathub/io.github.GnomeMpv/blob/master/io.github.GnomeMpv.json) in the flathub repo and [another one](https://github.com/TingPing/flatpak-packages/blob/master/io.github.GnomeMpv.json)  that uses the git repo directly.

**Comment by BrainBlasted** [comment]
Yes, the thing I'm requesting is about one _within_ the repo - so when I clone celluloid in Builder it can grab all the dependencies and I can run a sandboxed development version.

**Comment by BrainBlasted** [comment]
Typically these use the `master` GNOME runtime and build everything from git rather than tagged releases.

**Comment by gnome-mpv** [comment]
>Yes, the thing I'm requesting is about one within the repo - so when I clone celluloid in Builder it can grab all the dependencies and I can run a sandboxed development version.

Wouldn't downloading one from a different repo achieve the same result?

**Comment by BrainBlasted** [comment]
No - GNOME Builder requires a local checkout in the same repo as the manifest in order to build and run it. This is because it runs the final build steps itself for integration & iteration purposes.

**Comment by gnome-mpv** [comment]
Alright, please go ahead and submit a pull request when you're ready.

**Comment by BrainBlasted** [comment]
Alright, will try and get this done later today :)

**Comment by BrainBlasted** [comment]
It took me a lot longer to get back to this than I expected, but I submitted a PR
