### ISSUE TITLE
flatpak version does not load external subtitles (.SRT file) automatically

### ISSUE THREAD

**Issue by glaubersm** [celluloid-player/celluloid#436]
Overview Description:
gnome mpv from Arch Linux repositories loads external subtitles files automatically if such file has the same name of the video file. But the same behavior does not occur when I use gnome mpv from flathub.

Steps to Reproduce:
1. have a video file named video.mp4 and a subtitles file named video.srt located in a same folder
2. open the video file with gnome mpv installed via flatpak/flathub
3.

Actual Results:
gnome mpv does not load the subtitles file

Expected Results:
The same behavior that occurs when I use gnome mpv installed from Arch Linux repositories: gnome mpv automatically loads the subtitle file with the same name of the video file.

Version: 0.16

Additional Information:

**Comment by TingPing** [comment]
This is forever impossible with the sandbox. By design the sandbox only allows in the file you select.

So there are two options:

- Support the user selecting the subtitles and video file at the same time and automatically work
- The user can just grant filesystem permissions: `flatpak override --user --filesystem=host io.github.GnomeMpv`

**Comment by TingPing** [comment]
Also once you load a video you can load a subtitle file from the menu and it will work as expected.

**Comment by yue-dongchen** [comment]
Indeed, many packages by default set filesystem to a broader scope: if not `filesystem=host`, then `filesystem=home` (user’s home directory). Flatseal is a GUI app that makes toggling such easy. But I have no knowledge about the process of Flatpak packaging. It would be nice if someone with such skills improve this aspect of the Flatpak.

**Comment by TingPing** [comment]
This issue discusses an idea for improving this: https://github.com/flatpak/xdg-desktop-portal/discussions/1257
