### ISSUE TITLE
GUI starts to blink on Gnome Wayland session after you change some preference during video playback

### ISSUE THREAD

**Issue by glaubersm** [celluloid-player/celluloid#445]
Steps to Reproduce:
1. start Gnome Wayland session
2. play a video with Gnome mpv
3. change some preference while gnome mpv plays the video

Actual Results:
GUI starts to blink after you click "Save" button in preferences window.
I recorded a video to show the bug.
https://youtu.be/-0msN82xA1o

Expected Results:
GUI never blinks

Version:
0.16

Additional Information:
My system:
Arch Linux
Gnome 3.32.2 desktop environment
intel hd graphics with modesetting driver

**Comment by gnome-mpv** [comment]
Can you check if git master still has this bug?

**Comment by glaubersm** [comment]
I can't reproduce exactly the same bevavior with celluloid-git.
But I noticed another behavior that seems to be related.
Steps to reproduce:
enable both "Autohide mouse cursor in windowed mode" and "Use floating controls in windowed mode"
in preferences
play a video
enable "Loop playlist" feature during video playback
wait the video playback to be finished
move the cursor to unhide the video controls
Result: as we can see in the screen recording below, the video area flickers

https://youtu.be/C8WUtcz9eo8

**Comment by gnome-mpv** [comment]
>as we can see in the screen recording below, the video area flickers

That's a different issue. Should be fixed by 455ec7a504cf6088f3a9ec6293e9e2a6cc7b2aeb.
