### ISSUE TITLE
Celluloid has wrong icon in alt+tab menu of KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [celluloid-player/celluloid#447]
Overview Description:
I use celluloid-git on Arch linux running KDE Plasma 5.16.3 Wayland session.

Steps to Reproduce:
1. start kde plasma wayland session. 
2. open celluloid
3. press alt+tab and hold tab key

Actual Results:
the task switcher shows a Wayland generic icon instead of celluloid icon

Expected Results:
the task switcher shows celluloid icon

Version:
celluloid-git

Additional Information:
This bugs also affects gnome mpv 0.16.

**Comment by gnome-mpv** [comment]
I'm not sure if it's possible to fix this in `celluloid`. Every gtk3 app I tested has the same problem.

**Comment by glaubersm** [comment]
I confirm this bug with other gtk3 apps.
But Nautilus file manager also is a gtk3 app and it shows its own icon
in the task switcher. Weird...

**Comment by glaubersm** [comment]
I have reported this issue to KDE devs.
Read the David Edmundson's comment please.

https://bugs.kde.org/show_bug.cgi?id=409967

What do you think?

**Comment by gnome-mpv** [comment]
This also changes the program name in the output of `--help`, but I don't think there's another way to set xdg-shell app_id.

**Comment by glaubersm** [comment]
it seems that there is a bug in gtk
https://gitlab.gnome.org/GNOME/gtk/issues/2034
