### ISSUE TITLE
Just a dot instead of Progress bar in Vertical Mobile view

### ISSUE THREAD

**Issue by ghost** [celluloid-player/celluloid#450]
Librem5 and Pinephone are arriving soon, celluloid must be usable in those phones. Celluloid runs perfectly,but instead of progress bar,just a dot is displayed.
See below:
![28-07-2019_06-49-10PM](https://user-images.githubusercontent.com/49347249/62007218-6a523b80-b168-11e9-8b96-def9327fe1a1.png)

**Comment by gnome-mpv** [comment]
This is caused by the screen being so narrow that there's not enough enough space for the progress bar. We'll need to adjust the controls a bit to make room for it.
