### ISSUE TITLE
Some mpv script doesn't works.

### ISSUE THREAD

**Issue by hajinhoe** [celluloid-player/celluloid#451]
Overview Description:
Some mpv lua script doesn't works.

Steps to Reproduce:
1. I have added autoload.lua script to celluloid.(https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua)
2. This script doing nothing in celluloid but, it works very well on pure mpv.

Actual Results:

It should work same as pure mpv. (maybe??)

Expected Results:

Add files in directory to playlists.
 
Version:
0.16, Ubuntu 18.04

Additional Information:
https://github.com/mpv-player/mpv/blob/e92d1b72a79c53369fdfd03b2d1499aa410324db/TOOLS/lua/autoload.lua

Older version of this works.

Thank you.

**Comment by gnome-mpv** [comment]
Can't reproduce.

Are you using Flatpak?

**Comment by hajinhoe** [comment]
No, I use the package in PPA (https://launchpad.net/~xuzhen666/+archive/ubuntu/gnome-mpv).

**Comment by gnome-mpv** [comment]
Run `G_MESSAGES_DEBUG=all gnome-mpv --mpv-options='--msg-level=all=trace'`, open a file, then post the log messages here.

**Comment by hajinhoe** [comment]
[log1.log](https://github.com/celluloid-player/celluloid/files/3467994/log1.log)
[log2.log](https://github.com/celluloid-player/celluloid/files/3467996/log2.log)
log1.log is a log using latest script, and log2.log is order version of the script(linked in additional information).
I have viewed logs but I can not understand the cause.

**Comment by gnome-mpv** [comment]
For some reason, your logs aren't showing messages from mpv. I was able to reproduce the bug in a VM though. In my case, the script crashes with this message: `Lua error: autoload.lua:92: attempt to call field 'trace' ( a nil value)`

It seems `libmpv` (0.27.2) in Ubuntu 18.04 is too old to run the new version of `autoload.lua`. I get the same error with regular `mpv`, so this problem isn't specific to celluloid.

**Comment by hajinhoe** [comment]
Thank you for your answer.
