### ISSUE TITLE
Celluloid exits when user exits from keyboard shortcuts help

### ISSUE THREAD

**Issue by Nirgendsdorf** [celluloid-player/celluloid#457]
Overview Description: Please see title/subject.

Steps to Reproduce:
1. Disable decorations and restart so the menu items display
2. Click Help/Keyboard Shortcuts
3. Exit the Keyboard Shortcuts pop-up by clicking the (x) or by pressing the escape key.

Actual Results: The Keyboard Shortcuts pop-up exits, followed by Celluloid exiting. This happens whether Celluloid is idle or has media paused.

Expected Results: just the Keyboard Shortcuts pop-up should exit.

Version: 0.17 Flatpak

Additional Information:

**Comment by gnome-mpv** [comment]
Can't reproduce.

Try running Celluloid from command line (`G_MESSAGES_DEBUG=all flatpak run io.github.celluloid_player.Celluloid --mpv-options='--msg-level=all=trace'`), trigger the crash/exit, then post log messages here.

**Comment by Nirgendsdorf** [comment]
Here you go...

[log.gz](https://github.com/celluloid-player/celluloid/files/3511816/log.gz)

**Comment by gnome-mpv** [comment]
Can you trigger the crash in GDB and post the backtrace here?

Here's how to generate backtrace with FlatPak:
1. Install debugging symbols: `flatpak install flathub io.github.celluloid_player.Celluloid.Debug`
2. Open a shell inside the sandbox: `flatpak run --command=sh --devel io.github.celluloid_player.Celluloid`
3. Run Celluloid with GDB: `gdb -ex 'set pagination off' -ex run -ex bt /app/bin/celluloid`
4. Trigger the crash

**Comment by Nirgendsdorf** [comment]
>$ flatpak run --command=sh --devel io.github.celluloid_player.Celluloid
error: runtime/org.gnome.Sdk/x86_64/3.32 not installed

After I managed to figure out this is a Flatpak runtime and install it, I followed the rest of your instructions. Thing is, Celluloid was no longer crashing. Apparently, org.gnome.Sdk is necessary but flathub didn't install it? Anyway, this problem seems to be resolved. Thanks for your help.
