### ISSUE TITLE
Ukrainian translation file uk_UA.po

### ISSUE THREAD

**Issue by vl-nix** [celluloid-player/celluloid#458]
[uk_UA.po.tar.gz](https://github.com/celluloid-player/celluloid/files/3517594/uk_UA.po.tar.gz)

Regards,
Stepan

**Comment by gnome-mpv** [comment]
Thank you. I included your translation in 61e0ef31ab9004a507e41d9db22f625797646484.

In the future, you can use [Zanata](https://github.com/celluloid-player/celluloid#contributing-translations) to update your translation.
