### ISSUE TITLE
Thank you. Your translation has been synced from Zanata in 61e0ef31ab9004a507e41d9db22f625797646484.

### ISSUE THREAD

**Issue by hugok79** [celluloid-player/celluloid#460]
Thank you. Your translation has been synced from Zanata in 61e0ef31ab9004a507e41d9db22f625797646484.

_Originally posted by @gnome-mpv in https://github.com/celluloid-player/celluloid/issues/459#issuecomment-522973390_

You're welcome but please update again. Fix some grammar errors. Thanks

**Comment by gnome-mpv** [comment]
I'll sync again some time before the next release.

**Comment by hugok79** [comment]
Ok. Thanks.
