### ISSUE TITLE
Celluloid Ubuntu PPA needs updating

### ISSUE THREAD

**Issue by spectrumcomputing** [celluloid-player/celluloid#464]
Please can the Ubuntu PPA be updated.  It does not seem to have been updated for 31 weeks.  Thank you.

**Comment by xuzhen** [comment]
New packages for 19.04 & 19.10 have been uploaded.

If you got this message
>Repository 'http://ppa.launchpad.net/xuzhen666/gnome-mpv/ubuntu disco InRelease' changed its 'Label' value from 'GNOME MPV' to 'Celluloid (formerly GNOME MPV)'"

run the following command and retry

```sudo rm /var/lib/apt/lists/ppa.launchpad.net_xuzhen666_gnome-mpv_ubuntu_dists_disco_InRelease```

**Comment by spectrumcomputing** [comment]
Thanks for doing this @xuzhen 

Is it possible for the version for the LTS version of Ubuntu (18.04 - Bionic) be updated for the latest version, or is this not possible?

Thanks

**Comment by xuzhen** [comment]
I uploaded celluloid 0.17 for 18.04

But the version of libmpv in 18.04's official repository didn't meet the requirement for celluloid 0.17, therefore you have to add another PPA: https://launchpad.net/~mc3man/+archive/ubuntu/bionic-media

And don't forget to run 
```sudo rm /var/lib/apt/lists/ppa.launchpad.net_xuzhen666_gnome-mpv_ubuntu_dists_*_InRelease```

**Comment by spectrumcomputing** [comment]
Thank you. I will give that a go at the weekend. Are you OK to leave the issue open until then?

Thanks for such a great player.  It has replaced VLC for me!

**Comment by gnome-mpv** [comment]
> Are you OK to leave the issue open until then?

That's fine.

**Comment by spectrumcomputing** [comment]
Thank you. That all worked fine.  Appreciated.
