### ISSUE TITLE
Is gettext 0.20 really needed?

### ISSUE THREAD

**Issue by xuzhen** [celluloid-player/celluloid#466]
gettext 0.20 is required in https://github.com/celluloid-player/celluloid/blob/master/configure.ac#L20

but there are many distributions (especially the Debian-based ones) still only have 0.19.8 in their repository
Ubuntu: https://packages.ubuntu.com/search?keywords=gettext
Debian: https://packages.debian.org/search?keywords=gettext&searchon=names&suite=all&section=all
Fedora 30 and lower: https://rpms.remirepo.net/rpmphp/zoom.php?rpm=gettext

I lowered the requirement and successfully compiled on Ubuntu 19.10 with gettext 0.19.8. 

Is there any gettext 0.20 new features really be needed?

**Comment by gnome-mpv** [comment]
I don't remember exactly why I bumped the requirement to 0.20, so I'm not sure if it's really needed. You should be able build without gettext 0.20 if you use the [release tarball](https://github.com/celluloid-player/celluloid/releases/download/v0.17/celluloid-0.17.tar.xz) though.
