### ISSUE TITLE
Crash when click on play, pause, options etc...

### ISSUE THREAD

**Issue by AngryPenguinPL** [celluloid-player/celluloid#468]
Overview Description:
Celluloid 0.17 crashing when click on any IU elements like options, play, stop, fullscreen etc. Also when dragging the video file directly to the player causes the video is played well.
Worth to add I start observe it just after upgrade package from gnome-MPV 0.16 to celluloid 0.17. Previous works fine, new one crashing on my two machines.
Build process is exactly the same.

Steps to Reproduce:
1. Install celluloid 0.17 on OpenMandriva Cooker
2. Open, click on options or play button or fullscreen
3. Watch a crash

When I run celluloid in terminal I don't see any error message.

When I start it with parameter celluloid --mpv-options=--msg-level=all=trace

I see this:
```
540, 14, -1, single]
** Message: 14:34:53.529: [input] mouse move 540/14
** Message: 14:34:53.529: [cplayer] Run command: ignore, flags=73, args=[]
** Message: 14:34:53.531: [cplayer] Run command: mouse, flags=64, args=[538, 14, -1, single]
** Message: 14:34:53.531: [input] mouse move 538/14
** Message: 14:34:53.531: [input] No key binding found for key 'MOUSE_MOVE'.
** Message: 14:34:53.531: [cplayer] Run command: mouse, flags=64, args=[538, 14, -1, single]
** Message: 14:34:53.531: [input] mouse move 538/14
** Message: 14:34:53.531: [cplayer] Run command: ignore, flags=73, args=[]
Segmentation fault (core dumped) 
```
So log is useless.

Also starting app with gdb show me this:
https://pastebin.ubuntu.com/p/df82437zS4/

**Comment by gnome-mpv** [comment]
It seems that OpenMandriva's `libmpv` is a bit broken. I tried using `libmpv` built manually from upstream's release tarball and the crashing stops.

**Comment by AngryPenguinPL** [comment]
Maybe problem is latest git mpv 0.30. OpenMandriva Cooker recently switched from a stable version to git.
