### ISSUE TITLE
Forward/rewind via arrow keys is totally unpredictable

### ISSUE THREAD

**Issue by fbruetting** [celluloid-player/celluloid#469]
Overview Description: It is nearly impossible to sift through a video for searching a specific point in time, because of the skip stepping varying in a not at all comprehensive manner.

Steps to Reproduce:
1. Press arrow right
2. Press arrow right
3. Press arrow right
3. Sometimes pressing arrow right a fourth time is necessary

Actual Results: Move by 5s + move by 5s [+ move by 5s] + move by anything between 20s and 1m.

Expected Results: Celluloid should move three times by the same timestep.

Version: 0.17

Additional Information: Flatpak installation

**Comment by gnome-mpv** [comment]
Is it the same issue as #385?

**Comment by fbruetting** [comment]
Ah yes, seems I forgot that I already filed a report. ^^
