### ISSUE TITLE
Wny warning on mpv version

### ISSUE THREAD

**Issue by mc4man** [celluloid-player/celluloid#473]
Overview Description:
When running from terminal see
** (io.github.celluloid_player.Celluloid:15346): WARNING **: 14:55:59.668: Minimum mpv version requirement (0.29.0) not met

Steps to Reproduce:
1.run from terminal

Actual Results:warning

Expected Results: no warning

Version: v0.17

Additional Information:
The actual mpv source version used for libmpv is 0.29.1 
As far as libmpv it's actual version as shown  in /usr/lib/x86_64-linux-gnu/pkgconfig/mpv.pc is 1.102.0
Obviously ? it's using the provided libmpv so why warning?
``ldd /usr/local/bin/celluloid  |grep mpv
	libmpv.so.1 => /usr/lib/x86_64-linux-gnu/libmpv.so.1 (0x00007f9f37edb000)``

**Comment by gnome-mpv** [comment]
Can you post the output of `G_MESSAGES_DEBUG=all celluloid --mpv-options='--idle=no'`?

**Comment by mc4man** [comment]
I now see issue ,closing
(- was seeing if celluloid would work with latest git (lib)mpv,(there are some issues), I used source from an mpv only build  where the Release file uses a git head vs. 0.29.1-unknown
