### ISSUE TITLE
App description is too technical

### ISSUE THREAD

**Issue by clefebvre** [celluloid-player/celluloid#475]
Hi,

Although a "GTK+ frontend for mpv" is very accurate and describes precisely what Celluloid is to a developer, it doesn't describe what it is to a user.

Casual desktop users might not know what a toolkit is, or a frontend, or even MPV. If Celluloid is that great media player which plays their favorite movies, it should probably describe itself according to what it does, more so than what it's built with. It should definitely describe itself in terms they can understand, especially if it's installed by default (and it has great potential to be, it's a very good player).

Imo, the intended audience for the .desktop file and the appdata is made of desktop users. Technical details of implementation are probably better in the about dialog, the git page, the README/Credits.

**Comment by p3732** [comment]
Feel free to use or adapt this text. I put the information that is of interest to casual users first, while providing the more technical details later.

```<p>
   Celluloid is a simple media player that can play virtually all video and audio
   formats. It supports playlists and MPRIS2 media player controls. The design of
   Celluloid follows the GNOME HIG, but can also be adapted for other systems that
   don't use client-side decorations (CSD). It is based on the mpv library and GTK.
  </p>
```
For the .desktop file I suggest ``A simple media player with playlist support.``

**Comment by clefebvre** [comment]
Hi @p3732, I think that's a good app description. It's perfect within an app store (pkg or flatpak description). As you browse it and see many other players, you might ask yourself "why this one?".... and that's where features (playlist, MPRIS support..etc) and implementation details (mpv backend, GTK toolkit) become relevant.

As you browse your application menu and go through the list of what's already installed on your system though, you're not shopping for the best player, you're discovering what's there, and so what's relevant to you at that moment aren't features or implementation details but general descriptions and purpose.

For this reason, I'd recommend sticking to what the app is and does in .desktop file.

Here are some examples.

MPV:

```
Name=mpv Media Player
GenericName=Multimedia player
Comment=Play movies and songs
```

Spotify:

```
Name=Spotify
GenericName=Music Player
```

Rhythmbox:

```
Name=Rhythmbox
GenericName=Music Player
X-GNOME-FullName=Rhythmbox Music Player
Comment=Play and organize your music collection

```

Celluloid could use something like:

```
Name=Celluloid
GenericName=Multimedia Player
X-GNOME-FullName=Celluloid Multimedia Player
Comment=Play movies and videos
```
