### ISSUE TITLE
Volume setting from mpv.conf being ignored

### ISSUE THREAD

**Issue by str225** [celluloid-player/celluloid#477]
Overview Description:
The --volume option from mpv.conf is being ignored, celluloid sets the volume to the last volume we've choose before instead.

Steps to Reproduce:
1. Enable mpv.conf in settings
2. Set volume=<0-100> in mpv.conf
3. Play a video

Actual Results:
Volume setting is ignored

Expected Results:
Celluloid should set the volume according to the --volume option.

Version:
celluloid-0.17-2.fc31.src.rpm from rpmfusion

**Comment by gnome-mpv** [comment]
Would an option that toggles between stored volume and volume from the config file suit your use case?

There's no way to differentiate between an option set to its default value and an option that's not set so it's not possible to do this automatically. At least not without parsing the config file ourselves, which is fragile.

**Comment by str225** [comment]
> Would an option that toggles between stored volume and volume from the config file suit your use case?
It would, but i think that'd be overkill, so it'd be better to just keep the current behaviour then.
