### ISSUE TITLE
Every time crashing with segmentation fault (core dumped) on Arch Linux when I click a menu button.

### ISSUE THREAD

**Issue by Kerrung** [celluloid-player/celluloid#480]
Hi!

Overview Description:
Every time crashing with segmentation fault (core dumped) on Arch Linux when I click a menu button.
Version: https://www.archlinux.org/packages/community/x86_64/celluloid/

Steps to Reproduce:
1. Run Celluloid;
2. Click a menu button.
3.
![Screenshot from 2019-10-27 00-00-58](https://user-images.githubusercontent.com/36989404/67624652-eaae3880-f84c-11e9-8d49-4d2d85fca46a.png)

**Comment by gnome-mpv** [comment]
Does this happen with the git version? You can use this AUR package: https://aur.archlinux.org/packages/celluloid-git/

**Comment by Kerrung** [comment]
> Does this happen with the git version? You can use this AUR package: https://aur.archlinux.org/packages/celluloid-git/

Works perfect with celluloid-git!

**Comment by TomLouisKeller** [comment]
I have the same issue.
The Arch Linux package version is 0.17, which was tagged on August 7.
So the questions is, could please create a new tag based on master, 
so the fix propagates to the rest of the Arch Linux users?

Thank you for Celluloid, i really enjoy it =)

**Comment by gnome-mpv** [comment]
> When the new fixed release?

I'll make a new release in 1-2 weeks if no serious bugs are found.

**Comment by mrxspice** [comment]
crashes for me too "segmentation fall" cannot install from git either: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.7/site-packages/tqdm-4.31.1.dist-info'
==> ERROR: A failure occurred in build().

**Comment by glaubersm** [comment]
I also use celluloid 0.17 on Arch Linux and it rashes here too.
Celluoid also crashes when I click on the seek bar during playback.
Fortunately celluloid-git fixes both crashes.

**Comment by jiri-one** [comment]
I can confirm this bug too, same like Kerrungs report. Btw. I use Arch :).

**Comment by gnome-mpv** [comment]
[v0.18](https://github.com/celluloid-player/celluloid/commit/e23a68d42cad37f0e2d4798df38cdc9690f16795) has been released.
