### ISSUE TITLE
[feature request] 200% volume (vlc-like)

### ISSUE THREAD

**Issue by Krafting** [celluloid-player/celluloid#490]
Overview Description: On VLC we can turn the volume up to 200% 
I like this feature from vlc, It would be great if it comes to celluloid too! :)
(if some people doesnt like the 200% volume setting, adding an option to disable/enable it would fix this)

thanks, I love your work :)

**Comment by gnome-mpv** [comment]
You can now use the option `volume-max` in your mpv config file to set the maximum volume.
