### ISSUE TITLE
Cannot "Open Location" in Celluloid

### ISSUE THREAD

**Issue by mgunt** [celluloid-player/celluloid#492]
Overview Description: Whenever I try to click on "Open Location" in Celluloid, I would not get a dialog box.

Steps to Reproduce:
1. Install Celluloid 0.18
2. Click on "Open Location" in menu.

Actual Results: Nothing happened.

Expected Results: Open dialog.

Version: 0.18

Additional Information: Manjaro Linux KDE

This is what I get in the terminal when I open "Open Location" in Celluloid.

`(io.github.celluloid_player.Celluloid:26508): GLib-GIO-CRITICAL **: 00:00:12.418: g_simple_action_activate: assertion 'simple->parameter_type == NULL ? parameter == NULL : (parameter != NULL && g_variant_is_of_type (parameter, simple->parameter_type))' failed
`

**Comment by gnome-mpv** [comment]
I just tried reproducing this with the latest ISO, but everything seems to be working fine.

**Comment by mgunt** [comment]
@gnome-mpv I think the issue resolved itself. Thank you for responding.
