### ISSUE TITLE
[Feature request] Subtitle delay and customization

### ISSUE THREAD

**Issue by Krafting** [celluloid-player/celluloid#493]
Overview Description:
Add a setting in the setting page for subtitles delay 
and also changing size, color, border etc...

**Comment by thwaller** [comment]
Both delay and hasten would be nice.

**Comment by Silejonu** [comment]
You can already easily do this via a config file or the extra mpv options field.
You can also delay and hasten subtitles with X and Z.

**Comment by Krafting** [comment]
I'm just asking for setting easy to use I don't have time to read the whole option page of MPV
Maybe celluloid should make its own "option page" to put the most used options

**Comment by Silejonu** [comment]
X and Z are already documented in the "Keyboard Shortcuts" menu of Celluloid.
The mpv manual is very well made and easy to navigate, there is no need to duplicate information. Having a separate Celluloid manual would be a waste of resources as it would require extra work, and it would need to be updated every time mpv changes something.
You don't have to read the whole option page of mpv. Just look at the subtitles section here: https://mpv.io/manual/master/#subtitles or search the page for the term "subtitles", "font", "color" or any other relevant term. This document is usually easy to read, covering everything you need, and up-to-date.

**Comment by Krafting** [comment]
I don't have any arguments, you're right ahah
I'll close this issue, thanks for the information tho ! :)
