### ISSUE TITLE
"run" keybinding behavior disparity with mpv

### ISSUE THREAD

**Issue by eao** [celluloid-player/celluloid#496]
I have the following keybinding in input.conf:
`a run "code"`

When I press "a" in mpv, VSCode opens.

When I press "a" in Celluloid, nothing happens.

Using the flatpak release if that affects anything.

**Comment by gnome-mpv** [comment]
I think that's exactly how it's supposed to work. Programs inside the sandbox shouldn't be able to run programs outside of it.

Your example should work fine if you're not using Flatpak.

**Comment by eao** [comment]
Thought that might be it, thank you for the prompt reply.  I want this functionality, but unfortunately I am on Ubuntu 16.04 so I do not have gtk >= 3.22, and the xenial package in launchpad is from 2016-05-18.  Do you know if there is any way I can get a new version of Celluloid without updating my OS?  Sorry, I know this is a problem on my end and not with Celluloid but I would like to be able to use Celluloid on my current system with this functionality.

**Comment by gnome-mpv** [comment]
> Do you know if there is any way I can get a new version of Celluloid without updating my OS?

You can try [Nix](https://nixos.org/nix/).

**Comment by eao** [comment]
Forgot to comment saying that installing with Nix works great!  Thank you.  When launching with CLI I get a few weird warnings but ignoring them seems to work fine.
