### ISSUE TITLE
flatpak version can not play a disc

### ISSUE THREAD

**Issue by glaubersm** [celluloid-player/celluloid#497]
Overview Description:

Steps to Reproduce:
1. insert and mount a dvd disc
2. open celluloid, click on "+" in the upper left corner, select "Open disc", click on the previously inserted disc
3.

Actual Results:
error message says that playback was terminated, reason "loading failed". 

Expected Results:
celluloid plays the disc

Version:
0.18

Additional Information:
celluloid 0.18 installed from Arch repositories on the same system plays the same disc as expected.

**Comment by TingPing** [comment]
Duplicate of #331
