### ISSUE TITLE
Cannot save playlist

### ISSUE THREAD

**Issue by pkail** [celluloid-player/celluloid#499]
Overview Description:
"Save Playlist" option from menu gives dialogue box with no option to save.

Steps to Reproduce:
1. Select 'Save Playlist' from menu.
2.
3.

Actual Results:
Dialogue box with options to cancel and open, but not to save.

Expected Results:
"Save Playlist" should allow one to save the playlist.
Version:
0.17
Additional Information:

**Comment by gnome-mpv** [comment]
Are you using Flatpak?

**Comment by pkail** [comment]
Yes.

**Comment by gnome-mpv** [comment]
I managed to reproduce this with KDE but not with GNOME, so this might be a bug in `xdg-desktop-portal-kde`.

**Comment by gnome-mpv** [comment]
It seems that the bug has already been fixed. I just tested again with a newer version of `xdg-desktop-portal-kde` and I wasn't able to reproduce the bug anymore.
