### ISSUE TITLE
Speed white, therefore invisible on a light background.

### ISSUE THREAD

**Issue by pkail** [celluloid-player/celluloid#500]
Overview Description:
The speed (shown by pressing the bracket keys) is white.  It would be much better for it to be red, for example.  Many videos have a light background and the white is almost invisible).
Steps to Reproduce:
1.Press bracket key.
2.
3.

Actual Results:

Expected Results:

Version:
0.17
Additional Information:

**Comment by gnome-mpv** [comment]
There should be a black border around the text so that it's visible on both light and dark background.

![celluloid](https://user-images.githubusercontent.com/8312231/70075466-c8020300-15f4-11ea-8e0c-4d782f0864f2.png)

Does it look different on your machine?

**Comment by pkail** [comment]
I didn't look closely enough to see the border.  Sorry to bother you!
