### ISSUE TITLE
Switching to/from full screen mode by using "F" key should be case insensitive

### ISSUE THREAD

**Issue by goarvic** [celluloid-player/celluloid#501]
Overview Description: Switching to/from full screen mode by using "F" key should be case insensitive. If you have enabled Caps Lock mode, the F key is not working switching screen mode. This function should be case insensitive.

Steps to Reproduce:
1. Enable Caps Lock
2. When playing video try to switch to full screen

Actual Results:
It doesn't working

Expected Results:
Switch to fullscreen mode

Version: 0.18

**Comment by gnome-mpv** [comment]
For switching to/from fullscreen, you can use `F11` instead to avoid this problem.

There are many keybindings that have do different things based on the case, e.g. `q` and `Q`, so it's not possible to just make all bindings case insensitive. What might be a better solution would be to have an option to ignore caps lock, but this is better implemented in mpv itself.

**Comment by goarvic** [comment]
_For switching to/from fullscreen, you can use F11 instead to avoid this problem._

Of course, but i think it is usually a standard for most player programs to use "F" key. If other shortcuts must be case sensitive, it should be good that some like this would be insensitive.

As a user, it doesn't make much sense that this shortcut only works depending on the status of the Caps Lock.

**Comment by gnome-mpv** [comment]
You can simulate case insensitivity just for this key by using an input config file to bind `F` to `cycle fullscreen` in addition to `f`.

**Comment by Silejonu** [comment]
This is the default behaviour of mpv, which differentiates shortcuts depending on whether or not they are in capital letters. Celluloid is an mpv frontend, so it should try to mpv defaults as much as possible to avoid confusion, bugs, and weird behaviours. Especially since you can already easily add your custom keybindings.
