### ISSUE TITLE
Home Page Installation Links need an update

### ISSUE THREAD

**Issue by spectrumcomputing** [celluloid-player/celluloid#505]
Overview Description:
Links to installation guides on home page still link to gnome-mpv installs

Steps to Reproduce:
1. Click on https://celluloid-player.github.io/installation.html
2.
3.

Actual Results:
Takes you to old gnome-mpv install

Expected Results:
For example the fedora link takes you to:
https://admin.rpmfusion.org/pkgdb/package/free/gnome-mpv/

But should go to:

https://admin.rpmfusion.org/pkgdb/package/free/celluloid/

Version:

Additional Information:
Thank you.

**Comment by gnome-mpv** [comment]
https://github.com/celluloid-player/celluloid-player.github.io/commit/1da56c59902be98001918a129fbf7c8e7e1e3f46
