### ISSUE TITLE
Some entries in the Keyboard Shortcuts window are missing and/or use outdated/discouraged keybindings

### ISSUE THREAD

**Issue by Silejonu** [celluloid-player/celluloid#509]
Overview Description:
The Keyboard Shortcuts window shows a few outdated, discouraged or even discontinued shortcuts. Here are the "culprits", as shown from the [mpv manual](https://mpv.io/manual/master/#keyboard-control):
> w and W
>     Decrease/increase pan-and-scan range. The e key does the same as W currently, but use is discouraged.
> j and J
>     Cycle through the available subtitles.
> z and Z
>     Adjust subtitle delay by +/- 0.1 seconds. The x key does the same as Z currently, but use is discouraged.
> r and R
>     Move subtitles up/down. The t key does the same as R currently, but use is discouraged.

Steps to Reproduce:
1. Open the Keyboard Shortcuts and look at the entries

Actual Results:
Some shortcuts are outdated (i to cycle through the subtitles does not work, for instance), discouraged, or missing.

Expected Results:
The shortcuts shown should be the default (and working) mpv shortcuts.

Version:
0.18

Additional Information:
This is debatable, but all letters are shown as uppercase, while mpv differentiates between lowercase and uppercase letters for its shortcuts. Wouldn't it be better to write, for instance, `p` instead of `P` and `P` instead of `<Shift>P`? For novice users, adding a line or two at the top explaining that lowercase and uppercase letters are differentiated could clear any confusion as well.

**Comment by Silejonu** [comment]
I made a pull request to correct the entries. #510 
It doesn't change anything regarding lowercase/uppercase, though.

**Comment by gnome-mpv** [comment]
> This is debatable, but all letters are shown as uppercase, while mpv differentiates between lowercase and uppercase letters for its shortcuts. Wouldn't it be better to write, for instance, p instead of P and P instead of <Shift>P? For novice users, adding a line or two at the top explaining that lowercase and uppercase letters are differentiated could clear any confusion as well.

GtkShortcutsWindow doesn't let you do that; it always display the keys in uppercase even if you use lowercase in your shortcuts. In any case, I think it's better to display `Shift` as a separate key anyway to be consistent with GNOME applications.

**Comment by Silejonu** [comment]
> GtkShortcutsWindow doesn't let you do that; it always display the keys in uppercase even if you use lowercase in your shortcuts. In any case, I think it's better to display `Shift` as a separate key anyway to be consistent with GNOME applications.
Well, in this case, keeping things as is is probably the most elegant thing to do, I guess.

Also, just to be sure as this is my first pull request: I made a fork, and then made a pull request. Is this the preferred way of doing it? And I can safely delete the fork, now, right?

**Comment by gnome-mpv** [comment]
> Also, just to be sure as this is my first pull request: I made a fork, and then made a pull request. Is this the preferred way of doing it? And I can safely delete the fork, now, right?

Yes and yes.
