### ISSUE TITLE
Is there a way to adjust the gnome mpv setting to reduce integrated graphics power consumption?

### ISSUE THREAD

**Issue by jendrina69** [celluloid-player/celluloid#513]
Overview Description:
The same Lenovo X1 Carbon Machine played the same video on Windows 10 and Linux (Fedora 31 with gnome mpv). The integrated graphics power consumption on linux is around 10 times higher than windows.
Steps to Reproduce:
1. Play a video on Windows 10 and measure the integrated graphics power using intel's thermal analysis tool.
2. Play the same video on Fedora 31 using gnome mpv and measure the integrated graphics power using the same tool.
3. Compare the two results.

Actual Results:
The integrated graphics power on linux is around 10 times higher than windows.
![image](https://user-images.githubusercontent.com/59222089/71440698-840ca480-2741-11ea-8cd6-7cbec526ba69.png)

Expected Results:
The power consumption on windows and linux should be on-par.
Version: 0.16-3.fc31

Additional Information:

**Comment by gnome-mpv** [comment]
Try enabling hardware decoding (put `hwdec=auto` in your config file).

**Comment by jendrina69** [comment]
Thanks. We will try it.

**Comment by DanielValahul** [comment]
I kinda have the same problem. On fedora 31 with gstreamer1-vaapi and libva-intel-driver celluloid consumes 1% cpu and totem (gnome's default player) around 4-5% cpu. However battery life estimates are quite similar. Shouldn't there be a difference? 

I added hwdec=auto and profile=gpu-hq in a .conf file for celulloid

**Comment by gnome-mpv** [comment]
@DanielValahul I think that would depend on the specifics of your hardware and/or how powertop estimates power consumption. Unless Celluloid's consumption greatly diverges from regular mpv, I don't think there's anything we can do.

**Comment by gnome-mpv** [comment]
Closing since it looks like enabling hardware acceleration fixes the issue. Feel free to reopen if this is not the case.
