### ISSUE TITLE
[enhancement request] Panels behavior in fullscreen

### ISSUE THREAD

**Issue by durunduk** [celluloid-player/celluloid#515]
I would like to have such an option: control elements and the window title to pop up in full-screen mode only if the mouse is either in the lower or upper part of the window, suppose + -20-50% of the size of the panel with control elements and the title. It is well implemented in "Windows Media Player Classic" for example. Because in conditions of uncontrollable potential cursor shaking from time to time, the panels pop up and cover part of the video, you have to turn off the mouse from usb or for now i use dconf "control-unhide-cursor-speed" parameter to evade this.

**Comment by Silejonu** [comment]
If this is of any help, SMPlayer implemented it, and it works perfectly with mpv, so maybe part of the code can be reused to achieve this result.

**Comment by TingPing** [comment]
SMPlayer is a Qt application and has nothing in common, UI wise, with Celluloid.
