### ISSUE TITLE
Inconsistent window size when opening a video

### ISSUE THREAD

**Issue by nostdm** [celluloid-player/celluloid#518]
**Version:** Celluloid 0.18
**Session:** Gnome 3.14 (Wayland)
**MPV:** mpv 0.32.0

**Description:**

Whenever I open a video in Celluloid it seems to start with an arbitrary window size. Sometimes even the video frame goes outside of the GTK window decorations - i.e. the decorations are 100% of the screen as normal but video is more than 100% - resulting in just part of the video being visible. Sometimes I open the same video multiple times and it starts with different window dimensions. Also sometimes the Celluloid window acts as a maximized window despite not being maximized - i.e. the window is clearly not maximized but the Gnome maximize command does nothing and the window can only be minimized. 

I tried playing with the following settings in `mpv.conf` but none of them have fully fixed the issue:

```
border
geometry=100%:100%
ontop=yes
fullscreen=no
window-maximized=yes
window-minimized=no
keep-open=yes
autofit=100%
autofit-larger=100%x100%
force-window=immediate
force-window-position
keepaspect
no-keepaspect-window
window-scale=1
hidpi-window-scale
```

I also have disabled the auto-resize setting in the preferences menu.

**Comment by gnome-mpv** [comment]
Are you trying to make it auto-maximize on startup?

**Comment by nostdm** [comment]
Ideally I would like the GTK window to be maximized on start and the video buffer to keep its aspect ratio but to resize to fit the GTK window. At the moment I can get it to be maximized but then the video buffer either doesn't fit on the screen or the entire application window is bigger than the display resolution. It's hard to tell exactly what's going wrong since the window sizing seems to be quite arbitrary (some videos open too small some open too large etc.).

**Comment by rnul** [comment]
I have the same issue. Video size is all over the place when opening files. Linux Mint XFCE.

**Comment by danialkeimasi** [comment]
I have the same issue too.
every time I open a video it will be in a small wide size, like this:
![image](https://user-images.githubusercontent.com/33510850/154657724-412951e5-c155-40a3-b3e7-e9bed1f86515.png)

**Comment by Aleksanaa** [comment]
Same issue.

**Comment by canadaduane** [comment]
I'm seeing something similar to @danialkeimasi. Running on Gnome/Wayland (Pop!_OS 22.04):

![image](https://user-images.githubusercontent.com/129/171296887-147d90c5-424c-4536-8a36-9ed37a359ed6.png)


```
$ flatpak info io.github.celluloid_player.Celluloid

Celluloid - GTK+ frontend for mpv

          ID: io.github.celluloid_player.Celluloid
         Ref: app/io.github.celluloid_player.Celluloid/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.23
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 30.1 MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: b409e8d10b500ec9b5df2a0dc605819e8a1dc567cd8d0a99e8b344da220f8b6a
      Parent: 52bd7cb042285e731fe8a75b85b8fa8cc9a3b86869e0e7d86a7ef9ea6a10df8c
     Subject: Update 2 modules (20e3329f)
        Date: 2022-05-23 18:02:42 +0000
```

**Comment by canadaduane** [comment]
I've been able to identify a likely cause of the "small video" problem that I and @danialkeimasi are seeing. When I turn on 200% scaling for my hidpi screens, this happens. When I turn it off (back to 100%) then Celluloid behaves correctly.

@danialkeimasi Can you confirm that this is true in your case as well?
