### ISSUE TITLE
Livestream TV

### ISSUE THREAD

**Issue by Axel-Erfurt** [celluloid-player/celluloid#520]
Overview Description:

Steps to Reproduce:
celluloid http://zdf-hls-01.akamaized.net/hls/live/2002460/de/high/master.m3u8

Actual Results:
no sound

Expected Results:
sound

Version:
0.17

Additional Information:
After the ZDF has changed his Playlist structure Celluloid can no longer handle it.
There is no sound.
When looking into the master.m3u8 I see that they are now sending video and audio on separate URL to offer different audio tracks.

Audio:
https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/5/5.m3u8

Video:
https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/3/3.m3u8

**Comment by gnome-mpv** [comment]
I can't see any of the links; I'm getting 403 error from all of them.

> After the ZDF has changed his Playlist structure Celluloid can no longer handle it.
> There is no sound.
> When looking into the master.m3u8 I see that they are now sending video and audio on separate URL to offer different audio tracks.

Do you get sound if you try playing it with plain mpv?

**Comment by Axel-Erfurt** [comment]
that's the command I've used

`celluloid http://zdf-hls-01.akamaized.net/hls/live/2002460/de/high/master.m3u8`

celluloid plays without audio

with 

`mpv http://zdf-hls-01.akamaized.net/hls/live/2002460/de/high/master.m3u8`

same, video without audio

`vlc http://zdf-hls-01.akamaized.net/hls/live/2002460/de/high/master.m3u8`

audio without video

the content of the playlist:

> #EXTM3U
> 
> 
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="A1.1+A2.1+A3.1-2013556649",NAME="TV Ton",LANGUAGE="deu",DEFAULT=YES,URI="https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/5/5.m3u8"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="A1.1+A2.1+A3.1-2013556649",NAME="Originalton",LANGUAGE="mul",URI="https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/6/6.m3u8"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="A1.1+A2.1+A3.1-2013556649",NAME="Audio-Deskription",LANGUAGE="deu",URI="https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/7/7.m3u8"
> 
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="A1.1+A2.1+A3.1-892643947",NAME="TV Ton",LANGUAGE="deu",DEFAULT=YES,URI="https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/5/5.m3u8"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="A1.1+A2.1+A3.1-892643947",NAME="Originalton",LANGUAGE="mul",URI="https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/6/6.m3u8"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="A1.1+A2.1+A3.1-892643947",NAME="Audio-Deskription",LANGUAGE="deu",URI="https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/7/7.m3u8"
> 
> #EXT-X-STREAM-INF:CODECS="avc1.4d401f,mp4a.40.2",BANDWIDTH=542359,AVERAGE-BANDWIDTH=452359,AUDIO="A1.1+A2.1+A3.1-2013556649",FRAME-RATE=25.000,RESOLUTION=480x270
> https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/1/1.m3u8
> #EXT-X-STREAM-INF:CODECS="avc1.4d401f,mp4a.40.2",BANDWIDTH=542359,AVERAGE-BANDWIDTH=452359,AUDIO="A1.1+A2.1+A3.1-892643947",FRAME-RATE=25.000,RESOLUTION=480x270
> https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/1/1.m3u8
> #EXT-X-STREAM-INF:CODECS="avc1.4d401f,mp4a.40.2",BANDWIDTH=1044619,AVERAGE-BANDWIDTH=840619,AUDIO="A1.1+A2.1+A3.1-2013556649",FRAME-RATE=25.000,RESOLUTION=640x360
> https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/2/2.m3u8
> #EXT-X-STREAM-INF:CODECS="avc1.4d401f,mp4a.40.2",BANDWIDTH=1044619,AVERAGE-BANDWIDTH=840619,AUDIO="A1.1+A2.1+A3.1-892643947",FRAME-RATE=25.000,RESOLUTION=640x360
> https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/2/2.m3u8
> #EXT-X-STREAM-INF:CODECS="avc1.4d401f,mp4a.40.2",BANDWIDTH=2128446,AVERAGE-BANDWIDTH=1678446,AUDIO="A1.1+A2.1+A3.1-2013556649",FRAME-RATE=25.000,RESOLUTION=960x540
> https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/3/3.m3u8
> #EXT-X-STREAM-INF:CODECS="avc1.4d401f,mp4a.40.2",BANDWIDTH=2128446,AVERAGE-BANDWIDTH=1678446,AUDIO="A1.1+A2.1+A3.1-892643947",FRAME-RATE=25.000,RESOLUTION=960x540
> https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/3/3.m3u8
> #EXT-X-STREAM-INF:CODECS="avc1.640028,mp4a.40.2",BANDWIDTH=4375402,AVERAGE-BANDWIDTH=3415402,AUDIO="A1.1+A2.1+A3.1-2013556649",FRAME-RATE=50.000,RESOLUTION=1280x720
> https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/4/4.m3u8
> #EXT-X-STREAM-INF:CODECS="avc1.640028,mp4a.40.2",BANDWIDTH=4375402,AVERAGE-BANDWIDTH=3415402,AUDIO="A1.1+A2.1+A3.1-892643947",FRAME-RATE=50.000,RESOLUTION=1280x720
> https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/4/4.m3u8

**Comment by Axel-Erfurt** [comment]
maybe there is geoblocking (Germany), therefore you can not see it.

**Comment by gnome-mpv** [comment]
> mpv http://zdf-hls-01.akamaized.net/hls/live/2002460/de/high/master.m3u8
> same, video without audio

If mpv is also having the same problem, then this should be reported to them.

**Comment by Axel-Erfurt** [comment]
maybe that helps, if not ignore it

I can play it with audio and video in **mpv** with

`ffmpeg -i https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/5/5.m3u8 -i https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/4/4.m3u8 -async 1 -c copy -f nut - | mpv -
`

**Comment by gnome-mpv** [comment]
You should be able to do something similar with Celluloid using named pipes:

```
mkfifo /tmp/pipe && \
ffmpeg -nostdin -y \
-i https://zdf-hls-01.akamaized.net/hls/live/2002460/de/46a8d40c9f1b9df43b8c9a85a4379d92/5/5.m3u8 \
-i https://zdf-hls-01.akamaized.net/hls/live/2002460-b/de/46a8d40c9f1b9df43b8c9a85a4379d92/4/4.m3u8 \
-async 1 -c copy -f nut /tmp/pipe & \
celluloid /tmp/pipe
```

You may also need to disable metadata prefetch for this to work.

**Comment by Axel-Erfurt** [comment]
Thanks, that works.
