### ISSUE TITLE
Lunch application with subtitles disabled.

### ISSUE THREAD

**Issue by SweDennis** [celluloid-player/celluloid#522]
Overview Description: Unless I've missed something, there's no way to launch the application with subtitles disabled. If they are present in the media directory, they will, by default, be used.
It would be nice to be able to have them off by default, and enabled as needed. I never want them, but they are more often than not present in downloaded content directories, and I have to disable subtitles every time. Not a big thing by no means, but still. :)

Already in there somewhere and I've missed it?

/Dennis

Steps to Reproduce:
1. Launch media file with subtitles
2. Disable subtitles in preferences
3.

Actual Results: Subtitles are used every time

Expected Results:

Version: 0.17

Additional Information:

**Comment by gnome-mpv** [comment]
Putting `--sub=no` in `Extra MPV Options` should do what you want.

**Comment by SweDennis** [comment]
Tested, and verified.
Many thanks, case closed.

Regards,
/Dennis
