### ISSUE TITLE
--autofit and --geometry are double the size with hidpi screens in Gnome 3

### ISSUE THREAD

**Issue by homocomputeris** [celluloid-player/celluloid#525]
### Important Information

Provide following Information:
- mpv version
```console
$ mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2

$ celluloid --version
Celluloid 0.18
```
- Linux Distribution and Version
ArchLinux
```console
$ uname -a
Linux box 5.5.5-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 20 Feb 2020 18:22:57 +0000 x86_64 GNU/Linux
```
- Source of the mpv binaries
Official repos
- If known which version of mpv introduced the problem
- Window Manager and version
```console
$ mutter --version
mutter 3.34.4
$ gnome-shell --version
GNOME Shell 3.34.4
```
- GPU driver and version
```console 
$ glxinfo | grep Mesa
client glx vendor string: Mesa Project and SGI
    Device: Mesa DRI Intel(R) Iris Graphics 540 (Skylake GT3e)  (0x1926)
OpenGL renderer string: Mesa DRI Intel(R) Iris Graphics 540 (Skylake GT3e) 
OpenGL core profile version string: 4.6 (Core Profile) Mesa 19.3.4
OpenGL version string: 3.0 Mesa 19.3.4
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.4
```

### Reproduction steps
In Gnome3, use a 3840x2160 screen with `org.gnome.desktop.interface scaling-factor 0` (or 200% scaling manually).
Use `--geometry`, `--autofit`, `--autofit-larger` or `--autofit-smaller` with a percent value, say 50% in Celluloid or mpv.conf.
Play a 1920x1080 video.

### Expected behavior
Window should occupy only 50%

### Actual behavior
With the 50% it occupies all the screen. With 25% more than 50%.

It works fine in mpv without Celluloid.

### Config
```
profile=gpu-hq
audio-file-auto=fuzzy
audio-channels=stereo
sub-auto=fuzzy
autofit=50%
```

**Comment by homocomputeris** [comment]
Probably the same/relevant to  #518

**Comment by RlndVt** [comment]
This doesn't seem to have been fixed. Using  0.19 on arch but the scaling still seems to be ignored.

Also I noticed in the patch that a int (now replaced by gint) is used for the scaling factor. What if the scaling factor is not a integer?

**Comment by gnome-mpv** [comment]
> This doesn't seem to have been fixed. Using 0.19 on arch but the scaling still seems to be ignored.

I actually have the opposite problem now; window sizes are smaller than they should be. Is this what you're seeing too?

> Also I noticed in the patch that a int (now replaced by gint) is used for the scaling factor. What if the scaling factor is not a integer?

`gdk_window_get_scale_factor()` returns a `gint`, so scale factors can only be integers. From my understanding, if the scaling factor you set is not an integer, the display will be scaled to the next integer factor beyond the one you set. To get to the correct size, the resulting _image_ will then be scaled back down, but the scale factor presented to applications is always integer.

**Comment by RlndVt** [comment]
No, for me nothing seemed to change.

**Comment by gnome-mpv** [comment]
@RlndVt Can you try running Celluloid with `geometry=50%` and post 2 screenshots: one with 100% scale and another with 200% scale?

**Comment by RlndVt** [comment]
Could you confirm how to? Do I pass it as a command line option? I didn't see it specified in `man celluloid`.

**Comment by gnome-mpv** [comment]
@RlndVt You can either put that in your config file, or pass `--mpv-geometry=50%` as a command line option.

**Comment by RlndVt** [comment]
1024 × 576 @ 100%:
![1024 × 576](https://user-images.githubusercontent.com/1658570/80866189-b731e800-8c8d-11ea-9fd3-6886d44f1c8c.png)

3840 x 1606 @ 50%:
![3840 × 1606](https://user-images.githubusercontent.com/1658570/80866192-bac56f00-8c8d-11ea-8732-5e0ded4b5f38.png)

**Comment by gnome-mpv** [comment]
@RlndVt I was referring to HiDPI scaling. You can change the scaling factor [in GNOME Settings under the Displays section](https://i.redd.it/ml5tq1x99jr01.png). With `geometry=50%`, the width/height of the window should be 50% of the entire screen. I wanted to see how it behaves with different scaling factors.

**Comment by RlndVt** [comment]
Oke will do! You mean 50% at launch? and then 50% of the video file?

The screenshots do show the unexpected behaviour this bug report aims to fix doesn't it?

**Comment by gnome-mpv** [comment]
> Oke will do! You mean 50% at launch? Meaning 50% of the video file size?

50% at launch, and don't play a video.

> The screenshots do show the unexpected behaviour this bug report aims to fix doesn't it?

They look wrong, but it's a bit different from the original bug. In the original bug, the screen size was miscalculated. For this one, it looks like the video size isn't being scaled correctly.

**Comment by RlndVt** [comment]
Ahh oke, I'll create a new bug report for that issue.

100%
![Screenshot from 2020-05-03 12-23-13](https://user-images.githubusercontent.com/1658570/80911870-4ba55480-8d39-11ea-877e-b3d3bd38695f.png)

200%
![Screenshot from 2020-05-03 12-23-43](https://user-images.githubusercontent.com/1658570/80911872-53fd8f80-8d39-11ea-823f-4bcfb2ca2a31.png)

and a bonus 300%:
![Screenshot from 2020-05-03 12-24-09](https://user-images.githubusercontent.com/1658570/80911876-5cee6100-8d39-11ea-9f07-e07593554183.png)

so all seems fine
