### ISSUE TITLE
How to use user scripts?

### ISSUE THREAD

**Issue by junglized** [celluloid-player/celluloid#527]
Hi,

This is actually a question rather than bug report. I'm new to Linux and I've just installed Linux Mint with Cinnamon UI. I see that Celluloid is default media player here. I got to the point where I've added two user scripts to Celluloid by going into Preferences > Plugins, clicking + and selecting appropriate files. I see scripts being there on the list, I can remove them, but how to launch them? The ones I need are equalizer and pitch control. I'll be grateful for some help. I looked in docs but I couldn't find any information with detailed step by step procedure.

best regards.

**Comment by gnome-mpv** [comment]
In general, user scripts are automatically loaded once you add them to *Plugins*, but some of them may require you to press a key to actually do something. Many script authors put this information in the source code of the script, usually near the beginning of the file: [*equalizer*](https://gist.github.com/avih/41acff712abd32e1f436235388c8b523#file-equalizer-lua-L8-L11),  [*pitch control*](https://github.com/FichteFoll/mpv-scripts/blob/master/pitchcontrol.lua#L9-L16).
