### ISSUE TITLE
The full screen button does not appear

### ISSUE THREAD

**Issue by eltonfabricio10** [celluloid-player/celluloid#528]
Overview Description: **After displaying the full screen for the first time using the button and exiting with "ESC" the full screen button does not appear again.**

Steps to Reproduce:

> 1. Open video
> 2. Click the full screen button
> 3. Press the ESC button

Actual Results: The full screen button does not appear

Expected Results: The full screen button appears again

Version: 0.18

Additional Information: None

**Comment by gnome-mpv** [comment]
I can't reproduce this.

Can you post a [log file](https://github.com/celluloid-player/celluloid/blob/master/.github/CONTRIBUTING.md) and a video/image of this happening?

**Comment by eltonfabricio10** [comment]
[https://drive.google.com/file/d/1hNCb_DQXyY5VJPOOjNO0_v-mQ771WbJA/view?usp=sharing](The full screen button does not appear)
