### ISSUE TITLE
Segregate PAN and SCAN functions

### ISSUE THREAD

**Issue by akshayjauhari** [celluloid-player/celluloid#538]
Overview Description:
PAN and SCAN functionality must be on separated with each other like that of Media player classic with k-lite mega codec on windows

Steps to Reproduce:
1.  Make PAN on numpad 8 and 2 to increase/decrease it.
2. Make SCAN on numpad 6 and 4 to increase/decrease it.
3. This will help configure PAN and SCAN functions separately.

Actual Results: 
Currently both PAN and SCAN are linked to each other and with any increase it crops the sides of the videos.

Expected Results: 
Please segregate both the functions so the user can customize according to its taste.

Version: 0.19

Additional Information:
I always like the videos to just increase the PAN which are not covering my full screen space without cropping any side screen video.

**Comment by gnome-mpv** [comment]
This needs to be implemented in mpv: https://github.com/mpv-player/mpv/issues/6303

**Comment by gnome-mpv** [comment]
Implemented in mpv.
