### ISSUE TITLE
Black screen using Wayland - Sound is OK

### ISSUE THREAD

**Issue by didierga** [celluloid-player/celluloid#540]
Overview Description:
When I try to use celluloid using wayland I get a black screen but sound is OK

Steps to Reproduce:
1. Select Wayland for the session
2. Start Celluloid
3.

Actual Results:
I get a black screen but sound is OK.

I get following messages in terminal:

mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
Cannot load libcuda.so.1

Expected Results:
Images and sound as when using Xorg.

Version:
Fedora 32 Beta
kernel-5.6.5-300.fc32.x86_64
celluloid-0.19-1.fc32.x86_64
mpv-0.32.0-3.fc32.x86_64

Additional Information:
VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tonga XT / Amethyst XT [Radeon R9 380X / R9 M295X] (rev f1)

https://bugzilla.rpmfusion.org/show_bug.cgi?id=5610

**Comment by gnome-mpv** [comment]
Does it work if you use mpv directly?

**Comment by didierga** [comment]
It works if:
- I use mpv directly with Wayland or Xorg
- I use Celluloid with Xorg
Problem is only using Celluloid with Wayland

**Comment by didierga** [comment]
I did more tests using Wayland. 

When I start Celluloid I get:
- a windowed view with black screen
- sound is OK
- Minimize, Maximize and Close window's button are inactive

In this state:
- if I toggle to fullscreen I get images and if I toggle back to windowed view images and sound stay OK
- same thing if I switch application and switch back to Celluloid

**Comment by gnome-mpv** [comment]
I can't reproduce this with Vega 10 or RX 560X. On both GPUs, I get the same console output, but video plays normally.

**Comment by ewonchang** [comment]
I have the same issue since Gnome 3.36 update. Upon opening a video I got blank screen, after resizing I got image. I'm using Intel UHD 620 graphics.

**Comment by Mel34** [comment]
Having the same issue on gnome 3.36.2 in a wayland session with RX580. Distro is Arch. If I toggle fullscreen and then back it reproduces video in the window normally like @didierga stated. MPV reproduces video in window normally too (I'm running mpv from git master, FWIW)

**Comment by gnome-mpv** [comment]
@ewonchang Were you using Celluloid 0.19 before you updated to Gnome 3.36?

**Comment by didierga** [comment]
What I did using wayland:
- I downgraded from celluloid-0.19-2.fc32.x86_64.rpm to celluloid-0.18-2.fc32.x86_64.rpm
- Celluloid works fine, I get images when I start it
- I upgraded from celluloid-0.18-2.fc32.x86_64.rpm to celluloid-0.19-2.fc32.x86_64.rpm
- Celluloid works fine and I cannot recreate the problem !

**Comment by ewonchang** [comment]
> @ewonchang Were you using Celluloid 0.19 before you updated to Gnome 3.36?

I think so. I was on openSUSE Tumbleweed. Gnome 3.36.1 became available only early this week. I was using the latest Celluloid flatpak all the time. That means 3.34.5+0.19 for about 2 weeks.

**Comment by glaubersm** [comment]
I can reproduce with both 0.18 (from distro repos) and 0.19 (bulit source code) versions on Wayland session of Gnome 3.36.2 on Arch Linux if Celluloid window is maximized when playback starts.

open Celluloid on Wayland
maximize Celluloid window
open a video file via "+" button in the upper left corner

Result: audio plays without video, just a black screen.
Video starts to play if Celluloid window is restored/unmaximized.

My video adapter is intel hd 4000.

**Comment by gnome-mpv** [comment]
>open Celluloid on Wayland
>maximize Celluloid window
>open a video file via "+" button in the upper left corner

Thanks. I can reproduce the bug now.

**Comment by MaCroX95** [comment]
This bug is extremely annoying, and since it's been fixed in the git and still present in Flatpak version 4 months later, could it perhaps be backported or released as a new version of Celluloid?

**Comment by cdalexndr** [comment]
Encountered this bug on Celluloid 0.29, Gnome 49.
MPV shows video.
