### ISSUE TITLE
Cannot open file on a read only nfs share

### ISSUE THREAD

**Issue by mispp** [celluloid-player/celluloid#543]
Overview Description:
cannot open files on doubleclick on a read only nfs mount in Ubuntu 20.04, 19.10, Fedora 32

Steps to Reproduce:
1. mount nfs share readonly
2. open file by doublicking in nautilus

Actual Results:
Fails with error "Playback was terminated abnormally. Reason: loading failed."

Expected Results:
Opens file normally.

Version: 0.19, flatpak

Additional Information:
Flapak installed and updated.

**Comment by gnome-mpv** [comment]
Duplicate of #396
