### ISSUE TITLE
Feature request: libdav1d (ppa:xuzhen666/gnome-mpv) Ubuntu focal

### ISSUE THREAD

**Issue by rmkimathi** [celluloid-player/celluloid#544]
Overview Description:
Feature request: libdav1d (ppa:xuzhen666/gnome-mpv) Ubuntu focal. libdav1d seems to play much better.
Steps to Reproduce:
1.Open AV1 encoded video file
2.keyboard i
3.

Actual Results:
Video decoder: libaom-av1
Expected Results:
Video decoder: libdav1d
Version:
0.19
Additional Information:
Playing AV1 videos with mpv is very smooth with libdav1d. Ubuntu 20.04

**Comment by mc4man** [comment]
This is not a celluloid issue.
libdav1d support is thru ffmpeg, in the case of that ppa it uses the repo ffmpeg shared libs which don't have libdav1d support.
Celluloid will happily use libdav1d when using a libmpv1 that has such support. It does not need to be built against such libmpv.

**Comment by rmkimathi** [comment]
> This is not a celluloid issue, support is in libmpv via ffmpeg
> libdav1d support is thru ffmpeg, in the case of that ppa it uses the repo ffmpeg shared libs & libmpv1 which don't have libdav1d support.
> Celluloid will happily use libdav1d when using a libmpv1 that has such support. It does not need to be built against such libmpv.

Thanks! ... Will try build custom libmpv from https://github.com/mpv-player/mpv-build
