### ISSUE TITLE
[Feature Request] Shortcut to shuffle

### ISSUE THREAD

**Issue by Krafting** [celluloid-player/celluloid#547]
Overview Description: 
Add a keyboard to Shuffle the current playlist (Useful when you are using celluloid to listen to music without having to show the playlist then shuffle it)

Version: 0.19

**Comment by gnome-mpv** [comment]
You can already do this with an input config file. For example, putting `a playlist-shuffle` in your input config file will make Celluloid shuffle the playlist when you press the `a` key.

**Comment by Krafting** [comment]
Oh thank you! I didn't know that!
