### ISSUE TITLE
Speed increase/decrease value

### ISSUE THREAD

**Issue by RickAndTired** [celluloid-player/celluloid#549]
Is there a way to change the speed increase / decrease value?

I would like to reach 2.0 speed via hotkey. 
I can open Celluloid with --speed=2.0, but then I'm not able to reach 1.0 speed

Current values:
1.0 - 1.10 - 1.21 - 1.33 - 1.46 - 1.61 - 1.77 - 1.95 - 2.14

**Comment by gnome-mpv** [comment]
>Is there a way to change the speed increase / decrease value?

You can rebind the keys using an input config file. For example, putting these lines in the file will make the `[`/`]` key subtract/add the speed by 0.5 for each key press.

```
[ add speed -0.5
] add speed 0.5
```

>I would like to reach 2.0 speed via hotkey.
>I can open Celluloid with --speed=2.0, but then I'm not able to reach 1.0 speed

By default, pressing `{`/`}` will decrease/increase speed by a factor of 2. You should be able to reach 2.0 that way.

**Comment by RickAndTired** [comment]
Thank you!
