### ISSUE TITLE
[Feature Request] Cycle between video properties, playlist, and nothing

### ISSUE THREAD

**Issue by Hordeking** [celluloid-player/celluloid#550]
One thing I always liked about xplayer/Totem was that it could list the video properties such as framerate, resolution, a/vcodecs, etc.

However, annoyingly, one had to specifically select this in a menu to get from the playlist to this.

My request is for F9 to not just toggle the playlist off and on, but actually cycle through the off-state, playlist, and properties sheet.

An alternative might also simply have the properties be togglable, for instance using ctrl-F9. So it could appear either to the left or right of the playlist when the video is not in fullscreen.

**Comment by gnome-mpv** [comment]
Pressing `Shift+I` will toggle an overlay that contains some information about the video. Does it work for your use case?
