### ISSUE TITLE
Closing with keybinding doesn't save volume

### ISSUE THREAD

**Issue by D33M0N** [celluloid-player/celluloid#552]
I really really really don't want to manually drag the volume down to ~40%..60% every time I start the player. Could this be remembered like smplayer does? Please? :)

It's especially annoying when starting something with big bang music at nighttime... not cool.

**Comment by gnome-mpv** [comment]
This should already work; the volume is supposed to be remembered across sessions.

What version of Celluloid are you running? And how did you install it?

**Comment by D33M0N** [comment]
0.18-1 in Manjaro official repos.

**Comment by gnome-mpv** [comment]
Did you close Celluloid using a keybinding (`q` or `ctrl+c`) ? I noticed that sometimes the volume doesn't get saved if you do. Closing by clicking the close button works fine for me.

> While at the subject, also the "Remember last files location" option doesn't seem to have any effect (if this is supposed to remember where I left the video progress?), opening the same video I just watched to about 30%, opens it from the very beginning.

That option is for something different. It's for making the file chooser dialog remember the last folder you opened a file from.

**Comment by D33M0N** [comment]
I always close by pressing q.
