### ISSUE TITLE
[Feature Request] Reduce or increase subtitle font size

### ISSUE THREAD

**Issue by ngiampaoli** [celluloid-player/celluloid#553]
Overview Description:
Add an option to reduce or increase subtitle font size.
It could be an **A** (small)  **A** (bigger) icons on the control bar, it will be easy to use and also esthetically beautiful. 

Use:
When you click on **A** (small) the subtitle font size are reduced.
When you click on **A** (bigger) the subtitle font size are increased.

**Comment by gnome-mpv** [comment]
You can already do this by adding new keybindings using the input config file. For example:
```
F3 add sub-font-size -1
F4 add sub-font-size 1
```

The control bar is already a bit cluttered, so I would prefer to avoid adding more buttons if possible.

**Comment by ngiampaoli** [comment]
> You can already do this by adding new keybindings using the input config file. For example:
> 
> ```
> F3 add sub-font-size -1
> F4 add sub-font-size 1
> ```
> 
> The control bar is already a bit cluttered, so I would prefer to avoid adding more buttons if possible.

Thanks for de advice. 
Could you tell me the name of that file that I have to create and also the exact location to put that file?
Over .config/celluloid I have only 2 folders (scripts and watch_later) without any file.

**Comment by gnome-mpv** [comment]
You can create the file anywhere. You just need to load it under the `Config Files` tab in the preferences dialog.

**Comment by ngiampaoli** [comment]
> You can create the file anywhere. You just need to load it under the `Config Files` tab in the preferences dialog.

Thanks. It works great !!
Just one more question.
Is there any keybindings that I can use to download subtitle automatically for the movie?

**Comment by gnome-mpv** [comment]
> Is there any keybindings that I can use to download subtitle automatically for the movie?

You can do that with a script. There's a list [here](https://github.com/mpv-player/mpv/wiki/User-Scripts). Download one and install using the `Plugins` tab.

**Comment by ngiampaoli** [comment]
Thank you very much for all your help.

**Comment by shawonkibrea** [comment]
Sir,
How to set default subtitle font size in celluloid?
Plz...

**Comment by gnome-mpv** [comment]
>  How to permanently set default subtitle font size in celluloid?

Use `sub-font-size` in your mpv config file, e.g. `sub-font-size=55`. Alternatively, put the option in `Extra mpv options` (it's under the `Miscellaneous` tab in the preferences dialog), e.g. `--sub-font-size=55`.

**Comment by gnome-mpv** [comment]
> Do we have an option to "move up" a little bit the subtitle position, so that it's not partially covered by the controls when doing mouse over question?

Yes, you can use the `sub-pos` option. The default value is 100, which represents the original position. A value smaller than that shifts the subtitle up, and a value greater than that shifts it down. You can also use `R` and `Shift + R` to control this option.

> Or an even more generic question: how can we find all the available options (such as the ones mentioned above like sub-font and sub-font-size) question?

The [mpv manual](https://mpv.io/manual/stable/) has detailed information about all  available options.

**Comment by dxps** [comment]
OMG! :tada:  Now this looks perfect to me!

![image](https://user-images.githubusercontent.com/14140226/144884839-598d34fa-02f7-41d6-8e20-3464906a0ed6.png)

And those `Extra MPV Options` are `--osc=yes --script-opts=osc-layout=slimbox,osc-boxalpha=220,osc-seekbarstyle=knob --sub-font-size=28 --sub-font="Fira Sans"`
