### ISSUE TITLE
Dark theme on a KDE Plasma desktop

### ISSUE THREAD

**Issue by ChameleonScales** [celluloid-player/celluloid#555]
I'm on Manjaro KDE and when I enable the dark theme in both Plasma's settings and Celluloid's preferences, the colors stay bright.
Do I have to download a particular GTK theme?

Versions:
Plasma: 5.18.5
Celluloid : 0.18

**Comment by TingPing** [comment]
There are two ways to have a dark GTK application.

- Use a "dark" variant. This means the specific GTK theme provides two theme files basically. Your theme clearly does not.

- Use a theme that is just dark already.

**Comment by ChameleonScales** [comment]
Oh I didn't realize there was a separate setting in Plasma's Application style for GTK themes (the "Configure GNOME/GTK Application style" button). That solved it.
Thanks!
