### ISSUE TITLE
[Feature request] Please make the player remember video progress.

### ISSUE THREAD

**Issue by D33M0N** [celluloid-player/celluloid#556]
When I close the video I am watching halfway through, I would love, if it would continue showing the video where I left it the other day. Like just storing filename + time/frame_number where it left off and next time it opens it, it tries to resume.
Probably not everyone likes this, thus maybe make it toggle in preferences?

Also please make it remember the video progress, when closing with keybinding q and not just with mouse :-D

**Comment by gnome-mpv** [comment]
Exiting by pressing `shift+q` will do this. If you want the same behavior for `q` and clicking the close button, put `save-position-on-quit` in your config file.

**Comment by D33M0N** [comment]
You have mentioned this mythical "config file" around here few times. Yet, its location seems to be well hidden mystery. Can you point me into the right direction where I might find this thing?
~/.config/celluloid/ with 0 files in it.

**Comment by gnome-mpv** [comment]
You need to create the file yourself. You can put it anywhere you like. After creating the file, open the preferences dialog (press `ctrl+p` or use the ☰ menu), switch to the `Config Files` tab, then set the config file location (using the button next to `MPV configuration file`) and check the checkbox above it.

**Comment by D33M0N** [comment]
Thanks.

**Comment by imkane** [comment]
Why on earth isn't this a default setting in a default config file. I've never seen a modern video player that doesn't do this by default. No offense to the developers, but seriously, there's been MANY, MANY questions about this feature throughout the years. It's very intuitive that to enable it you have to (1) manually create a config file (2) add some weird text to it

**Comment by dgel** [comment]
I agree, I would find it more intuitive to have a config file at a standard location, and create it if it doesn't exist with some useful defaults, this option being one of them. Perhaps if this would cause the config to be in a weird location in flatpaks, instead of an option to specify the configuration location, the preferences could have an 'open config file' button
