### ISSUE TITLE
Extremely slow cache when playing from cifs shares

### ISSUE THREAD

**Issue by mmowchenko** [celluloid-player/celluloid#557]
Can we implement this bug fix found over on mpv:

Thread: https://github.com/mpv-player/mpv/issues/7408

Commit: https://github.com/mpv-player/mpv/commit/20eead18130fd460d8e9eff50ce14afd3646faab

**Comment by gnome-mpv** [comment]
There's nothing we need to do here. Once mpv makes a new release and your distro updates its package, the fix will take effect in Celluloid automatically.
