### ISSUE TITLE
Move file from playlist to trash bin

### ISSUE THREAD

**Issue by didierga** [celluloid-player/celluloid#558]
Overview Description:

Add on option to move file from playlist to trash bin

Additional Information:

I would like to have an enhancement to move file from playlist to trash bin.

 ie: Right click on file in playlist display a "Move to trash bin" choice

**Comment by gnome-mpv** [comment]
I'm not sure I should implement this. It seems like something that should be done using a file manager.

If you don't mind using a shortcut, you can add a new keybinding for this in the input config file:
```
DEL run gio trash "${path}"
```
This will move the current file to trash when you press the delete button.
