### ISSUE TITLE
Changing extension of a .m3u playlist file causes abnormal termination

### ISSUE THREAD

**Issue by Chronigan** [celluloid-player/celluloid#560]
Overview Description:
If you change the file extension, just the extension, not the MIME type of a playlist then try to open it with celluloid. you will get an abnormal termination

Steps to Reproduce:
1.rename .m3u file
2.right click in nautilus -> choose to open in celluloid
3.celluloid opens then terminates

Actual Results:
crash

Expected Results:
play playlist

Version:
0.18

Additional Information:
It would be nice if celluloid could use multiple playlist types. Most music players use m3u and so m3u files are defaulted to audio players. So having a playlist type that defaults to celluloid would make things easier.

**Comment by gnome-mpv** [comment]
> crash

Did it really crash or just failed to play the file (and showed you a popup saying that playback terminated) ?

> It would be nice if celluloid could use multiple playlist types. Most music players use m3u and so m3u files are defaulted to audio players. So having a playlist type that defaults to celluloid would make things easier.

PLS is also supported.

**Comment by Chronigan** [comment]
Showed a message that playback had been terminated and then the program
closed.

**Comment by gnome-mpv** [comment]
>Showed a message that playback had been terminated and then the program closed.

I can't reproduce this. I tried changing the extension of a `.m3u` file to `.foo` and opening it. The popup appears, but the program didn't close.

Would you be able to share the playlist file that triggered this? And what extension did you rename the file to?

**Comment by gnome-mpv** [comment]
Closing due to lack of response.
