### ISSUE TITLE
[Request] Save screenshots as *.png instead of *.jpeg

### ISSUE THREAD

**Issue by solitonmedic** [celluloid-player/celluloid#562]
Hi there, I really love Celluloid, it's really comfortable to use then VLC. 

Is it possible to implement a option to save screenshots as *.png instead of the usual *.jpeg?

Thanks in advance!

**Comment by gnome-mpv** [comment]
You can change the format using the mpv option `screenshot-format`. To change the format to PNG, put this in your mpv config file.

```
screenshot-format=png
```
