### ISSUE TITLE
Setting MPV options in Preferences dialog does not work anymore

### ISSUE THREAD

**Issue by holzbrenner** [celluloid-player/celluloid#563]
Overview Description:

With version 0.19, setting MPV options through menu / preferences dialog doesn't work anymore. Entering "--hwdec=vaapi" results in no hardware acceleration, entering --mpv-hwdec=vaapi results in an error message box  "Failed to apply one or more MPV options."

Steps to Reproduce:

1. Open Preferences / Miscellanous
2. Enter --hwdec=vaapi in "Extra MPV options" text box
3. Save options
4. Play video

Actual Results:
- MPV options are not used and there is no video hardware acceleration

Expected Results:
- MPV options are used and VA-API based hardware acceleration is enabled

Version: **0.19-1**
System: Arch Linux (kernel 5.6.15-arch1-1)

Edit: it seems that MPV options do not work at all. Even running celluloid from command line with `celluloid --mpv-hwdec=vaapi` does not enable hardware acceleration.

**Comment by gnome-mpv** [comment]
Does hardware decoding work if you use mpv to play the file?

**Comment by holzbrenner** [comment]
Yes, but I have to use this option for the acceleration to work, it's not auto-detected like in vlc. It also works with celluloid 1.18, if I enter --hwdec=vaapi here:
![image](https://user-images.githubusercontent.com/288556/83754587-79e5bf00-a66c-11ea-8a81-22e88e97ed1e.png) 
Version of the **mpv** is **0.32.0**

**Comment by gnome-mpv** [comment]
I just tested with v0.19 and it seems to work fine for me.

How are you determining if hwdec is working? In my test, I printed out the mpv property `hwdec-current`. The output should be `vaapi` for supported codecs and `no` otherwise.

**Comment by holzbrenner** [comment]
First of all - thank you for your involvement and quick replies. I got it working, see below, the issue seems to be ... something completely different :) 

> A more accurate way to check if hwdec is working would be to start Celluloid from command line like this: `celluloid --mpv-msg-level=all=v 720p-file.mkv`. If hwdec is being used, there will be something like this in the output: `[decode_wrapper/vd] Using hardware decoding (vaapi)`

**The problem seems to be in the order of the passed options** and it applies to both the GUI preferences text box and bash command line.

`celluloid --mpv-save-position-on-quit --mpv-hwdec=vaapi 720p-file.mkv`

Doesn't enable hardware acceleration and also doesn't save the position of the video:
```
** Message: 19:09:41.340: [vd] No hardware decoding requested.
** Message: 19:09:41.340: [vd] Using software decoding.
```
While passing hwdec _first_ enables vaapi and the video position is saved on exit.

`celluloid --mpv-hwdec=vaapi --mpv-save-position-on-quit 720p-file.mkv`
```
** Message: 19:38:51.802: [vd] Using hardware decoding (vaapi).
** Message: 19:38:51.802: [vd] Decoder format: 1280x720 vaapi[nv12] auto/auto/auto/auto/auto CL=mpeg2/4/h264
```
This seems to have change since version 0.18 where it also worked with the 'save position' option passed first (configured as in my 1st comment above).

**Comment by gnome-mpv** [comment]
This is actually a bug in the options parser.

**Comment by holzbrenner** [comment]
As the issue title suggests, I had a feeling from the beginning that the problem has something to do with options handling.
