### ISSUE TITLE
Add support for profiles

### ISSUE THREAD

**Issue by Digitalone1** [celluloid-player/celluloid#565]
mpv can be set to use different profiles in its configuration. To use a specific profile, you can launch mpv with `--profile="profile_name"` command line option.

Unfortunately this does not work for celluloid. It would be really useful if the same could be done with celluloid selecting a specific profile from command line while the app launched from UI will rely on default config.

**Comment by gnome-mpv** [comment]
To set an mpv option from the command line, you need to add `mpv-` prefix to the option name. So if you want to set the mpv option `--profile=PROFILENAME`, you will need to use `--mpv-profile=PROFILENAME` when launching Celluloid.

**Comment by Digitalone1** [comment]
Thanks @gnome-mpv, I didn't know that. Can you please add it to the `README.md` file?

So, if I specify `--mpv-profile`, will the profile settings override the ones specified in the config file set in Celluloid preferences?

And if I provide to Celluloid the same config file used by mpv with different profiles, will Celluloid ignore the profiles picking only the default ones?

**Comment by gnome-mpv** [comment]
> Thanks @gnome-mpv, I didn't know that. Can you please add it to the README.md file?

The info is already in the manpage, but I'll mention it in the README as well.

> So, if I specify --mpv-profile, will the profile settings override the ones specified in the config file set in Celluloid preferences?

It will. Options specified on the command line take priority over the ones in the config file.

> And if I provide to Celluloid the same config file used by mpv with different profiles, will Celluloid ignore the profiles picking only the default settings?

The behavior should be exactly the same as mpv, meaning that anything listed under a profile will have no effect unless the profile is enabled using `--profile` (or the input command `apply-profile`).

**Comment by Digitalone1** [comment]
Thank you.
