### ISSUE TITLE
Display chapters in progress bar

### ISSUE THREAD

**Issue by soredake** [celluloid-player/celluloid#578]
Overview Description:

Steps to Reproduce:
1. Open file with chapters.
2. No chapter marks is shown in progress bar.
3.

Actual Results:
No chapter marks is shown in progress bar.

Expected Results:
Show chapter marks like mpv does.
![Screenshot_20200801_103453](https://user-images.githubusercontent.com/5204968/89096971-6ee8aa00-d3e3-11ea-92a7-7f1242df5b2f.png)

Version: 0.19-1~focal1

Additional Information: kubuntu 20.04

**Comment by Crucizer** [comment]
+1

**Comment by moshiur-raj** [comment]
Recent version of mpv shows the chapter name in the osc. Maybe we can have something like that too?
For example, when the mouse hovers over the progress bar the chapter name is shown beside the timestamp?

**Comment by VarLad** [comment]
Haruna now shows it in the progress bar too. 
@gnome-mpv Any idea how easy/hard will it be to implement? Or will we consider it for UI Redesign?

**Comment by gnome-mpv** [comment]
> Any idea how easy/hard will it be to implement? Or will we consider it for UI Redesign?

It shouldn't be too difficult. We're currently using GtkScale to implement the seek bar, so `gtk_scale_add_mark()` can be used to add chapter marks. Doing that changes the shape of the slider though, so we need to override that behavior somehow.
