### ISSUE TITLE
Celluloid video playback has difficulties on pinephone where stalandalone mpv video player works fine

### ISSUE THREAD

**Issue by sirnewton01** [celluloid-player/celluloid#580]
Overview Description:
I'm trying to use Celluloid on a PinePhone with the Mobian (aka. Debian) OS with a modified GNOME environment. The standalone mpv player is working fairly well, but it lacks any reasonable on screen controls and doesn't disable the screensaver. Celluloid would be able to provide these benefits. However, videos that playback fine with standalone mpv don't work well at all with celluloid even with matching versions of mpv/libmpv.

Steps to Reproduce:
1. Launch mpv and force it into Open GL ES mode ```mpv --opengl-es=yes path_to_video_file```
2. Launch celluloid from the command-line in the same way as mpv with a local video file, but with the special GDK environment variable to force it into GLES mode. ```GDK_GL=gles celluloid path_to_video_file```

Actual Results:
Mpv video playback is smooth and has correct colours while celluloid playback jumps back and forth between previous frames and the current, plus skin tones appear blue along with other colour irregularities. See this youtube video capture of the celluloid output: https://www.youtube.com/watch?v=yDHhi9y4stY

Expected Results:
Celluloid using the same version of mpv and using the same Open GL back-end with the same GL ES should produce the same or similar results.

Version:
0.18-2 (from debian package version)

Additional Information:
I'm actually using Celluloid and Mpv comparison to try to isolate other GL problems I've been seeing on the pinephone. It seems like a great way to figure out if it's GDK/GTK that is causing problems somehow with the Open GL drivers and/or Mesa in this context.

**Comment by gnome-mpv** [comment]
Confirmed. Looks like the red and blue channels are swapped for some reason. Swapping the channels back again restores the correct color: `GDK_GL=gles celluloid --mpv-vf=colorchannelmixer=rr=0:rb=1:br=1:bb=0`

Playback doesn't jump back and forth for me though, but I don't have a PinePhone to test with.

**Comment by sirnewton01** [comment]
Thanks for the reply. I'm not sure if it's related but this is not the first time I see the color channels mixed up like this. If you try the gtk3-demo, which does both GLES and GL with it's OpenGL Area demo. The triangle shows up as yellow on GL and blue on GLES. It kinda makes me wonder if there's something up with gtk/gdk GLES support, but I am not knolwedgeable enough about OpenGL matters to make the call.

**Comment by gnome-mpv** [comment]
I did some more testing, and it looks like this might a be a bug in gtk. With gtk-demo from gtk 3.24.21, red and blue channels are swapped when using GLES, but this no longer happens with the latest git version of gtk. I can't find the commit that fixes it though.

>Btw, the --mpv-vf=color... option doesn't seem to work for me. Maybe my celluloid is not the latest.

For < 0.19, you can use `--mpv-options` instead: `GDK_GL=gles celluloid --mpv-options='--vf=colorchannelmixer=rr=0:rb=1:br=1:bb=0'`

**Comment by sirnewton01** [comment]
Thanks for digging deeper into this. When you say the latest version fro git, do you mean in the 3.x branch or are you referring to 4.x?

**Comment by sirnewton01** [comment]
I dug back in the gtk 3.24 history from the 3.24.21 tag up until today. I don't see any commits that seem to address the GLES colour space issue here. The closest I saw was some work done to support GLES on Windows/ARM, but I didn't see any of that touching common GLES pieces for Linux.

There must be some dependency of GTK that gets bumped and fixes the problem somehow, maybe?

**Comment by sirnewton01** [comment]
I also raised this gtk issue to see if anyone over there might have some idea of what's the cause and maybe the solution that was merged. https://gitlab.gnome.org/GNOME/gtk/-/issues/3032

Thanks again @gnome-mpv hopefully this might get us a step closer to getting this working on the pinephone.

**Comment by gnome-mpv** [comment]
> Thanks for digging deeper into this. When you say the latest version from git, do you mean in the 3.x branch or are you referring to 4.x?

I'm referring to the 4.x branch.

**Comment by sirnewton01** [comment]
Two of the GTK devs seem to think that this commit is what fixed the problem in 4.x. But, it seems that it was back-ported two years ago to 3.x and it seems to apply only to Windows, not Linux. https://gitlab.gnome.org/GNOME/gtk/-/commit/cf0175ffcec21ebc7b74c1fc44e74437e30af840

**Comment by sirnewton01** [comment]
There's also this branch that might have some more clues about GLES on Linux, but X11 though, not Wayland. https://gitlab.gnome.org/GNOME/gtk/-/commits/wip/ebassi/gdk-egl-x11/

**Comment by baconicsynergy** [comment]
I too am encountering this error on my PinePhone running postmarketOS.

For me, Celluloid also freezes when I click the "+" button and select "Open..." to try to select a video to play.

I receive this error message from stderr: (io.github.celluloid_player.Celluloid:3966): Gtk-WARNING **: 18:32:47:980: GtkOverlay does not have a child property called shrink

**Comment by j0lol** [comment]
not-smooth playback is happening for me as well, i also cannot select any menu options that appear (but thats an unrelated issue) 
im running manjaro kde edition on pinephone

**Comment by gnome-mpv** [comment]
We're using GTK4 now (02c1e86dae64c5049915753a24aed91fde994e0a) so the bug no longer affects us.
