### ISSUE TITLE
Celluloid freezes when selecting "Open..." option in top left menu, on PinePhone running postmarketOS

### ISSUE THREAD

**Issue by baconicsynergy** [celluloid-player/celluloid#585]
Overview Description:
When attempting to open a new video from the top left menu, Celluloid freezes. Running postmarketOS on the PinePhone.

stderr shows the following error message: (io.github.celluloid_player.Celluloid:3966): Gtk-WARNING **: 18:32:47:980: GtkOverlay does not have a child property called shrink

Steps to Reproduce:
1. Run postmarketOS on PinePhone
2. Open Celluloid
3. Attempt to open video file for playback via top left menu (+)

Actual Results: Celluloid freezes and must be terminated with kill command

Expected Results:Video playback

Version: 0.19-r0 aarch64

Additional Information: stderr shows the following error message: (io.github.celluloid_player.Celluloid:3966): Gtk-WARNING **: 18:32:47:980: GtkOverlay does not have a child property called shrink

**Comment by gnome-mpv** [comment]
When this happens, are you able to open up the app switcher? If so, do you see a file chooser dialog in there?

**Comment by baconicsynergy** [comment]
I should have stated that I am using Phosh version 0.4.3-41. When I go to the app switcher overview, a file chooser dialogue is not visible.

Please forgive my late response, I am pretty busy as of late

**Comment by gnome-mpv** [comment]
I can't reproduce this with Celluloid 0.22 and Phosh 0.15.0, so it's  probably fine now. Feel free to reopen if it's still a problem for you.
