### ISSUE TITLE
Support for panel

### ISSUE THREAD

**Issue by shosek** [celluloid-player/celluloid#590]
Overview Description:
It is not bug, but just an idea. What about support for panel (gnome, xfce), probably in notifiction area, with some control items, and possibility to hide player as classical window app?

Actual Results:
No support.

Expected Results:
Icon on panel (gnome, xfce), or notification area, with some control items (maybe possibility to choose which items), and possibility to choose hide player as classic app in window.

Version:

Additional Information:

**Comment by gnome-mpv** [comment]
>What about support for panel (gnome, xfce), probably in notifiction area, with some control items

Celluloid already supports MPRIS, so you should be able to get this by installing an MPRIS plugin for your DE (e.g. [XFCE](https://github.com/matiasdelellis/xfce4-soundmenu-plugin), [GNOME](https://extensions.gnome.org/extension/1379/mpris-indicator-button/)).

>and possibility to hide player as classical window app?

Are you referring to the ability to start Celluloid without showing a GUI? If so, there's already [an issue for that](#491).
