### ISSUE TITLE
Many dropped frames in a video compared to when playing video directly in MPV

### ISSUE THREAD

**Issue by zethexx** [celluloid-player/celluloid#592]
Overview Description: The best example I had: I played a large video file (+25GB) over the network (sshfs), and during a specific part, many frames are dropped (after about a minute, 700+ dropped frames in (output) section). This does NOT happen when playing the video in MPV (running `mpv /path/to/video/file), instead only a few or none frames dropped.

This happens in other videos too, although to a lesser degree. Celluloid occasionally drops a few frames here and there, while direct MPV doesn't. The example above had the best example and was the final straw that made my write this issue.

Steps to Reproduce:
1. Play a video in celluloid
2. Notice the dropped frames (or press shift+I)
3. Play the same video in MPV directly
4. Notice the smooth playback, or at least way less dropped frames (my computer is not the fastest, and in normal, non-benchmarked usage it's doing some things in the background which could cause a hiccup, but for the final testing to write this issue I made sure nothing else was running).

Actual Results: The video drops more (sometimes WAAY more) frames than directly playing in MPV does.

Expected Results: The video plays as smoothly (or at least almost as smoothly) as it does in direct MPV.

Version: 0.19 (0.19-1 in arch linux repos). Also tried in git master d1e923a5ae0c2d3307be48ea2e5981fe3c90ac48 (latest commit in the time this is posted), also had same result (0.16.r29.g3fca44d-1in arch linux aur repos).

Additional Information: Both direct MPV and celluloid are reading the same config and input file (enabled in preferences and selected my files). One thing to note is that direct MPV shows "frame timings: (last/average/peak microsec)" in the shift+I display, while celluloid doesn't. not sure why. I am running on sway with wayland. MPV config is default, except for profile=gpu-hq.

The fact that its playing on a network drive and being large shouldn't invalidate this issue IMO because direct MPV handles it fine (I have tried going back and forth playing celluloid and direct MPV and get same results). 

The video with the best example is HEVC with flac audio in an mkv container. I am using intel graphics. Tried with and without forcing hw acceleration, and switched hw acceleration on and off during the vids. nothing changed.

I also tried messing with the preferences in the 'interface' section, nothing fixed it.

**Comment by gnome-mpv** [comment]
Video playback on Wayland is a bit inefficient (#494), so it's possible that playing a file that requires a lot of processing power to decode will cause frame drops. You should be able to get similar performance to mpv by running Celluloid on X11 (or XWayland).

To make Celluloid use XWayland, set the env var `GDK_BACKEND=x11` and choose a VO that that can be embedded (e.g. `vo=x11`) in your mpv.conf. `vo=gpu` also works, but you also need to set `--gpu-context=x11`.

**Comment by zethexx** [comment]
This seems to be the case. I did not expect it to be a GTK for Wayland issue, no wonder I couldn't find any results online! Using celluloid under X11/Xwayland helps, except the video is laggy when the top/bottom bar is in view, and I also had an issue where clicking in the scrollbar goes to a different time than what it says in the pop up box (around 5mins off, depending on how long the video is), probably another GTK issue. (although this is unrelated to the current issue)

I'm going to switch to using command-line MPV under Wayland for now, cause I don't want to use Celluloid under X11 and because of the other issue I had, and also for performance/cpu usage. But using celluloid under X11 does solve this issue, even if its not the most ideal solution. I'm hoping that these issues can be solved in the future, though that gitlab issue doesn't seem to be very active.

**Comment by Froggy232** [comment]
Hi,
Is there any news on this issue, or at least hope it will be solved?
I'd like to use celluloid instead of MPV but because of this problem, I must rely on mpv.
I will switch as soon as it's solved, and I think a lot of other people too.
Thanks you a lot for your work!

**Comment by gnome-mpv** [comment]
>  Is there any news on this issue, or at least hope it will be solved?

Not really. Something I want to try is to implement a Wayland subcompositor in Celluloid and see if we can embed mpv's window that way. That should be more efficient, but I'm not going to have time to work on it any time soon. Patches are welcome though.

**Comment by Froggy232** [comment]
Thanks, I understand.
I deeply hope it will end up being solved, celluloid is a wonderfull GUI for MPV.
Thanks for your work!

**Comment by Froggy232** [comment]
Hi,
I'm not competent enough to really understand it, but won't this new feature of GTK could help celluloid?
https://blog.gtk.org/2023/11/15/introducing-graphics-offload/
If I understand correctly, it would be possible to display the video output at a very low cost on performance?
Sorry if it's not relevant, I would also understand if it's too much work to implement.
Thanks you!

**Comment by gnome-mpv** [comment]
I haven't looked deeply into this, but it sounds like you have to build GdkTextures from dmabufs for this to work, so I don't think this will be useful for us.

**Comment by Froggy232** [comment]
Ah, sorry for that.
Thanks for your work!
