### ISSUE TITLE
strange behaviour when I click the progress bar?

### ISSUE THREAD

**Issue by AhmedHalim96** [celluloid-player/celluloid#595]
Overview Description:
So when I click a certain point on the progress bar it seeks 10 seconds forward or backwards instead of jumping to that point
is that the default behaviour or can  that be changed?
Version: 0.20

**Comment by gnome-mpv** [comment]
I'm not aware of any location on the progress bar you can click to make it seek forward/backward. Can you post a screencap showing this happening?

**Comment by AhmedHalim96** [comment]
there you go: 
https://imgur.com/a/ja0jTqa
clicking while holding shift does what I want but this is unconventional

**Comment by gnome-mpv** [comment]
On my machine, I have to hold shift or right click to get the behavior in the video. It jumps immediately to the clicked location if I just left click.

What WM/DE are you using?

**Comment by AhmedHalim96** [comment]
I'm using Linux Mint Cinnamon

**Comment by gnome-mpv** [comment]
In `~/.config/gtk-3.0/settings.ini`, do you have a line that looks like this: `gtk-primary-button-warps-slider=0`? If so, removing the line should restore the normal behavior.

**Comment by AhmedHalim96** [comment]
@gnome-mpv  thank you, that solved the problem!

**Comment by emanuelserpa** [comment]
Had this problem and it's sad that took some months to found this thing. Celluloid is pratically unusable with this gtk setting.

**Comment by regulator-g** [comment]
For anyone on KDE, the settings.ini file gets overridden every restart.

System Settings->Workspace->Clicking in scrollbar track

**Comment by HubKing** [comment]
Well, I thought it was a bug, but what do you know, it seems like it is a default behaviour of GTK. Am I the only one who thinks that this is stupid? Why would a person expect that clicking a position on a seek bar does not jump to that clicked position but just jump 10 seconds?

In my `~/.config/gtk-4.0/settings.ini` (yeah, not gtk-3.0), the default was `gtk-primary-button-warps-slider=false`. According to the documentation, this makes it jump 10 seconds. Setting it to `true` make it jump to the clicked position. Also, clicking with shift do the opposite action.

**Comment by kdato** [comment]
Ah, it's a Shift+Click! Thanks for the tip.

**Comment by ironhak** [comment]
Please make it default behaviour...
