### ISSUE TITLE
Add option to hide title bar

### ISSUE THREAD

**Issue by PtrckDns** [celluloid-player/celluloid#597]
Just a quick toggle feature to hide the title bar

**Comment by gnome-mpv** [comment]
With c1d2f7ab434d0c9cfbf281d28f647a6998d85e2a, you can hide the title bar by creating an mpv keybinding to change the value of the mpv property `border`, e.g. `a cycle border`.

**Comment by PtrckDns** [comment]
> With [c1d2f7a](https://github.com/celluloid-player/celluloid/commit/c1d2f7ab434d0c9cfbf281d28f647a6998d85e2a), you can hide the title bar by creating an mpv keybinding to change the value of the mpv property `border`, e.g. `a cycle border`.

How to do that exactly? Sorry, linux newbie here.

**Comment by gnome-mpv** [comment]
> How to do that exactly? Sorry, linux newbie here.

Supposing you want the `a` key to toggle the title bar:
1. Create a file, and put "a cycle border" in the file. The file uses the same syntax as mpv's `input.conf`. The Command Interface section in the [mpv manual](https://mpv.io/manual/stable/) has more details.
2. Open the preferences dialog (Ctrl + P).
3. Click the `Config Files` tab.
4. Check `Load mpv input configuration file`.
5. Choose your file using the button below the checkbox.
6. Press `Save`.
