### ISSUE TITLE
Enhancement request: Enqueuing to the current playlist

### ISSUE THREAD

**Issue by FBachofner** [celluloid-player/celluloid#601]
Overview Description:

Enqueuing to the playlist from a file manager is not possible without drag and drop.  Even then it is _only_ possible if dragged specifically to the playlist panel.

Steps to Reproduce:
1. Launch a file in Celluloid (for example, double click a video file in "Nemo" the LinuxMint file manager)
2. Attempt to enqueue a **_second_** file in Celluloid (for example, double click another video file in "Nemo" )

Actual Results:
1. The second file will immediately **_replace_** the first (playing) file.  Always.
2. There is no way to use a keyboard modifier (such as pressing the shift key).
3. There is no preference setting which can be set to allow additional files to be automatically enqueued (i.e. to amend the program's default way)

DESIRED Results:
1. MPV standard allows for a file to be shift-dragged _anywhere_ into the video window and it is enqueued.  According to the MPV issue tracker that feature was added 5 years ago (at _least_ partially?).  See: https://github.com/mpv-player/mpv/issues/2166#issuecomment-136139524
2. Double-clicking a file (with shift modifier) should enqueue it to currently playing file/s. (conceptually similar to the above standard)
3. Right-clicking a file and selecting "open with" should allow enqueuing from the context menu
4. A preference setting should be added to allow any clicked file to be added to the playlist (instead of replacing the current media)

Version:
0.19

Additional Information:
Sorry if this is not the best place to request features.  Please direct me to the proper place if there is a superior way.

Thank you for your consideration.

**Comment by gnome-mpv** [comment]
> 1. MPV standard allows for a file to be shift-dragged anywhere into the video window and it is enqueued. According to the MPV issue tracker that feature was added 5 years ago (at least partially?). See: mpv-player/mpv#2166 (comment)

Implemented in 6e8ea0850caf6eeb8720882937d653477ea4e622.

>2. Double-clicking a file (with shift modifier) should enqueue it to currently playing file/s. (conceptually similar to the above standard)
>3. Right-clicking a file and selecting "open with" should allow enqueuing from the context menu

These need to be implemented by the file manager. 026f95dfe96c9d4475d506f1ccaa37dc90ebfc2b added a new action for adding items to the playlist, so a file manager can potentially use this to display a context menu item.

> 4. A preference setting should be added to allow any clicked file to be added to the playlist (instead of replacing the current media)

WIP

**Comment by FBachofner** [comment]
Hi @gnome-mpv

**_WOW!_**  I am super impressed and thankful for your responsiveness to this request.

Mimicking MPV drag and drop functionality is smart (as many people might/would expect that on a program based on it).

I have a suspicion that the Mint team will quickly implement the necessary changes in the file manager to take advantage of your new program action.  They seem very interested in not having people use snaps (or flatpacks?); meanwhile VLC is pushing hard in that direction which is (I suspect) the reason that Celluloid is a first-class (the default!) media player in Mint.

I have also thanked you more publicly on the LinuxMint forums:
https://forums.linuxmint.com/viewtopic.php?p=1924757#p1924757

At the top of the thread you would see (between the lines) how I ultimately came here.

Thanks again!  :-)
