### ISSUE TITLE
Cannot run Celluloid after using wrong flag

### ISSUE THREAD

**Issue by prog-amateur2** [celluloid-player/celluloid#603]
**Overview Description:**
Hello, I cannot run celluloid any more as normal user since I have used a wrong flag. 
I can open it as root only. 

**Steps to Reproduce:**
1. Go to Setup
2. Use wrong option flag
3. Enjoy bug

**Actual Results:**
Clicking on celluloid do not open the window (so no video/audio). Also from terminal error message is something like `(--null)`. 

**Expected Results:**
Wrong option flag shall not be remembered so the program still can be open to correct the flag

**Version:**
celluloid-0.19-4.fc33.x86_64.rpm for Fedora 33

**Additional information:**
removing `~/.config/celluloid` folder after uninstall does not help. If I re-install Celluloid, I still have the same issue. 

Thank you for your kind help.

**Comment by gnome-mpv** [comment]
> Clicking on celluloid do not open the window (so no video/audio).

Usually, you should just get an error dialog saying that an option could not be applied. Can you try running Celluloid again with [logging enabled](https://github.com/celluloid-player/celluloid/blob/master/.github/CONTRIBUTING.md) and post it here? If it crashes, post the backtrace too.

> removing ~/.config/celluloid folder after uninstall does not help. If I re-install Celluloid, I still have the same issue.

Settings are stored using [dconf](https://wiki.gnome.org/Projects/dconf). You need a tool like [dconf-editor](https://wiki.gnome.org/Apps/DconfEditor) to access them. Celluloid's settings are under `/io/github/celluloid-player/celluloid/`.

**Comment by prog-amateur2** [comment]
> Can you try running Celluloid again with [logging enabled](https://github.com/celluloid-player/celluloid/blob/master/.github/CONTRIBUTING.md) and post the log here? If it crashes, post the backtrace too.
> 

Thank you vvery much for your quick reply. When I launch the log command, there is this following loop : 
```
** (io.github.celluloid_player.Celluloid:15774): DEBUG: 01:21:08.515: Applying option: --=(null)

** (io.github.celluloid_player.Celluloid:15774): WARNING **: 01:21:08.515: Failed to apply option: --=(null)
```

Backtrace gives the same loop, what do you think ? Thank you !

**Comment by gnome-mpv** [comment]
Can you post the full log (from the start to the place where it starts looping) ? I tried reproducing the bug by putting `--` in `Extra mpv options`, but the error message only appears once.

**Comment by prog-amateur2** [comment]
Hello thank you for your help. Unfortunately, it is not possible to post full log from terminal because I have to perform the following : 
1. run the command
2. quickly kill celluloid to stop the loop
3. check terminal logs -> this is where I can't post the beginning because the loop is so quick that I can't recover the beginning of the log (not enough space in the terminal window). 

Is there any log file location ? Then maybe I could post the result ? Thank you again

**Comment by gnome-mpv** [comment]
You can redirect the output to a file like this:
`G_MESSAGES_DEBUG=all celluloid &> celluloid.log`
