### ISSUE TITLE
Focus / bring the window to front when opening a new video file to play in an existing window

### ISSUE THREAD

**Issue by nekohayo** [celluloid-player/celluloid#607]
When Celluloid is already running, and I open an audio file from another app (like Evolution or Nautilus), Celluloid simply starts playing it in the background, which is the expected behavior.

However, when launching a video file (with visuals), if Celluloid is already running, it starts playback in the background instead of bringing it to the foreground, which not only requires me to do an extra action to switch to Celluloid to see the visuals, but is also confusing for non-tech-savvy users I've watched who were wondering why they were hearing sound but not seeing the video.

So I would suggest that, in the case of video files, it should ensure the app is focused and brought to the front. I have tested only on the GNOME Xorg session, but I presume it's the same under Wayland.

**Comment by Arnaudv6** [comment]
Same here, other-wise great software: thanks :+1:

**Comment by Arnaudv6** [comment]
Great, thanks for super fast support.
I'll grab this when holidays are over.
