### ISSUE TITLE
Celluloid doesn't pick sub-auto config option

### ISSUE THREAD

**Issue by RememberTheAir** [celluloid-player/celluloid#608]
**Overview Description:**

Celluloid seems to properly load my config file and set the preferences described there, but fails to respect  the `sub-auto` option (while bare mpv behaves as expected)

**Steps to Reproduce:**
1. create an mpv config file: `~/.config/mpv/mpv.conf`
2. set celluloid to load that config file from the "Config files" settings
3. edit the config file to "fuzzy-load" subtitles: `sub-auto=fuzzy` or `sub-auto=all` ([docs](https://mpv.io/manual/master/#options-sub-auto))
4. open a video file in a directory where there's also some suitable .srt file to load

**Actual Results:**
Celluloid doesn't load the srt file it is supposed to load. Apparently the other options in the config file are picked up (eg. I tried with `start=+56` and in fact the video is played starting from second 56)

**Expected Results:**
Celluloid loads srt files that contain the video file name as described in mpv docs ("fuzzy load"). Running `mpv video.mkv` _does_ load the subtitles as expected. I reproduced the issue and recorded it in [this video](https://files.catbox.moe/ghe4ww.webm)

**Version:**

- Celluloid 0.20
- mpv 0.33.0
- Pop!OS 20.04, Gnome 3.36.3

**Additional Information:**

See video linked above

**Comment by gnome-mpv** [comment]
Are you using the Flatpak version?

**Comment by RememberTheAir** [comment]
@gnome-mpv yes:

```bash
$~ flatpak info io.github.celluloid_player.Celluloid

Celluloid - GTK+ frontend for mpv

          ID: io.github.celluloid_player.Celluloid
         Ref: app/io.github.celluloid_player.Celluloid/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.20
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 25.6 MB
     Runtime: org.gnome.Platform/x86_64/3.38
         Sdk: org.gnome.Sdk/x86_64/3.38

      Commit: 8673f70a9b732a608eac1e611c94436c37e7e484295c8882327946aa12a1ab07
      Parent: 98464e1415872b0865c662da591b48d4eaf1476d3ab85ed69b834a99caa4744a
     Subject: fix flags (1e3cd16c)
        Date: 2020-11-22 21:55:22 +0000
```

**Comment by gnome-mpv** [comment]
Due to Flatpak's sandboxing, Celluloid has no access to the filesystem. It can only access the file you explicitly open.

To use subtitle autoloading with Flatpak, you have to allow filesystem access: `flatpak override --user --filesystem=host io.github.celluloid_player.Celluloid`

**Comment by RememberTheAir** [comment]
@gnome-mpv thanks a lot, that indeed fixes my issue!
