### ISSUE TITLE
Feature Request: Button to close the application from fullscreen mode

### ISSUE THREAD

**Issue by Nebelkind** [celluloid-player/celluloid#614]
Since since moving the mouse in full screen mode already gives access to all other functions of the application, I would like to request adding the one button every user will need to use: the close button.
 It is pretty inconvenient first having to switch to window-mode and then closing the window afterwards especially when the top bar is dislayed with all other functionalities in fullscreen-mode.
If placement mirroring the system setting for window controls is possible that would be awesome, otherwise I would suggest the right corner of the top bar for placement.

**Comment by leventerevesz** [comment]
This is a good suggestion. Until it is implemented, you can press `Q` to quit.
