### ISSUE TITLE
Pause at clicking on video

### ISSUE THREAD

**Issue by tavoda** [celluloid-player/celluloid#618]
It's common behavior in video playback SW that clicking on video will stop it and second click will again start to play it.

**Comment by gnome-mpv** [comment]
It's a common for web-based video players, but I'm not sure it's common for desktop players.

In any case, it's easy to get that behavior using an input config file:

```
MOUSE_BTN0 cycle pause
```

**Comment by tavoda** [comment]
Great! Thank you very much.
