### ISSUE TITLE
deadzonesize=1.0 osc option

### ISSUE THREAD

**Issue by SoiledBrush** [celluloid-player/celluloid#620]
Hi, i need that option so that gui shows up only when i hover it with mouse. Is there any way to make celluloid use osc.conf?

**Comment by gnome-mpv** [comment]
There's the GSettings key `/io/github/celluloid-player/celluloid/controls-dead-zone-size` (you can access it with `dconf-editor`), but right now the behavior is inconsistent with mpv. Currently, the deadzone covers the entire video, so with 1.0, the controls won't be shown at all. Instead, you need to set it to something like 0.9 to get the behavior you want. I'll fix this in the future.

Another thing you can do is to disable Celluloid controls and use mpv's OSC instead. You can do this by setting the options `osc` and `script-opts=osc-deadzonesize=1` in your config file. You can then press `Ctrl+H` to hide Celluloid's controls.

**Comment by SoiledBrush** [comment]
Thanks, that`s what i needed.

**Comment by SoiledBrush** [comment]
Sorry, about the second option. Celluloid controls can`t be hidden in the fullscreen mode.
