### ISSUE TITLE
Add Basque language to Celluloid's page on Zanata

### ISSUE THREAD

**Issue by aldatsa** [celluloid-player/celluloid#623]
Overview Description: I want to translate Celluloid to Basque (eu).

Steps to Reproduce:
1. Go to Celluloid's page on Zanata.

Actual Results: Basque (eu) language is not available for translations.

Expected Results: Could you please add it?

Version:

Additional Information:

**Comment by gnome-mpv** [comment]
Basque (eu) has been added on Zanata. Let me know if you have any questions.

Thanks!
