### ISSUE TITLE
How to make celluloid exit after finishing playing?

### ISSUE THREAD

**Issue by inoton** [celluloid-player/celluloid#624]
Overview Description:
How to exit celluloid automatically after playback. 
mpv.conf  keep-open=no,  not work for celluloid.
if someone know, PLS tell me, thanks!

Version:
$ celluloid --version
Celluloid 0.20

Additional Information:
OS Name: Fedora 33 64-bit
GNOME Version 3.38.2
Windows System Wayland

**Comment by gnome-mpv** [comment]
You can do this with a Lua script:

```
function handle_end_file(event)
        if event.reason == "eof"
        then
                mp.command("script-message celluloid-action win.quit")
        end
end

mp.register_event("end-file", handle_end_file)
```

**Comment by inoton** [comment]
> You can do this with a Lua script:
> 
> ```
> function handle_end_file(event)
>         if event.reason == "eof"
>         then
>                 mp.command("script-message celluloid-action win.quit")
>         end
> end
> 
> mp.register_event("end-file", handle_end_file)
> ```

It works, thank you soooo much!
have a good day.

**Comment by Xavier13pan** [comment]
Hi, how do i add the Lua Script to my Celluloid.

**Comment by gnome-mpv** [comment]
> Hi, how do i add the Lua Script to my Celluloid.

Copy & paste the script into a file, open the `Preferences` dialog (press `Ctrl + ,`)
, switch to the `Plugins` tab, then click the `+` button on the bottom and select the file.
