### ISSUE TITLE
Closing a new instance would close the first one

### ISSUE THREAD

**Issue by atnapes** [celluloid-player/celluloid#625]
Steps to Reproduce:
1. Open one video
2. Open another video on a new instance
3. Close the new instance

Actual Results:
First instance also gets closed

Expected Results:
First instance continue playing video

Version:
0.20

Additional Information:
Running on
Linux 5.9.14-arch1-1 x86_64

**Comment by gnome-mpv** [comment]
I can't reproduce this.

>2. Open another video on a new instance

How did you open the new instance?

**Comment by atnapes** [comment]
To open a new instance you either Ctrl+Click on the icon or enable it via:
Preferences > Miscellaneous > Always open new window

These are some logs that I think it is associated to the issue:
Jan 19 22:05:04 hpc098 io.github.celluloid_player.Celluloid[54785]: X Error of failed request:  GLXBadWindow
Jan 19 22:05:04 hpc098 io.github.celluloid_player.Celluloid[54785]:   Major opcode of failed request:  152 (GLX)
Jan 19 22:05:04 hpc098 io.github.celluloid_player.Celluloid[54785]:   Minor opcode of failed request:  32 (X_GLXDestroyWindow)
Jan 19 22:05:04 hpc098 io.github.celluloid_player.Celluloid[54785]:   Serial number of failed request:  76862
Jan 19 22:05:04 hpc098 io.github.celluloid_player.Celluloid[54785]:   Current serial number in output stream:  76867
