### ISSUE TITLE
Try "hwdec=vaapi –vo=gpu" with Mint 20.1 (Ryzen 3200G)

### ISSUE THREAD

**Issue by a9801259** [celluloid-player/celluloid#626]
Overview Description:
After Mint 20.1 upgrade, videos will stutter & jump a bit with Ryzen 3200G.
From Preferences: Miscellaneous: it is possible to give extra MPV options.
Try "hwdec=vaapi –vo=gpu" to crash your player and make your Celluloid unable to start again (even after remove&purge).
This happened in Linux Mint 20.1 by user mistake.

Steps to Reproduce:
1. Add this line to Extra MPV options "hwdec=vaapi –vo=gpu" (at least if you have Ryzen 3200G in use).
2. Try to remove Celluloid, because it won't start after that command (remove and purge; delete folders).
3. Try to install it again (it wont start).

Actual Results:
Crash and remove&purge not working which leads to a situation where user can't install it again (with basic commands).

Expected Results:
Should give some kind of error if it can't start, and/or return the basic value (hwdec=yes) if it crashes?
Or should have some kind of configuration file, where user could correct their mistakes in that Extra MPV options line.

Version:
0.20 (Linux Mint 20.1)

Additional Information:
User error to use wrong kind of Extra MPV option which lead to a situation where Celluloid seems impossible to remove completely and install again after the crash. Even I install it again, it won't start.

**Comment by gnome-mpv** [comment]
You can remove the mpv options with this command: `gsettings reset io.github.celluloid-player.Celluloid mpv-options`

> Should give some kind of error if it can't start, and/or return the basic value (hwdec=yes) if it crashes?

I think this is a good idea. We should probably offer to start in some kind safe mode if a crash is detected.

**Comment by a9801259** [comment]
Hello sir, and thank you. That worked perfectly!
