### ISSUE TITLE
question: Is there a way i can have waveform visualization?

### ISSUE THREAD

**Issue by inet56** [celluloid-player/celluloid#629]
or other types of audio visualization?

**Comment by gnome-mpv** [comment]
You can use this Lua plugin: https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua

**Comment by inet56** [comment]
how can i use it?

**Comment by gnome-mpv** [comment]
>how can i use it?
>I have loaded the plugin via preference/plugin.

It should automatically show a visualization when you play an audio file. You can also press `c` to change the type of visualization.
