### ISSUE TITLE
Doesn't open through xdg-open

### ISSUE THREAD

**Issue by rharish101** [celluloid-player/celluloid#630]
Overview Description:
Celluloid is registered as the default video player (as seen through the mimetype associations), and it open when double-clicking in the file manager (Thunar). However, when a video file is opened in the terminal using `xdg-open test.mp4`, it doesn't open a window; it just starts a process with the command `/usr/bin/celluloid --gapplication-service`, which terminates by itself after a few seconds (with nothing printed to the console). Opening a video using `celluloid test.mp4` works perfectly.

Steps to Reproduce:
1. Set Celluloid as the default application for a video (here an MP4 video is used): `xdg-mime default io.github.celluloid_player.Celluloid.desktop video/mp4`.
2. Open it through the CLI: `xdg-open test.mp4`. Observe that no window opens.
3. Immediately, check the command used for Celluloid in the process table: `pgrep -fa celluloid`.
4. Now open it using: `celluloid test.mp4`. Observe that this time a window opens and the video plays.

Actual Results:
Celluloid doesn't open any window, and terminates soon.

Expected Results:
Celluloid should open the video in a window.

Version:
0.20

Additional Information:
- OS: Arch Linux

**Comment by TingPing** [comment]
`xdg-open` is a mess of a tool that can do one of a dozen things depending on your environment.

Does `gio open test.mp4` work? That tool actually implements the XDG spec correctly.

**Comment by rharish101** [comment]
Thanks, that worked! I wasn't aware of `gio` before this; I've been using `xdg-open` all this time.

Could you help find out the cause of this bug, so that I can open the issue at the xdg-utils repo? Meanwhile I'll close the issue, since it doesn't seem like a Celluloid bug.

**Comment by TingPing** [comment]
> Could you help find out the cause of this bug, so that I can open the issue at the xdg-utils repo? 

It is just a shell script, so I'd read it and figure out what tool its actually launching, like `exo-open` or whatever, and then figure out that tools behavior.

As mentioned `gio` respects the standard, many other tools have their own configuration and behaviors counter to it on purpose.

**Comment by rharish101** [comment]
Thanks for the hints, I'll figure out the rest and submit a bug report upstream.
