### ISSUE TITLE
Please don't deprecate --mpv-options, or provide alternative "verbose mpv" method

### ISSUE THREAD

**Issue by Bananaman** [celluloid-player/celluloid#632]
Hey there!

The --mpv-options is vital for applying a verbose logging mode to mpv, so that I can debug script errors when developing/fixing mpv scripts inside Celluloid.

I use it as follows:

```
celluloid --mpv-options="--msg-level=all=v"
```

It works properly but warns that the feature is going to be removed:

```
** (io.github.celluloid_player.Celluloid:2): WARNING **: 17:34:39.529: --mpv-options is deprecated and will be removed in future versions.
```

I can understand if you want to remove it because many of its options don't work and just confuse users.

But please don't remove it without at least providing some way to set the mpv msg-level to verbose mode.

It's vital for debugging scripts and other mpv issues. :-)

**Comment by gnome-mpv** [comment]
Since v0.19, you can set mpv options using the `--mpv-` prefix instead. For example, `--mpv-msg-level=all=v` is equivalent to `--mpv-options="--msg-level=all=v"`.

**Comment by JJRcop** [comment]
I think this issue should be closed, since it's a non-issue. Maybe the message should say "use --mpv-MPVOPTION=VALUE" for people who didn't read the man page.

**Comment by Bananaman** [comment]
@gnome-mpv @JJRcop Ahh, excellent! That new way of passing flags is much nicer actually, since it will properly handle double quoted arguments.

Glad to see that the latest code improves the depreciation message to talk about thr new way of doing things!
