### ISSUE TITLE
Celluloid doesn't inhibit idle on Wayland (Sway)

### ISSUE THREAD

**Issue by j-james** [celluloid-player/celluloid#639]
Overview Description:
Celluloid doesn't inhibit idle with swayidle, meaning that the screen will turn off / lock while watching a video.

Steps to Reproduce:
1. Set up swayidle to time out after a certain period of time: `exec swayidle -w timeout 100 'swaylock -f' before-sleep 'swaylock -f'`
2. Launch a video in Celluloid under Sway with swayidle.
3. Observe that swayidle times out and locks the screen while Celluloid is still running.

Version:
0.20

Additional Information:
#158 suggests that this is a regression. mpv works fine. My guess would be that now Wayland idle code is in mpv, something's conflicting with Celluloid's implementation.

**Comment by akarshanbiswas** [comment]
Gnome/(GtkApplication?) currently only uses some D-Bus interfaces (org.freedesktop.portal.Inhibit, org.gnome.SessionManager, org.xfce.Session.Manager) which leaves behind simple compositors that don't expose these interfaces
whereas mpv uses [wayland idle-inhibit protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/blob/fad3a831d4c2dac434b0c8a93a54982fb407b935/unstable/idle-inhibit/idle-inhibit-unstable-v1.xml).

Reason why mpv doesn't stop the screen from getting blank when running in Gnome, whereas celluloid player inhibits the screen without any issues when running on Gnome.

**Comment by gnome-mpv** [comment]
This is now working with the git version of GTK4.
