### ISSUE TITLE
--mpv-MPVOPTION=VALUE tokenises incorrectly and so requires quoting of VALUE twice when it contains spaces

### ISSUE THREAD

**Issue by smithfred** [celluloid-player/celluloid#642]
Overview Description:

`--mpv-MPVOPTION` values have to be quoted twice if they contain spaces:

```bash
# Fails:
celluloid --mpv-bluray-device='/path to/dir with spaces' bd://
# Works:
celluloid --mpv-bluray-device="'/path to/dir with spaces'" bd://
```

Steps to Reproduce:
<del>1. Ensure no MPV options set in Prefs -> Misc. (separate bug, to be filed).</del>
2. Run each of the above commands (can be run with non-existent dummy paths to reproduce).

Actual Results:

First form:

```
** (io.github.celluloid_player.Celluloid:<pid>): WARNING **: <time>: Failed to apply option: --to=(null)

** (io.github.celluloid_player.Celluloid:<pid>): WARNING **: <time>: Failed to apply option: --=(null)

[2nd error repeats forever without any window appearing.]
```

Second form: works (window appears, and if path is valid, playback starts).

Expected Results:

Celluloid should correctly create and pass the equivalent option to MPV, without it being quoted twice by the user.

Version:

0.2.0.

**Comment by gnome-mpv** [comment]
This is already fixed in the git version (3766260f61c132922a77ade86749da12c2e16888).
