### ISSUE TITLE
Celluloid freezes completely

### ISSUE THREAD

**Issue by ShrirajHegde** [celluloid-player/celluloid#643]
Overview Description:
I tried to add some options in Extra MPV Options, now MPV completely freezes. Even clearing .config/celluloid doesn't work.

Where is this data stored??

Steps to Reproduce:

1.Add option `--softvol-max` to Extra MPV Options
2.Close and reopen celluloid

Actual Results:

Celluloid completely freezes
Expected Results:

Use the option / give error if incompatible
Version:Celluloid 0.20

Additional Information:
Unable to solve issue by  clearing .config/celluloid

**Comment by gnome-mpv** [comment]
>Where is this data stored??

It's in the dconf database. You can use `dconf-editor` to reset it, or just use this command: `gsettings reset io.github.celluloid-player.Celluloid mpv-options`

>Celluloid completely freezes

ff04e5614aa5b611407f6d06c5ee0ccaa054e5d2 should fix the freeze.
