### ISSUE TITLE
Speed increments go as geometric progression

### ISSUE THREAD

**Issue by ShrirajHegde** [celluloid-player/celluloid#644]
Overview Description:
Speed increments go as geometric progression (1.1)ⁿ instead of 1+0.1*n

Steps to Reproduce:
1.press `]` to increase speed 
2.Notice speed  goes as 1.1,1,21,1.33,1.46.......

Actual Results:

Playback speed  goes as 1.1,1,21,1.33,1.46.......
Expected Results:
Speed increments in 0.1 (1.1,1.2,1.3.....)

Version:
Celluloid 0.20

**Comment by gnome-mpv** [comment]
That's just how mpv works by default. You can get the behavior you want by adding these lines to your input config file.

```
] add speed 0.1
[ add speed -0.1
```

**Comment by ShrirajHegde** [comment]
Ok, thanks
