### ISSUE TITLE
Localization platform

### ISSUE THREAD

**Issue by Carmina16** [celluloid-player/celluloid#645]
Given Zonata no longer being developed, would you consider to move onto some living localization platform, like Weblate or Transifex?

**Comment by gnome-mpv** [comment]
Yes, I'm planning to move to Weblate unless someone has a better suggestion.

**Comment by comradekingu** [comment]
@gnome-mpv Ping me once you do and I'll help. I can help set it up too, but I am no expert :)

**Comment by gnome-mpv** [comment]
@comradekingu
I created a project for Celluloid on Weblate (it's locked for now): https://hosted.weblate.org/projects/celluloid/celluloid/

I'll unlock it once we shutdown the Zanata repo, which I plan to do within the next couple of days.

**Comment by comradekingu** [comment]
Been there looking to see if opened several times now :)

**Comment by gnome-mpv** [comment]
The project on Weblate is now open for translation.
