### ISSUE TITLE
[Bug] Clicking on seekbar leads to unprecise seeking

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [celluloid-player/celluloid#651]
Overview Description:

When clicking on the seekbar with the mouse cursor, the video does not skip to the previewed position. It is always some seconds behind the clicked point in the seekbar. This does not happen with mpv on wayland or x11 with the specific backend. Here is the log from the video playback:

[celluloid.log](https://github.com/celluloid-player/celluloid/files/6251062/celluloid.log)

Steps to Reproduce:
1. Open a longer video file with celluloid. I used Big Buck Bunny in 4K 60fps for testing.
2. Hover over the seekbar.
3. Click on the seekbar.

Actual Results:

The video skip to the wrong position. The playback is not at the shown position when hovering but some seconds before the shown timestamp.

![Bildschirmfoto von 2021-04-02 21-38-47](https://user-images.githubusercontent.com/41188546/113448952-1a2b8200-93fd-11eb-84a3-fffc9d105cd1.png)

Expected Results:

The video skips to the advertised position.

Version:

I used version 0.21 from the fedora repositories with rpmfusion enabled. The flatpak (0.20) behaves the same.

Additional Information:

Linux Distribution: Fedora 33
Desktop: Gnome Wayland
GPU: AMD RX Vega 56
Driver: Mesa 20.3.5

**Comment by popov895** [comment]
Can reproduce in Celluloid 0.24 on openSUSE Tumbleweed.

**Comment by Lassebq** [comment]
Can reproduce in 0.26.
Dragging the slider is precise.
Single click is not precise.

**Comment by gnome-mpv** [comment]
@Lassebq Does setting `hr-seek=yes` fix the problem?

**Comment by Lassebq** [comment]
No

**Comment by Lassebq** [comment]
Just for confirmation, this is not the issue with mpv. Seeking is precise with original mpv without gtk frontend
