### ISSUE TITLE
Location of screenshots (hotkey)

### ISSUE THREAD

**Issue by logicguy1** [celluloid-player/celluloid#652]
Overview Description:

Steps to Reproduce:
1. Press `s` while playing video
2. It saves the screenshot in the images folder

Actual Results:
It saves it to the folder

Expected Results:
I would like to be able to change somewhere where it saves them to

Version:
n/a

Additional Information:
n/a

**Comment by gnome-mpv** [comment]
You can set the `screenshot-directory` option in your config file to change the screenshot folder.

Example:
```
screenshot-directory=/path/to/your/folder
```

**Comment by logicguy1** [comment]
Thank you for the response, where is the config files located? I have been unable to find them.

**Comment by gnome-mpv** [comment]
It doesn't get created automatically. You have to create one yourself and load it in the preferences dialog.

**Comment by logicguy1** [comment]
Alright that makes sense thank you
