### ISSUE TITLE
Does not remember last file's position

### ISSUE THREAD

**Issue by clearoak** [celluloid-player/celluloid#656]
Overview Description: Forgets where it was in a movie, despite option to remember last file's position being ticked. 

Steps to Reproduce:
1. Play a movie part-way.  
2. Stop the movie, or close the player. 
3. Play the movie. 

Actual Results:  Starts from beginning. 

Expected Results:  Start from last play-point. 

Version: 0.20

Additional Information: Linux Mint 20.1 Cinnamon, recent install.

**Comment by gnome-mpv** [comment]
>despite option to remember last file's position being ticked.

That option makes the _file chooser_ remember the last folder something was opened from. That way you don't have to re-navigate to the folder if you want to open something else from the same folder. It has nothing to do with playback position.

To save playback position, close the player by pressing Shift + Q. Alternatively, set the `save-position-on-quit` option in your config file.

**Comment by clearoak** [comment]
Oh!  Thank you for that.   Hadn't realised.   

Is there a way of making it save the position if you only hit 'stop'?

**Comment by gnome-mpv** [comment]
It might be possible to do that using a Lua script, but I'm not completely sure.

The stop button just runs mpv's `stop` command. If you can figure out how to run `write-watch-later-config` when the `stop` command is run but before the current position is lost, then it should work. The closest thing I could could find is the `end-file` event, but it fires a bit too late.

**Comment by clearoak** [comment]
OK, thanks for answering my question, Jason.  I don't think I will devote time to that now but thanks for the pointer if it turns out to be a problem.  (My seven year old tends to hit 'stop'. . . . :-)  )
