### ISSUE TITLE
VA error: wayland: Wayland roundtrip error: Protocol error (errno 71) Cannot load libcuda.so.1

### ISSUE THREAD

**Issue by gitjod** [celluloid-player/celluloid#658]
Overview Description:

Steps to Reproduce:
Run the following from terminal:

flatpak run io.github.celluloid_player.Celluloid

Actual Results:  Get error:

VA error: wayland: Wayland roundtrip error: Protocol error (errno 71)
Cannot load libcuda.so.1
Gdk-Message: 22:55:06.571: Error flushing display: Protocol error

Expected Results: Application should run

Version: Flatpak from flathub Celluloid 0.21

Additional Information:

**Comment by gnome-mpv** [comment]
https://github.com/flathub/io.github.celluloid_player.Celluloid/issues/27

**Comment by gitjod** [comment]
Flathub runtime was updated today and I no longer get the VA error and the application now runs for me. So this would seem to be fixed however I still get an error "Cannot load libcuda.so.1".
