### ISSUE TITLE
request : tooltip with timestamp

### ISSUE THREAD

**Issue by tissatussa** [celluloid-player/celluloid#663]
it would be handy to see a tooltip with the timestamp when hovering over the "play-time-line" : then it's easy to pick & click a certain point in the playing media. I think this will be handy - i often want to skip to a certain time.
I use Xubuntu 20.04 and Celluloid 0.18

**Comment by gnome-mpv** [comment]
This was implemented a long time ago. You need to update to version 0.19 to newer.
