### ISSUE TITLE
[Enhance] Start playing files from last position

### ISSUE THREAD

**Issue by ndias** [celluloid-player/celluloid#664]
This is a request for an enhance, 
- Remember the last position of a file before close the application or change file
- Continue playing from the last position

**Comment by regulator-g** [comment]
Hi I just came on here to write that this setting does not work, when loading mpv.conf, my videos always start from the start

#general
save-position-on-quit

**Comment by gnome-mpv** [comment]
@regulator-g Are you using Flatpak?

**Comment by regulator-g** [comment]
@gnome-mpv hmm yep, let me guess it can't access the MPV config file? Where should I put the file? 😅

**Comment by gnome-mpv** [comment]
@regulator-g 
If you have just that one option in your file, you can put `--save-position-on-quit` in the `Extra mpv options` textbox under the `Miscellaneous` tab.

Otherwise, you can also explicitly grant access to your config file: `flatpak override --user --filesystem=/path/to/your/mpv.conf io.github.celluloid_player.Celluloid`

**Comment by regulator-g** [comment]
hmm, -save-position-on-quit gives me "failed to apply one or more MPV options"

I have done the flatpak command and restarted but the feature still does not work, weirdly 3 movie folders are listed in the flatpak permissions too!
documents  ca4da607   io.github.celluloid_player.Celluloid read,write,grant-permissions (b'/home/tgfunk/.config/mpv/mpv.conf', 64769, 40239183, 0)

i guess next option is to try a .deb installer/PPA..

**Comment by gnome-mpv** [comment]
>hmm, -save-position-on-quit gives me "failed to apply one or more MPV options"

There should be 2 dashes at the beginning of the option.

**Comment by regulator-g** [comment]
with two dashes the error is gone but files still do not resume from last position.. I put a window setting in my config too which didn't work so I guess Celluloid still cant read my mpv.conf

I'm on Ubuntu / Gnome / Wayland btw, could be a wayland thing

**Comment by ndias** [comment]
Just to help a little here @regulator-g 

In the conf of celluloid --save-position-on-quit and these works, with some issues ... from man page

"This does not happen if playback of a file is stopped in any other way than quitting.  For  example, going  to  the next file in the playlist will not save the position, and start playback at beginning the next time the file  is played."

 So maybe you are making one of the issues listed that will not save the position.

**Comment by regulator-g** [comment]
thanks, I switched from flatpak to .deb version and now it loads my mpv.conf file.. and remembers last position. So the flatpak version I guess it cant access the filesystem properly even with that override.. I had the same thing happen with a snap package once

**Comment by ndias** [comment]
Why this was closed? like I wrote in https://github.com/celluloid-player/celluloid/issues/664#issuecomment-855767444 the --save-position-on-quit doesn't solve everything, It only save the last file played and only if I quit the application!

**Comment by gnome-mpv** [comment]
@ndias
Sorry, I didn't quite understand what you meant in that comment. Are you saying that the entire playlist should be saved on quit, or that the position should be saved even if you stop the playback by going to the next file in the playlist, or something else?

**Comment by regulator-g** [comment]
My 2c is that in general the "remember last position" feature needs to be improved, so remember the position regardless of how the application is closed, and remember position for last 10-100 files. SMplayer for example always remembers file position

**Comment by ndias** [comment]
ok, let me explain, the mpv with --save-position-on-quit only save the last position of the last file that I was playing and if only I close the player.
What I was requesting was save the position of a file on quit,  playing next file in playlist, importing a new file, etc, so if I stop playing a file the position is recorded unless is in the end of the file :)
The number of files saved, maybe can be an option, or at least a big number 50 files for example, only the last 50 and only if they were interrupted before the end.

**Comment by gnome-mpv** [comment]
> playing next file in playlist, importing a new file, etc

This is something that should be implemented in upstream mpv. AFAIK there's no event/hook that can to be used for writing `watch_later` file.

**Comment by regulator-g** [comment]
fair enough, will ask that team then. Not sure how SMplayer does it so well, its also an MPV front end
