### ISSUE TITLE
REQUEST Load multiple subtitle tracks simultaneously and display them

### ISSUE THREAD

**Issue by KyleBroflowski** [celluloid-player/celluloid#667]
How to display multiple sub tracks and controll their font sizes and lags inndiividually?

**Comment by gnome-mpv** [comment]
>How to display multiple sub tracks

There's no GUI for this right now, but you can use `--mpv-secondary-sid` if you start celluloid from the command line (e.g. `celluloid --mpv-secondary-sid=1 video.webm`) to display a second subtitle. mpv's manpage has more info (look for the `--secondary-sid` option).

>controll their font sizes and lags inndiividually?

This isn't possible right now. mpv would have to support this first.

**Comment by pourmand1376** [comment]
Mpv now supports secondary subtitles through `--secondary-sid` and [here](https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst)'s their documentation. Shouldn't this be added to Celluloid?

**Comment by gnome-mpv** [comment]
@pourmand1376 
Yes, a GUI `--secondary-sid` could be added. mpv still doesn't support setting font size and delay for each subtitle individually though.

**Comment by pourmand1376** [comment]
I think even just that could be enough.
