### ISSUE TITLE
Question SET CUSTOM MOUSE BUTTON ACTIONS

### ISSUE THREAD

**Issue by KyleBroflowski** [celluloid-player/celluloid#668]
I'd like to set seek by 5 and 10s on mouse thumb buttons

**Comment by gnome-mpv** [comment]
You can use an input config file to do this. For example:

```
MBTN_FORWARD seek 5
MBTN_BACK seek 10
```
The general syntax is key name (this includes mouse buttons) followed by a command. You can run `mpv --input-test --idle --force-window` to figure out key names for the buttons that you want to use. The `COMMAND INTERFACE` section in mpv's manpage has more details.

Once you have your input config file, you can load it in Celluloid under the `Config Files` tab in the `Preferences` dialog.

**Comment by KyleBroflowski** [comment]
How to set the hold button action?
I've now used  for `MBTN_FORWARD sub-seek 1` seeking subs forward but I'd like to be able to hold it to repeat the action until I let go. (Just like the keyboard shortcut **Ctrl + Right**

**Comment by gnome-mpv** [comment]
You need a script to do that. There's one that does what you want in this [mpv issue](https://github.com/mpv-player/mpv/issues/8640#issuecomment-796621911).
