### ISSUE TITLE
translation: some strings are untranslatable

### ISSUE THREAD

**Issue by zhmars** [celluloid-player/celluloid#675]
**Overview Description**:

Hi, I'm unable to find some strings below to translate for Chinese (Simplified) on Weblate. It seems they could not be found from all languages except English. Could someone confirm it?

- `Always append opened files to playlist` (Preferences -> Miscellaneous)
- `Add to Playlist` (right click the icon on GNOME desktop)

**Steps to Reproduce**:
1. Visit the Celluloid's page on Weblate and search the strings

**Actual Results**:

  No strings found

**Expected Results**:

  Found the strings to translate

**Version**:

celluloid 0.21

**Additional Information**:

**Comment by gnome-mpv** [comment]
The PO files were outdated earlier so some strings were missing. I just updated them so all strings should be available now.

**Comment by zhmars** [comment]
Translating. Thanks for quick response.
