### ISSUE TITLE
Make bottom corners round

### ISSUE THREAD

**Issue by k-kirill** [celluloid-player/celluloid#676]
In GNOME 40 many applications have nice round bottom corners, so it would be nice if Celluloid supported this feature too. For example, it's the corresponding commit for Nautilus: https://gitlab.gnome.org/GNOME/nautilus/-/commit/2451836f71a5d80a55115343908c8656c81c3367

**Comment by jannuary** [comment]
We can have this for free with GTK4:
![image](https://user-images.githubusercontent.com/27908024/136017047-d8244240-4c55-48f4-898e-2cd365af0480.png)

**Comment by k-kirill** [comment]
@jannuary just wanted to thank you as defining `border-radious: 8px` in `.config/gtk-4.0/gtk.css` did help for Celluloid, Extensions and other GTK4 apps that hadn't had round corners before :)
```
$ cat .config/gtk-4.0/gtk.css 
window {
  border-radius: 8px;
}
```

**Comment by jannuary** [comment]
This has been shipped :)
