### ISSUE TITLE
Celluloid crashes when trying to open a file

### ISSUE THREAD

**Issue by eyalroz** [celluloid-player/celluloid#680]
**Overview Description:**
Celluloid crashes when trying to open a file - any file

**Steps to Reproduce:**
1. Start Celluloid 0.21 with no source file
2. Drag a video file with audio onto the window, or press Ctrl+O and select such file 

**Actual Results:**
Crash. Console output:
```
io.github.celluloid_player.Celluloid:18866): GLib-GIO-ERROR **: 20:39:41.694: Settings schema 'io.github.celluloid-player.Celluloid' does not contain a key named 'always-append-to-playlist'

[1]+  Trace/breakpoint trap   /opt/versions/celluloid-0.21/bin/celluloid
```

**Expected Results:**
No crash...

**Version:**
0.21 release, built from source

**Additional Information:**

* Using Devuan 4 Chimaera (~= Debian Bullseye without systemd)
* Built with meson and ninja
* The distribution-provided version 0.20 doesn't exhibit this behavior.
* Adding `/opt/version/celluloid-0.21/share` to `$XDG_DATA_DIRS` does not help.

**Comment by TingPing** [comment]
> /opt/versions/celluloid-0.21/bin/celluloid

Custom prefixes often require setting various env vars to function.

Adding `/opt/versions/celluloid-0.21/share` to `XDG_DATA_DIRS` would fix this issue.

**Comment by eyalroz** [comment]
@TingPing : 

1. That should absolutely not cause a crash. At most - an error message.
2. Doing so did not change the behavior
3.

**Comment by eyalroz** [comment]
Ok, dupe of my own #634. Embarrassing.
