### ISSUE TITLE
Settings do not persist in combination with firejail!

### ISSUE THREAD

**Issue by s-a-p-i-e-n-s** [celluloid-player/celluloid#683]
Overview Description:

Steps to Reproduce:
1. Install and configure Firejail
2. Install celluloid
3. Try to persist options in preferences e.g. load mpv config file
 
Actual Results:
Celluloid immediately discards any changes made 

Expected Results:
Celluloid should persist the changes

Version:
0.21

Additional Information:
I am fully aware that celluloid is able to persist changes in general. However the premade firejail profile seems to interfere with this behavior. Firejail gives Celluloid read and write access to `${HOME}/.config/celluloid` but this does not seem to be enough. Were does Celluloid try to persist changes done under preferences and in particular when I use the `load mpv config file`option, so that I can create a custom profile and maybe create a pull request to the profile repository.

**Comment by TingPing** [comment]
Set `GTK_USE_PORTAL=1` and set `XDG_CONFIG_HOME` to a private location. Then it should all work.

**Comment by s-a-p-i-e-n-s** [comment]
This is the output I get when trying to set the config file.
```
(io.github.celluloid_player.Celluloid:60): Gtk-WARNING **: 12:53:40.885: Attempting to store changes into '/home/sapiens/.local/share/recently-used.xbel', but failed: Failed to create file “/home/sapiens/.local/share/recently-used.xbel.NPZA80”: Read-only file system

(io.github.cellu(io.github.celluloid_player.Celluloid:60): Gtk-WARNING **: 12:53:40.885: Attempting to store changes into '/home/sapiens/.local/share/recently-used.xbel', but failed: Failed to create file “/home/sapiens/.local/share/recently-used.xbel.NPZA80”: Read-only file system

(io.github.celluloid_player.Celluloid:60): Gtk-WARNING **: 12:53:40.885: Attempting to set the permissions of '/home/sapiens/.local/share/recently-used.xbel', but failed: No such file or directory
(io.github.celluloid_player.Celluloid:60): Gtk-WARNING **: 12:53:40.885: Attempting to store changes into '/home/sapiens/.local/share/recently-used.xbel', but failed: Failed to create file “/home/sapiens/.local/share/recently-used.xbel.NPZA80”: Read-only file system

(io.github.celluloid_player.Celluloid:60): Gtk-WARNING **: 12:53:40.885: Attempting to set the permissions of '/home/sapiens/.local/share/recently-used.xbel', but failed: No such file or directory

(io.github.celluloid_player.Celluloid:60): dconf-WARNING **: 12:53:56.671: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(io.github.celluloid_player.Celluloid:60): dconf-WARNING **: 12:53:56.671: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
loid_player.Celluloid:60): Gtk-WARNING **: 12:53:40.885: Attempting to set the permissions of '/home/sapiens/.local/share/recently-used.xbel', but failed: No such file or directory

(io.github.celluloid_player.Celluloid:60): dconf-WARNING **: 12:53:56.671: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

```
When I set `GTK_USE_PORTAL=1`the menu to select the file does not even open and I receive the following in the terminal:
```
(io.github.celluloid_player.Celluloid:60): GLib-CRITICAL **: 12:56:05.817: g_variant_new_string: assertion 'string != NULL' failed

(io.github.celluloid_player.Celluloid:60): Gtk-WARNING **: 12:56:05.819: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

```

**Comment by TingPing** [comment]
So you probably don't want to use DConf at all, its a sandbox escape effectively. GSettings has a keyfile backend which is what I'm suggesting.

`GTK_USE_PORTAL=1` enables all of the sandbox friendly APIs, including forcing GSettings to use keyfiles, however this does require `xdg-desktop-portal` installed on the host, as well as DBus access to talk to `org.freedesktop.portal.Desktop`. That will solve your last warnings.

**Comment by s-a-p-i-e-n-s** [comment]
I set `GTK_USE_PORTAL=1` as en environment variable for the firejail profile and also allowed it access to ~/glib-2.0/settings.

Celluloid does currently not open the file selection dialog/window to select the config file when I click on it but outputs
```
(io.github.celluloid_player.Celluloid:60): GLib-CRITICAL **: 22:50:57.494: g_variant_new_string: assertion 'string != NULL' failed

(io.github.celluloid_player.Celluloid:60): Gtk-WARNING **: 22:50:57.505: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

**Comment by TingPing** [comment]
> however this does require xdg-desktop-portal installed on the host, as well as DBus access to talk to org.freedesktop.portal.Desktop. That will solve your last warnings.

**Comment by s-a-p-i-e-n-s** [comment]
Thank you for your help so far, now I am already a step closer.
```
[sapiens@computer ~]$ pacman -Q | grep xdg-desktop
xdg-desktop-portal 1.8.1-1
xdg-desktop-portal-gtk 1.8.0-1
```
~/.config/firejail/celluloid.local
```
env GTK_USE_PORTAL=1
env XDG_CONFIG_HOME=/home/sapiens/.config/celluloid
dbus-user.talk org.freedesktop.portal.Desktop    
```
I am now able to open a file selection window when I click on the button under `load mpv configuration file` but still receive the following errors when I hit `apply`.
```
(io.github.celluloid_player.Celluloid:60): dconf-WARNING **: 18:34:44.017: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(io.github.celluloid_player.Celluloid:60): GLib-CRITICAL **: 18:34:51.366: g_variant_new_string: assertion 'string != NULL' failed

```

**Comment by rusty-snake** [comment]
(coming from netblue30/firejail#4469)

As i understand https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gportalsupport.c `GTK_USE_PORTAL=1` has no effect on the gsettings backend.

```C
else // [ -e "/.flatpak-info" ]
  {
    const char *var;

    var = g_getenv ("GTK_USE_PORTAL");
    if (var && var[0] == '1')
      use_portal = TRUE;
    network_available = TRUE;
    dconf_access = TRUE;
  }
```

`GSETTINGS_BACKEND=keyfile` seems to be the trick.
