### ISSUE TITLE
Mousescroll seeking not working on Wayland

### ISSUE THREAD

**Issue by francoism90** [celluloid-player/celluloid#684]
Overview Description:
This is the same as #207, however it was working for some time.
I don't know if this is a mpv issue and should be reported upstream.

Steps to Reproduce:
```
// input.conf

// mouse wheel do not work
WHEEL_UP      seek 10
WHEEL_DOWN    seek -10
WHEEL_LEFT    seek 10
WHEEL_RIGHT   seek -10

// arrow-keys work
RIGHT seek  5
LEFT  seek -5
UP    seek  60
DOWN  seek -60
```

Actual Results:
Not seeking

Expected Results:
Allow mouse scroll to seek

Version:
git - master

Additional Information:
GS40 - Wayland

**Comment by francoism90** [comment]
@gnome-mpv Many thanks! :)

Could you please tag a new release as well?

**Comment by gnome-mpv** [comment]
@francoism90
Right now playlist reordering is still broken due to a regression in GTK, so I can't make a release yet. I'm working on a workaround, but it could take a while.

**Comment by francoism90** [comment]
@gnome-mpv Thanks for letting me know, take your time. :)
