### ISSUE TITLE
"Open..." & select all files => adds them in reverse order

### ISSUE THREAD

**Issue by dxps** [celluloid-player/celluloid#695]
Overview Description:

Using Celluloid ver. 0.21, using `Open...` and select all files using Ctrl + A adds them to the playlist in the reversed (naming) order.

Steps to Reproduce:
1. Click `+` top left button and click `Open...` option.
1. The _Open File_ window opens, navigate to a location and use Ctrl + A to select all the files (.mp4 videos).
1. The files are added to the playlist, but in the descending order.

Actual Results: The files are added in the reverse (not ascending) order.

Expected Results: The files should be added in the ascending order, that is to have the same correct behavior that `Open Folder...` option has.

Version: `0.21`

Additional Information:

![image](https://user-images.githubusercontent.com/14140226/134971310-16bb7692-97d4-407a-a4e5-bd0b3db6c820.png)

Thanks for continuing this nice project and app!

**Comment by gnome-mpv** [comment]
That sounds like #315. Are you using Flatpak?

**Comment by dxps** [comment]
Yes, I am using the Flatpak version. I can confirm that using `.deb` version is behaves correctly,
even with ver. `0.20` that's currently available on Pop!_OS 21.04's store (Pop!_Shop).

Thanks for the quick feedback!
I'll close the ticket. Hopefully others will find that issue or this one (I guess I was just searching for _sort_ word on issues, that's why I didn't find anything and created this one).

**Comment by gnome-mpv** [comment]
Duplicate of #315
