### ISSUE TITLE
Celluloid does not use selected system's output sound device, but defaults to Line out

### ISSUE THREAD

**Issue by skmd0** [celluloid-player/celluloid#699]
### Overview Description:
I have 2 headphones plugged in. One in the back of my PC, second one in the monitor (via HDMI). In the GNOME system settings the audio device is set to the HDMI one, but I am getting sound from the headphones plugged in from the back of the PC.

If I unplug the headphones from the back of my PC, Celluloid uses the headphones from HDMI monitor because it is the only device left. If I replug the heaphones back in, the Celluloid will switch back to the device plugged in to the back of the PC.

mpv uses the device selected in GNOME system settings.

### Steps to Reproduce:

1. Setup 2 audio devices
2. Check which one Celluloid uses
3. Switch the main audio device in the system settings so it uses the opposite of what celluloid prefers
4. Restart Celluloid and check if it still uses the same audio device

### Actual Results:
Celluloid does not use the selected audio device from system settings.

### Expected Results:
Celluloid should use the correct audio device.

### Version:
0.21

### Additional Information:
- Arch Linux
- GNOME desktop environment 40.4.0

**Comment by gnome-mpv** [comment]
>mpv uses the device selected in GNOME system settings.

That's weird. Celluloid doesn't touch audio streams at all, so mpv should be handling all that.

Are you sure Celluloid is linked against the same version of mpv you're testing with?
