### ISSUE TITLE
Option for yt-dlp

### ISSUE THREAD

**Issue by VarLad** [celluloid-player/celluloid#702]
Overview Description: youtube-dl has not seen any development for months. Since Youtube capped the download speed limit for its videos, its really hard to `youtube-dl` with Celluloid for playing videos

Steps to Reproduce:
1. `celluloid https://www.youtube.com/watch?v=gYXpRWHVIPE`

Actual Results: Video playing with a lot of stutters for some people
Expected Results: Video playing smoothly

Version: 0.21

Additional Information: Most to everyone is now shifting to the [yt-dlp](https://github.com/yt-dlp/yt-dlp) fork
It would be nice if there was a small option in the Settings to use `yt-dlp` instead of `youtube-dl`

**Comment by MintMain21** [comment]
SMPlayer, SMTube, and MPV have all moved to yt-dlp with legacy support for yt-dl, so, yeah, definitely something to keep in mind.

**Comment by TingPing** [comment]
I believe this is 100% handled by `mpv`, and just by updating it Celluloid will use `yt-dlp`.

**Comment by TingPing** [comment]
I believe this is 100% handled by `mpv`, and just by updating it Celluloid will use `yt-dlp`.

**Comment by gnome-mpv** [comment]
@TingPing is right. The latest mpv release (0.34) uses yt-dlp by default now, so you can just update to that version.

**Comment by MossyMossMoss** [comment]
Will confirm if this works on the flatpak version when it's updated

**Comment by MossyMossMoss** [comment]
It works :+1:

**Comment by VarLad** [comment]
@Vascom I guess you're the packager for Fedora
Celluloid Fedora package has a dependency on youtube-dl 
Can you change it to yt-dlp instead?

**Comment by Vascom** [comment]
Yes, I can add this dependency.

**Comment by VarLad** [comment]
@Vascom yt-dlp hasn't been packaged yet
Would that require you to package it as well?

**Comment by Vascom** [comment]
Work in progress
https://bugzilla.redhat.com/show_bug.cgi?id=2012522

**Comment by smithfred** [comment]
yt-dlp is packaged and in updates-testing on Fedora now (https://koji.fedoraproject.org/koji/packageinfo?packageID=yt-dlp).

Bug for Celluloid deps update in RPMFusion: https://bugzilla.rpmfusion.org/show_bug.cgi?id=6141

**Comment by Vascom** [comment]
What changes need for celluloid so it can use yt-dlp instead of youtube-dl?
