### ISSUE TITLE
Celluloid does not follow system theme

### ISSUE THREAD

**Issue by xelser** [celluloid-player/celluloid#703]
Celluloid seemingly ignoring GTK theming and it has these errors when i launch it in the terminal.

 `Cannot load libcuda.so.1`

mpv seems to be working fine though. I tried themes that supports GTK 4, like Matcha but still doesn't follow it.

Distro: Arch Linux

**Comment by francoism90** [comment]
@xelser Could you try unchecking 'Enable dark theme' in Preferences? This seems to fix the issue for me.

**Comment by xelser** [comment]
@francoism90 Doesn't work either.

**Comment by cutrus** [comment]
@xelser I have the same problem. The reason is probably the app was rewritten to use GTK4. My system theme doesn't have GTK4 version :(

**Comment by gnome-mpv** [comment]
@xelser Are you using Flatpak?

**Comment by xelser** [comment]
@gnome-mpv Nope, im using arch's official package.

**Comment by gnome-mpv** [comment]
I just tried installing the`matcha-gtk-theme` package from AUR and switching the theme using `gnome-tweaks`. It seems to work fine here.

**Comment by xelser** [comment]
Okay my setup apparently doesn't play nice with GTK4 apps, i downloaded `gnome-todo` as a test and the problem occurs. I did a little digging and found out that GTK4 uses GPU for rendering?? I don't know if that's accurate, and my old pc doesn't have GPU nor Integrated Graphics. That sucks then.

**Comment by francoism90** [comment]
@xelser Gnome-TODO is broken for me as well, it has nothing to do with GPU rendering (it's 'just' a render backend).

Also note libawaita doesn't have custom theme support, you'll see more apps missing theme-support unfortunately.

**Comment by xelser** [comment]
I'll just use VLC, I seriously don't understand what's wrong

**Comment by xelser** [comment]
I guess it has to do with DE or WMs. I may have missing packages or something. (I use openbox).

**Comment by TingPing** [comment]
>  I did a little digging based of the error that I had and found out that GTK4 uses GPU for rendering?? I don't know if that's accurate, and my old pc doesn't have GPU nor Integrated Graphics.

GTK4 works fine with both CPU and GPU rendering, it will fallback to `cairo` on the CPU if OpenGL fails (and OpenGL itself runs on the CPU with llvmpipe just fine).

Anyway this is unrelated to the theming topic of course.

**Comment by TingPing** [comment]
@xelser Try running this to set the theme: `gsettings set org.gnome.desktop.interface gtk-theme 'YourThemeName'`

**Comment by xelser** [comment]
@TingPing It doesn't work, unfortunately.

**Comment by HugLifeTiZ** [comment]
> Okay my setup apparently doesn't play nice with GTK4 apps, i downloaded `gnome-todo` as a test and the problem occurs. I did a little digging based of the error that I had and found out that GTK4 uses GPU for rendering?? I don't know if that's accurate, and my old pc doesn't have GPU nor Integrated Graphics. That sucks then if that is the case.

gnome-todo is an Adwaita app. It won't follow your system theme anyways.

**Comment by swomf** [comment]
@xelser  Not to necrobump if this is already considered fully solved, but I found this thread and was able to solve this problem by symlinking assets in `~/.config/gtk-4.0` to the `gtk-4.0` directory of a theme. This convinces nonconforming libadwaita apps to follow your `gtk-4.0` theme. It's not a Celluloid problem, it's probably a libadwaita problem...

Also, `cannot load libcuda.so.1` isn't related to whether Celluloid runs your gtk theme at all, so you don't have to worry about that!

### example of a working theme

Matcha-gtk pueril theme, old integrated graphics computer running XFCE4
![image](https://github.com/celluloid-player/celluloid/assets/108753551/e3051227-2282-42a6-9103-07d73dab2e1f)

### more info

a new [post_install warning](https://aur.archlinux.org/cgit/aur.git/commit/?h=matcha-gtk-theme&id=d7070db25c338fa1788d2629e52579bfe6338fde) for the GTK theme's AUR package discusses how to fix it

> ```sh
> post_install() {
>  echo ""
>  echo "To force Libadwaita appliations to use the gtk-4.0 theme,"
>  echo "symlink the gtk-4.0 theme to config folder"
>  echo "(replace Matcha-dark-sea with chosen theme variant):"
>  echo ""
>  echo "mkdir -p ~/.config/gtk-4.0/"
>  echo "ln -sf /usr/share/themes/Matcha-dark-sea/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/"
>  echo ""
> }
> ```

and this solution was copied from the [install.sh](https://github.com/vinceliuice/Matcha-gtk-theme/blob/819ccff3e9cd85de5216b5001f353d4f97112818/install.sh#L482) of the GTK theme anyway.

[More info on the workaround](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2F7ekngnc6mr291.png%3Fwidth%3D4327%26format%3Dpng%26auto%3Dwebp%26s%3D35ce61847d8dfdc9570cee3177af05c3b1a87b45)

**Comment by TingPing** [comment]
>  it's probably a libadwaita problem...

libadwaita by design bundles its own theme, so apps have a theme to target. You can indeed inject anything at your own risk.

Note that Celluloid didn't use libadwaita at the time of this issue being opened, but it does now.

So I think this can be closed.
