### ISSUE TITLE
Size of the window

### ISSUE THREAD

**Issue by didierga** [celluloid-player/celluloid#705]
Overview Description:

With celluloid-0.21-2.fc35.x86_64 window size was saved and next video was opened in a window of the same size.
I cant reproduce this behaviour with celluloid-0.22-1.fc35.x86_64

Steps to Reproduce:
1. Start a video
2. Adjust window size as you want, in my case full scree 
3. Close this video
4. Start an other video

Actual Results:

Window is adjusted to the video, not to the previous window size
 
Expected Results:

Same window size as the previous video 

Version:

celluloid-0.22-1.fc35.x86_64

Additional Information:

**Comment by JaneSmith** [comment]
I've also been experiencing issues with the window size in version 0.22. For me it opens in a very tiny size every time which is very frustrating.

**Comment by JaneSmith** [comment]
Is there any chance a new version could be released? I see this issue has been patched, but at least with the modern Flatpak from Flathub, it's still on version 0.22 and this bug is still there. It's really frustrating. Thanks.

**Comment by gnome-mpv** [comment]
There are a few issues that need to be dealt with before making a new release, e.g. #710, #711.
