### ISSUE TITLE
Drag & drop stopped working in 0.22

### ISSUE THREAD

**Issue by bxkx** [celluloid-player/celluloid#710]
Overview Description: Unfortunately since 0.22 there're now several issues making Celluloid barely usable for me anymore.
Whenever I try to drag and drop a file or subtitle the first time nothing happens at all and from second attempt I'm getting error messages.

Steps to Reproduce:
1. Start video with celluloid from terminal
2. Drag subtitle or video file onto the video
3. Check terminal for error

Actual Results: No subtitles are shown, error in log
```
(io.github.celluloid_player.Celluloid:46536): Gtk-WARNING **: 22:27:29.808: (../gtk/gtk/gtkdroptarget.c:476):gtk_drop_target_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.celluloid_player.Celluloid:46536): Gtk-CRITICAL **: 22:27:29.809: gtk_drop_target_handle_event: assertion 'self->drop == gdk_dnd_event_get_drop (event)' failed
```

Expected Results: Load subtitles successfully.

Version: 0.22

Additional Information: I'm running Xorg with Nvidia w/ latest proprietary drivers, Arch Linux. A friend with Intel laptop doesn't seem to have this issue.

**Comment by rotalumi** [comment]
I can confirm that drag-and-drop functionality no longer works for me since the upgrade to Celluloid 0.22. In particular, when I drag any audio, video or playlist file from the Thunar file manager onto Celluloid, the file is rejected by Celluloid and the icon slides back to Thunar.

Downgrading to Celluloid 0.21 restores normal drag-and-drop functionality.

* Xfce on Arch Linux
* Intel graphics

**Comment by MaCroX95** [comment]
Please we need this fixed. 

Browsing through folders each time when we want to drag and drop subtitles into the player is really cumbersome, and it doesn't even remember the last folder where we used to load the subtitles from.

Hopefully this can get fixed as soon as possible.

**Comment by gnome-mpv** [comment]
>EDIT: BTW This affects Wayland too.

I'm only able to reproduce the bug on X11. Drag and drop works fine for me on Wayland.

**Comment by MaCroX95** [comment]
> > EDIT: BTW This affects Wayland too.
> 
> I'm only able to reproduce the bug on X11. Drag and drop works fine for me on Wayland.

Sorry, this seems to be a different issue, actually it's a flatpak sandobxing issue, the app by default for some reason doesn't get the access to user files /home and is apparently unable to load the subtitles by drag and dropping it? After giving Celluloid that permission through Flatseal it starts working as expected.

Should I open a bug report on the flathub repo for Celluloid?

**Comment by gnome-mpv** [comment]
> Should I open a bug report on the flathub repo for Celluloid?

The maintainer is already aware of this issue.

**Comment by gnome-mpv** [comment]
With GTK 4.4.1, I can no longer reproduce this. There's still an error message (different from the one in this issue) printed when drag and dropping on X11, but the file gets loaded normally.

Is this still a problem for anyone else?

**Comment by rotalumi** [comment]
Unfortunately, I continue to experience the problem as described here:

https://github.com/celluloid-player/celluloid/issues/710#issuecomment-973202157

- I'm using Xfce 4.16 on Arch Linux.
- I'm using GTK 4.4.1.
- I'm dragging an icon from Thunar 4.16.10 and dropping it onto Celluloid 0.22.

Drag-and-drop functionality is restored when I downgrade to Celluloid 0.21.

**Comment by bxkx** [comment]
Unfortunately the issue remains for me with 0.23


I tried it with Thunar and PCManFM
```
(io.github.celluloid_player.Celluloid:73031): Gdk-CRITICAL **: 16:06:30.887: gdk_drop_set_actions: assertion 'priv->state == GDK_DROP_STATE_NONE' failed
```

as well as PCManFM-QT

```
(io.github.celluloid_player.Celluloid:72717): Gtk-WARNING **: 16:04:39.559: (../gtk/gtk/gtkdroptarget.c:477):gtk_drop_target_handle_crossing: runtime check failed: (self->drop == NULL || self->drop == crossing->drop)

(io.github.celluloid_player.Celluloid:72717): Gtk-CRITICAL **: 16:04:39.559: gtk_drop_target_handle_event: assertion 'self->drop == gdk_dnd_event_get_drop (event)' failed
```

**Comment by rotalumi** [comment]
For me, with the upgrade to Celluloid 0.23, drag-and-drop functionality from Thunar to Celluloid has been restored.

I am using:

* Celluloid 0.23
* Xfce 4.16 on Arch Linux
* Thunar 4.16.10
* GTK4 4.6.1

**Comment by bxkx** [comment]
I'm using OpenBox and tried IceWM as well and both aren't working. I had a friend try and it didn't work for him in i3 nor Plasma.
I gave it a try in a WM w/ Xfce and Thunar and it worked there. Certainly weird.

**Comment by bxkx** [comment]
Now that mpv got updated I was forced to update to the latest Celluloid and drag & drop is still not working except with Xfce and Thunar.
