### ISSUE TITLE
Crashes in file-chooser dialog when sorting by access time

### ISSUE THREAD

**Issue by gslicer** [celluloid-player/celluloid#712]
Overview Description:

```
slicer@cosmos ~> celluloid 
Cannot load libcuda.so.1

(io.github.celluloid_player.Celluloid:12610): Gtk-CRITICAL **: 12:04:11.405: _gtk_tree_path_new_from_rbtree: assertion 'node != NULL' failed

(io.github.celluloid_player.Celluloid:12610): Gtk-CRITICAL **: 12:04:11.405: gtk_tree_model_get_iter: assertion 'path->depth > 0' failed
fish: Job 1, 'celluloid' terminated by signal SIGSEGV (Address boundary error)
```

Steps to Reproduce:
1. +
2. Open
3. Click on the "Accessed" column tite

Actual Results:
crash

Expected Results:
sorted column

Version:
slicer@cosmos ~> sudo dnf info celluloid

Installed Packages
Name         : celluloid
Version      : 0.22
Release      : 1.fc35
Architecture : x86_64
Size         : 1.2 M
Source       : celluloid-0.22-1.fc35.src.rpm
Repository   : @System
From repo    : rpmfusion-free-updates
Summary      : A simple GTK+ frontend for mpv
URL          : https://github.com/celluloid-player/celluloid
License      : GPLv3+
Description  : Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv.
             : It aims to be easy to use while maintaining high level of configurability.

Additional Information:
Is 'libcuda' a missed dependency on Fedora ?

**Comment by gnome-mpv** [comment]
Confirmed. Seems to happen randomly when clicking on column headers in the file chooser.

> Is 'libcuda' a missed dependency on Fedora ?

No. That's just mpv probing libraries to use for hardware decoding. It's normal if you're not using an Nvidia card.

**Comment by gnome-mpv** [comment]
I think this is probably a bug in Gtk. It's seems to be triggered when allowing multiple files to be selected in the file chooser dialog (by calling `gtk_file_chooser_set_select_multiple()`). I'm able to reproduce the crash with both `GtkFileChooserNative` and `GtkFileChooserDialog`.
