### ISSUE TITLE
Window is smaller every time Celluloid is opened (0.22 regression)

### ISSUE THREAD

**Issue by smithfred** [celluloid-player/celluloid#713]
Overview Description:

On Celluloid 0.22.x, the main window is about 10% smaller each time Celluloid is opened (seems to be a width/height reduction of about the height of the title bar). This is a regression from 0.21.x.

Steps to Reproduce:
1. Disable "Automatically resize window to fit video".
2. Launch Celluloid with any video.
3. Close and relaunch Celluloid with any video.

Actual Results:

Window is about 90% of the previous size (seems to be a width/height reduction of about the height of the title bar).

Expected Results:

Window is the same size both times.

Version:

0.22.

Additional Information:

Regression from 0.21.x.

**Comment by didierga** [comment]
I confirm this bug with Fedora 35 and celluloid-0.22-2.fc35.x86_64
