### ISSUE TITLE
Crashes on certain track titles

### ISSUE THREAD

**Issue by gslicer** [celluloid-player/celluloid#714]
Overview Description:
Some characters in track names lead to crash, could be a GTK+ bug

Steps to Reproduce:
1. play a stream e.g. http://stream01.my105.ch/my105djradio-aac.mp3
2. wait until a track appears having the problematic chars
3. boom

Actual Results:
(io.github.celluloid_player.Celluloid:12704): Gdk-WARNING **: 09:22:41.755: Invalid utf8 passed to gdk_surface_set_title: 'TI\xcbSTO & KILLFAKE - MONEY'

(io.github.celluloid_player.Celluloid:12704): GLib-CRITICAL **: 09:22:41.755: g_variant_new_take_string: assertion 'g_utf8_validate (string, -1, NULL)' failed

(io.github.celluloid_player.Celluloid:12704): GLib-CRITICAL **: 09:22:41.755: g_variant_new_variant: assertion 'value != NULL' failed
fish: Job 1, 'celluloid' terminated by signal SIGSEGV (Address boundary error)

Expected Results:
Playing this track flawlessly

Version:
Name         : celluloid
Version      : 0.22
Release      : 2.fc35
Architecture : x86_64
Size         : 1.2 M
Source       : celluloid-0.22-2.fc35.src.rpm
Repository   : @System
From repo    : rpmfusion-free-updates
Summary      : A simple GTK+ frontend for mpv
URL          : https://github.com/celluloid-player/celluloid
License      : GPLv3+
Description  : Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv.
             : It aims to be easy to use while maintaining high level of configurability.

Additional Information:
I like this player, but it lacks some basic functions like:
- remembering the position on shut-down to resume after restart at this position
- open file dialog does not remember the last opened file
- option for audio normalization (important for movies where SFX often override voice)
- setting size/colors of subtitles

life hack: I'm using Celluloid as my favorite OLED screensaver when idle or plaing audio only in full screen mode, because it produces a perfect pitch black :)

**Comment by gnome-mpv** [comment]
>  I like this player, but it lacks some basic functions like:
>    - remembering the position on shut-down to resume after restart at this position
>    - open file dialog does not remember the last opened file
>    - option for audio normalization (important for movies where SFX often override voice)
>    - setting size/colors of subtitles

All of these are already possible. I'll add some info about them to the [FAQ](https://github.com/celluloid-player/celluloid/wiki/FAQ) later.

**Comment by gslicer** [comment]
> All of these are already possible. I'll add some info about them to the FAQ later.
This is great, but would it be possible to include such settings directly in the celluloid config instead of importing mpv configs (most users are not familiar with)? Folks dealing with vmp configs probably don't even use GUI players...

**Comment by gnome-mpv** [comment]
>This is great, but would it be possible to include such settings directly in the celluloid config instead of importing mpv configs (most users are not familiar with)?

That could be done, but I have to think about how/what to include a bit.
