### ISSUE TITLE
Closing one window closes other all windows as well

### ISSUE THREAD

**Issue by minamme** [celluloid-player/celluloid#715]
Overview Description:
If I've two or more videos playing in different windows and if I close one of them then all of them get close.

Steps to Reproduce:
1. Open a video
2. Open another video while letting the other one keep playing or pause it.
3. Close either of two 

Actual Results:
All videos will be closed.

Expected Results:
Only the desired one should be closed leaving other open.

Version:
0.21

Additional Information:
Same [issue here](https://forums.linuxmint.com/viewtopic.php?t=354697).

**Comment by gnome-mpv** [comment]
Confirmed. It's actually crashing.

**Comment by gnome-mpv** [comment]
I can no longer reproduce this (tested with GTK 4.6.1 and GLib 2.70.4). Is this still an issue for anyone else?

**Comment by minamme** [comment]
Yes it's still the case but I also have updated my Linux to `Una` to now it happening only when closing by pressing `Q` key.

Open video 1 and then video 2 and now close Video 1 by pressing key `Q`.

**Comment by gnome-mpv** [comment]
>Yes it's still the case but I also have updated my Linux to Una to now it happening only when closing by pressing Q key.

Linux Mint Una still comes with 0.21, so that probably why it's still crashing. I tested the git version in a Mint VM and it's no longer crashing for me.

**Comment by eli-damon** [comment]
I am having this problem with a brand new installation of Linux Mint Cinnamon 21 with Celluloid 0.21 .
