### ISSUE TITLE
Celluloid is crashing hikari wayland compositor.

### ISSUE THREAD

**Issue by ahmadraniri1994** [celluloid-player/celluloid#716]
Overview Description:
When I'm opening celluloid on hikari wayland compositor, it will crash the entire wayland compositor and kick me to tty.

Steps to Reproduce:
1. Compile the latest master (the issue still exist).
2. Rebuild hikari wayland compositor (the issue still exist).
3. Fill issue to Hikari repository and forum (no answer yet)
4. For temporary solution, use GDK_BACKEND=x11 when launch celluloid, but it will unusable when hikari is compiled without Xwayland.

Actual Results:
Celluloid still make hikari crash.

Expected Results:
Celluloid run normally.

Version:
Celluloid 0.22

Additional Information:
OS : Archlinux.
Wlroots : 0.14.1-2
Hikari wayland compositor : 2.3.2
There is a "cuda" complaining but it doesn't matter, since I can open celluloid on other wayland compositor (sway, labwc).
[simple-log.log](https://github.com/celluloid-player/celluloid/files/7645949/simple-log.log)

**Comment by ahmadraniri1994** [comment]
Since celluloid use gtk4,  perhaps. Rebuild with gtk3 (older version) perhaps will solve the issue.

**Comment by ahmadraniri1994** [comment]
Solved by rebuild celluloid (gtk3 version), no more crash when open celluloid on hikari. Thanks 🙏

**Comment by gnome-mpv** [comment]
Might be worth reporting the bug to your compositor. Wayland clients shouldn't be able to crash the compositor.
