### ISSUE TITLE
Cursor auto hides on headerbar (gnome,wayland)

### ISSUE THREAD

**Issue by regern80** [celluloid-player/celluloid#717]
Overview Description: Cursor is hidden after 3-4seconds of idling on the headerbar and also when moving it horizontally on the headerbar after 3-4seconds. This makes clicking on the headerbar buttons hard because once the cursor hides on the headerbar it doesnt appear unless the cursor is moved out of the headerbar.

Steps to Reproduce:
1.run celluloid on Gnome(41.1) Wayland session.
2.place cursor on the headerbar and let it idle for 3-4 seconds,  
or move cursor horizontally on headerbar for more than 3-4 seconds
3.

Actual Results: the cursor is hidden after 3-4seconds of idling on headerbar (the cursor also hides when moving it horizontally on the headerbar after 3-4seconds)

Expected Results: Cursor only hidden when above video but stays visible when on headerbar

Version: 0.22-1

Additional Information: gtk theme:Adwaita

**Comment by gnome-mpv** [comment]
Confirmed. Happens when "automatically hide mouse cursor in windowed mode" is enabled. Fullscreen mode is not affected.
