### ISSUE TITLE
Is there a way to set a default Playback speed?

### ISSUE THREAD

**Issue by 13048** [celluloid-player/celluloid#718]
I am aware that I can change the playback speed using the [ ] { } keyboard shortcuts after opening a file.

I was wondering is there was a way to set a default playback speed value for all opened files

e.g. default playback speed of 1.50 instead of 1.00

i am unclear if this is something i can achieve through Preferences > 'Config Files' etc

thanks for any help you can provide

**Comment by gnome-mpv** [comment]
Yes, you can do that by setting the `speed` property in your config file.

Example:
```
speed=1.5
```
