### ISSUE TITLE
How to remove the Cache info from OSC ?

### ISSUE THREAD

**Issue by dxps** [celluloid-player/celluloid#724]
Dear Celluloid community,

I'm still loving using Celluloid, and I'd like to keep it that way. :blush: 
I have installed ver. 0.22 as flatpak. Recently, I got the updated version installed.

With this update, it seems that some `Cache: __` info is now shown on the OSC.
And I simply don't like to see that, and just have that clean "progress bar" without it.

I looked through [mpv manual](https://mpv.io/manual/stable/), but I couldn't find a related flag to use.

![image](https://user-images.githubusercontent.com/14140226/146816459-bee37499-9e2c-4280-bda4-94e0645a2ebc.png)

I am using the following `Extra mpv options`:
`--osc=yes --script-opts=osc-layout=slimbox,osc-boxalpha=200,osc-seekbarstyle=knob --sub-font-size=28 --sub-font="Fira Sans"`

Any idea how to get rid of it, please?

Thanks!

**Comment by gnome-mpv** [comment]
[`osc.lua`](https://raw.githubusercontent.com/mpv-player/mpv/448fe0226b469df9f8a109a9840afa00bc59b48c/player/lua/osc.lua) doesn't support hiding the cache info, so you'd need to patch it. Add `do return "" end` after line 2083 and the cache info should disappear.

Once you have the patched file, you can load it just like any other Lua scripts. Also, remove `--osc=yes` so that the `osc.lua` that comes with mpv doesn't get loaded.

**Comment by dxps** [comment]
Thanks for the feedback! :pray:  As always, I appreciate the responsiveness. :blush: 

Let me see if I understood correctly:
1. I can do the patch:
    1. Return a blank string - as you rightly mentioned - as the only body of that function (after [line 2018](https://github.com/mpv-player/mpv/blob/87286fe820b9071a64cd1eee38cf728b8adc801a/player/lua/osc.lua#L2083))
    2. Build the `mpv` binary from source
    3. Place that `mpv` binary into `~/.local/share/flatpak/app/io.github.celluloid_player.Celluloid/current/active/files/bin`, replacing the one that comes with the Flatpak installation.
2. I can ask mpv maintainers for such a flag to control the appearance of it.

Removing `--osc=yes` basically "destroys" what I really like about this clean approach: just to have a minimal progress bar with times, and to automatically show and hide based on mouse movement.

**Comment by dxps** [comment]
It's true that having `[x] Use floating controls in windowed mode` shows a "progress bar" that hides after some mouse inactivity, which is nice. So, the alternative would be indeed to stop using/showing OSC.

**Comment by gnome-mpv** [comment]
> I can do the patch:
> 
>     1. Return a blank string - as you rightly mentioned - as the only body of that function (after [line 2018](https://github.com/mpv-player/mpv/blob/87286fe820b9071a64cd1eee38cf728b8adc801a/player/lua/osc.lua#L2083))
> 
>     2. Build the `mpv` binary from source
> 
>     3. Place that `mpv` binary into `~/.local/share/flatpak/app/io.github.celluloid_player.Celluloid/current/active/files/bin`, replacing the one that comes with the Flatpak installation.

You don't need to rebuild mpv from source. What I suggested is just patching `osc.lua` and loading it at run time. More precisely:

1. Download [`osc.lua`](https://raw.githubusercontent.com/mpv-player/mpv/448fe0226b469df9f8a109a9840afa00bc59b48c/player/lua/osc.lua).
2. Add `do return "" end` after line 2083 using a text editor of your choice.
3. Launch Celluloid and open the preferences dialog.
4. Navigate to the Plugins tab and click the `+` button.
5. Open the `osc.lua` you just patched.
6. Navigate to the Miscellaneous tab and remove `--osc=yes` from `Extra mpv options`.
7. Press Save.

**Comment by dxps** [comment]
Gotcha! Thanks a lot again! :+1:

**Comment by gnome-mpv** [comment]
>Probably a bug, but to use the mouse for seeking within the clip, the cursor must be placed somewhere above the "bar" in a vertical "range" when the current spent time gets displayed, as shown in the screenshot.

Fixed in a9e85ba1b66fb0904fa09640bdfdc4a0ac255897.

**Comment by dxps** [comment]
Perfect & thank you, @gnome-mpv!
As there are no milestones defined, are you planning to release an updated version that includes this fix soon?

**Comment by gnome-mpv** [comment]
> As there are no milestones defined, are you planning to release an updated version that includes this fix soon?

I plan to make a release once all the major bugs are fixed, hopefully in 1-2 months.
