### ISSUE TITLE
Celluloid freezes when `--write-automatic-subs` is passed to yt-dlp config

### ISSUE THREAD

**Issue by bbhtt** [celluloid-player/celluloid#726]
## Overview Description

Celluloid seems to freeze with no video (only audio is playing) while playing a YouTube video when `--write-automatic-subs` is passed to yt-dlp while mpv seems to work fine. If `--write-automatic-subs` is removed from config, Celluloid works fine again. Celluloid, MPV is on default config, no scripts used, yt-dlp has `--write-automatic-subs` passed.

## Steps to Reproduce

1. Create `~/.config/yt-dlp/config` and add `--write-automatic-subs` or `--write-auto-subs` to it as per https://github.com/yt-dlp/yt-dlp#subtitle-options or do `$ celluloid --mpv-ytdl-raw-options=write-auto-subs= https://www.youtube.com/watch?v=rJ48-SYY1sQ`
2. Play a video: `$ celluloid https://www.youtube.com/watch?v=rJ48-SYY1sQ`
3. Only audio is playing no video and freezes shortly.

## Actual Results

No video, freezes.

## Expected Results

Both audio and video, not freezing. 

## Version

Celluloid 0.22

## Additional Information

Not sure how useful these are (all logs taken with `--write-automatic-subs` in yt-dlp) 

Output with `G_MESSAGES_DEBUG=all` [g_debug.txt](https://github.com/celluloid-player/celluloid/files/7780766/g_debug.txt)
Running with `$ celluloid --mpv-log-file=mpv.txt`  [mpv.txt](https://github.com/celluloid-player/celluloid/files/7780765/mpv.txt)

Running only `$ mpv --no-config --log-file=mpv-only.txt https://www.youtube.com/watch?v=rJ48-SYY1sQ` [mpv-only.txt](https://github.com/celluloid-player/celluloid/files/7780787/mpv-only.txt) [Video plays fine in this case]

System. Arch Linux
yt-dlp: 2021.12.25

**Comment by gnome-mpv** [comment]
I'm no longer able to reproduce this with both v0.22 and the git version. Tested with yt-dlp 2022.02.04 and mpv 0.34.0.

Feel free to reopen if this is still an issue for you.
