### ISSUE TITLE
Removing the last item from the playlist starts the (new) last item playing

### ISSUE THREAD

**Issue by smithfred** [celluloid-player/celluloid#735]
Overview Description:

Steps to Reproduce:
1. Open/create a playlist of files.
2. Start playing any item except the last two.
3. Remove the last item.

Actual Results:

(New) last item starts playing.

Expected Results:

Already playing item keeps playing.

Version:

0.22

Additional Information:

Only happens when last item is removed, not when any of the others are.

**Comment by gnome-mpv** [comment]
Confirmed.
