### ISSUE TITLE
Double-clicking current playlist item should start playing it again from the beginning

### ISSUE THREAD

**Issue by smithfred** [celluloid-player/celluloid#736]
Overview Description:

Steps to Reproduce:
1. Open/create a playlist.
2. Start playing any item.
3. Double-click the same item in the playlist.

Actual Results:

Nothing.

Expected Results:

Item starts playing again from the beginning.

Version:

0.22.

Additional Information:

**Comment by gnome-mpv** [comment]
Confirmed.
