### ISSUE TITLE
Quit Celluloid with Ctrl+Q keys causes crash

### ISSUE THREAD

**Issue by shimsa** [celluloid-player/celluloid#741]
**Overview Description**: When quit Celluloid with X button, then OK, but when quit Celluloid with Ctrl+Q keys, then quit with crash.

**Steps to Reproduce**:
1. Open Celluloid with or without video playing
2. Quit Celluloid with Ctrl+Q keys

**Actual Results**:
Celluloid crash

**Expected Results**:
Celluloid close correctly without crash

**Version**:
0.22

**Additional Information**:
Fedora 35 Workstation
Wayland
Celluloid Flathub version

**Comment by gnome-mpv** [comment]
Confirmed. For some reason, this only happens with Flatpak.
