### ISSUE TITLE
Drag the window by video area and hide the window title bar

### ISSUE THREAD

**Issue by HubKing** [celluloid-player/celluloid#755]
Overview Description: Feature request: Ability to drag the window by the video area and hide the UI showing only the video.

Additional Information: I have tested Celluloid on the latest Gnome Manjaro, and dragging on the video area did not work unlike the MPV Player app.

Many popular Korean video players allow the user to drag the window by the video area, just like MPV Player.  Most of them also have an option to hide the UI when a video is playing and the mouse is not above the video (for example, on PotPlayer, Preferences -> General -> Skins -> Auto hide main window skin while video screen is active). This is very useful on a laptop screen, because it does not waste any screen space for the UI. As far as I know, there is no Linux video player that can do this, so I hope this feature would be added.

Reference: Screen recording of PotPlayer. In this video, I started it and drag-and-dropped a video file on it. Then, I dragged the window by the video area. Notice that the top/bottom UI only appears when I place the mouse pointer over it, thus saving the screen space.
 
https://user-images.githubusercontent.com/10900489/157838014-e004ff54-768c-4258-8d4c-9f79fe852fb0.mp4

**Comment by gnome-mpv** [comment]
> Ability to drag the window by the video area and hide the UI showing only the video.

Thank you for your suggestions. These are already being included in the [redesign](https://github.com/celluloid-player/celluloid/issues/696).
