### ISSUE TITLE
"Use skip buttons for controlling playlist" has no effect in windowed mode

### ISSUE THREAD

**Issue by Silejonu** [celluloid-player/celluloid#757]
#### Overview Description:
Checking "Use skip buttons for controlling playlist" in the preferences only affects fullscreen mode, not windowed mode.

#### Steps to Reproduce:
1. Open Celluloid in windowed mode
2. Check "Use skip buttons for controlling playlist" in the preferences

#### Actual Results:
The "Previous Chapter" and "Next Chapter" buttons do not show up.
They show up in fullscreen mode, however.

#### Expected Results:
The "Previous Chapter" and "Next Chapter" buttons should show up in both windowed mode and fullscreen mode.

#### Version:
0.23 (this issue was already present in 0.22, and I believe in 0.21 as well, maybe even earlier)

#### Additional Information:
OS: Arch Linux
DE: GNOME on Wayland
Package installed from the Arch `community` repo

**Comment by gnome-mpv** [comment]
Confirmed.
