### ISSUE TITLE
Clicking the Maximise button hides the three window control buttons.

### ISSUE THREAD

**Issue by HubKing** [celluloid-player/celluloid#761]
Overview Description: The buttons disappear, if I click the maximise button. I tried the same thing with gedit which has almost identical layout, and it did not hide the three buttons.

Steps to Reproduce:
1. Click the maximise button
2.
3.

Actual Results:
Three buttons are gone.

Expected Results:
Three buttons are there.

Version: 0.22

Additional Information:

https://user-images.githubusercontent.com/10900489/159166380-3861c21d-8fef-490c-a83d-c1962ab855d8.mp4

PS: It was happening, and for some reason, now it does not happen. I have not figured out the condition that makes this happen. I will add it, if I find it.

**Comment by gnome-mpv** [comment]
I'm unable to reproduce both this and #760 in my Manjaro VM, but I think they are related based on your videos.

In both cases, it looks like Celluloid entered a weird hybrid state between being maximized and fullscreened. In this issue's video, the header bar looks like it's in fullscreen mode but everything else is in normal/maximized mode. In #760, it looks like the opposite is happening.

**Comment by gnome-mpv** [comment]
Can you check if the bugs are still reproducible with the latest git version?

**Comment by HubKing** [comment]
#760 happens often (like if I try opening/closing 2 or 3 videos and switch resize/maximise/full-screen mode a few times, but I have not figured out the exact procedure that triggers this), but I have not seen this happening for a few hours since opening this issue. If it does not happen again for a while, I will close this issue.

For what it is worth, three extensions were active: Custom Hot Corners - Extended, Dash to Panel, and Night Theme Switcher. All installed from the Gnome Extensions web site.

> Can you check if the bugs are still reproducible with the latest git version?

The version I am using was installed with the Add/Remove Software GUI from the Official Repository. I will uninstall it and install the "...-git" version from AUR, and append the result in one or two days.

**Comment by HubKing** [comment]
I could immediately reproduce #760 with the 2.23 git version.

**Comment by HubKing** [comment]
It happens with 0.23, but I guess it is probably because of the Unite extension. It happened with extensions disabled, but I had not restarted the desktop, so maybe the effect was still there.
