### ISSUE TITLE
Celluloid v23 still using the old UI

### ISSUE THREAD

**Issue by rashidi77** [celluloid-player/celluloid#766]
Overview Description:
I am using the Celluloid Flatpak app from flathub. It seems Celluloid got an update last month and should have a new theme (like Libadwaita apps). But mine is still using the old Adwaita theme. 

Steps to Reproduce:
1. Install Celluloid v23 from flathub
2. Open the app

Actual Results:
The app still using the old Adwaita theme.

Expected Results:
The app should have a new theme like the screenshots on Github and Flathub.

Version:
23

Additional Information:
Platform : Fedora Silverblue 36 (Gnome 42)

**Comment by gnome-mpv** [comment]
`libadwaita` is not in v0.23. It was added *after* the release.

**Comment by rashidi77** [comment]
> `libadwaita` is not in v0.23. It was added _after_ the release.

The screenshots in Flathub made me think it's currently using Libadwaita.
