### ISSUE TITLE
Cursor doesn't auto hide in full screen

### ISSUE THREAD

**Issue by paulaime** [celluloid-player/celluloid#767]
Overview Description:

I'm using Celluloid 0.22 on Fedora 35 + KDE 5.24.3. When playing a video file (MKV), the cursor doesn't auto hide in full screen.
Here are the following parameters I have in my mpv.conf:
You can see I have cursor-autohide=1000 and cursor-autohide-fs-only. I've tried with and without these parameters, but nothing changes, and the cursor is always visible in full screen mode.

Is it an issue with Celluloid, or with KDE, Wayland or Fedora?

gpu-context=wayland
osd-level=0
hr-seek=yes
save-position-on-quit
volume=100
volume-max=200
ontop=yes
hwdec=auto
border=yes
geometry=50%:50%
af-add='dynaudnorm=g=5:f=250:r=0.9:p=0.5'
audio-normalize-downmix=yes
alang=fr,en
slang=fr,en
stop-screensaver=yes
user-agent = "Mozilla/5.0"
cursor-autohide-fs-only
cursor-autohide=1000
fs-black-out-screens

Steps to Reproduce:
1. Launch Celluloid
2. Enter full screen

Actual Results:

The cursor is always visible.

Expected Results:

The cursor should auto hide aftr 1 second.

Version:

0.22

Additional Information:

Using Fedora 35 with KDE 5.24.3 / Wayland

**Comment by gnome-mpv** [comment]
Can you check if this patch fixes the problem?

````patch
From 8f093b172a60614c52ce79a27d2636e36984b4e6 Mon Sep 17 00:00:00 2001          
From: gnome-mpv <gnome-mpv@nowhere>                                             
Date: Sun, 10 Apr 2022 16:24:10 +0700                                           
Subject: [PATCH] Use GdkPixbuf to create transparent texture for cursor hiding  
                                                                                
---                                                                             
 src/celluloid-video-area.c | 11 ++++++++++-                                    
 1 file changed, 10 insertions(+), 1 deletion(-)                                
                                                                                
diff --git a/src/celluloid-video-area.c b/src/celluloid-video-area.c            
index 294e35d..a3aedac 100644                                                   
--- a/src/celluloid-video-area.c                                                
+++ b/src/celluloid-video-area.c                                                
@@ -182,7 +182,16 @@ set_cursor_visible(CelluloidVideoArea *area, gboolean visible)
        }                                                                       
        else                                                                    
        {                                                                       
-               cursor = gdk_cursor_new_from_name("none", NULL);                
+               GdkPixbuf *pixbuf =                                             
+                       gdk_pixbuf_new                                          
+                       (GDK_COLORSPACE_RGB, TRUE, 8, 1, 1);                    
+               gdk_pixbuf_fill(pixbuf, 0x00000000);                            
+                                                                               
+               GdkTexture *texture = gdk_texture_new_for_pixbuf(pixbuf);       
+               cursor = gdk_cursor_new_from_texture(texture, 0, 0, NULL);      
+                                                                               
+               g_object_unref(texture);                                        
+               g_object_unref(pixbuf);                                         
        }                                                                       
                                                                                
        gdk_surface_set_cursor(surface, cursor);                                
--                                                                              
2.35.1                                                                          
````

**Comment by paulaime** [comment]
Thanks. How can I apply this patch?

**Comment by gnome-mpv** [comment]
>Thanks. How can I apply this patch?

Clone the Celluloid repo, copy/paste the patch into a file, then run `git am --ignore-space-change --ignore-whitespace FILENAME.patch`.

After that, run `meson build && ninja -C build` to build. When the build finishes, you can run `build/src/celluloid` to start Celluloid.

**Comment by lsp432** [comment]
I'm not sure if it's appropriate to add to this, open a new issue, etc, but I've been having this same issue (cursor won't autohide) running latest git on Arch + KDE Plasma 5.26.0 (i915, Wayland).

Getting 'git am' to work is beyond me, but applying the contents of the patch manually, I can confirm that Celluloid still builds, runs, and the cursor now autohides after 1 second in fullscreen, and also respects the "hide in windowed mode" setting. 

Assuming it doesn't break anything else, can we get this patch committed?

**Comment by gnome-mpv** [comment]
Thanks for confirming. The patch is now in the master branch.
