### ISSUE TITLE
mpv `on_load` hook doesn't seem to be triggered?

### ISSUE THREAD

**Issue by teohhanhui** [celluloid-player/celluloid#770]
Overview Description: mpv `on_load` hook doesn't seem to be triggered

Steps to Reproduce:
1. Add [fuzzydir.lua] to `$XDG_CONFIG_HOME/celluloid/scripts`
2. Set `sub-file-paths=**` in the config file, e.g. `$XDG_CONFIG_HOME/celluloid/mpv.conf`
3. Run Celluloid specifying a file to load

Actual Results: `sub-file-paths` value is still `**`

Expected Results: `sub-file-paths` value should be expanded into subdirectories of working directory by [fuzzydir.lua] script

Version: 0.23

Additional Information:

The same script works in mpv.

I've tried just doing:

```lua
local mp = require "mp"
local msg = require "mp.msg"

msg.trace("A: script init")

mp.add_hook("on_load", 50, function()
    msg.trace("B: on_load")
end)

mp.add_hook("on_preloaded", 50, function()
    msg.trace("C: on_preloaded")
end)
```

with

`celluloid --mpv-msg-level='all=trace' /path/to/video.mkv > /tmp/celluloid.log  2>&1`

but only messages A and C are printed. Message B is not printed.

[fuzzydir.lua]: https://github.com/sibwaf/mpv-scripts/blob/bccda6d1560e9c33c8a7c2634edac41d06f49bb8/fuzzydir.lua

**Comment by gnome-mpv** [comment]
Confirmed. Looks like the script was loaded a bit too late. It works fine if you open the file after launching Celluloid.
