### ISSUE TITLE
Support for Gnome 42 Dark Style Preference

### ISSUE THREAD

**Issue by fsabr** [celluloid-player/celluloid#776]
The global dark style preference in GNOME 42 is amazing. See [Gnome 42 Release](https://release.gnome.org/42/) and a [Gnome wiki article](https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference)

Unfortunately, it doesn't seem to be working for Celluloid. Are there any plans to support it?
It works for the default video player [Totem](https://gitlab.gnome.org/GNOME/totem). I'd rather keep using this :)

Version:
I'm using Celluloid 0.23 on Fedora 36 with GNOME 42.

**Comment by gnome-mpv** [comment]
It's already supported in git master. It'll be in the next release.

**Comment by gnome-mpv** [comment]
[v0.24](https://github.com/celluloid-player/celluloid/releases/tag/v0.24)
