### ISSUE TITLE
Playlist retains keyboard focus even after clicking video region

### ISSUE THREAD

**Issue by smithfred** [celluloid-player/celluloid#784]
Overview Description:

After clicking in the playlist (e.g. to select a playlist item), up/down arrows continue to navigate the playlist items, even after clicking the video area.

This prevents use of the up/down arrows for long seeks.

Fullscreening/exiting fullscreen moves the focus back to the video area properly, fixing this.

Steps to Reproduce:
1. Open the playlist, and add items to it.
2. Double-click an item to play it.
3. Click on the video area.
4. Press the up or down arrow on the keyboard.

Actual Results:

Highlight moves up/down in the playlist.

Expected Results:

Currently playing item long seeks forwards/backwards.

Version:

0.23

Additional Information:

**Comment by smithfred** [comment]
Also does really weird things with <Space> for playing/pausing - try pressinge <Space> a few times after clicking on the current track or another track in the playlist. Again, fullscreening/exiting fullscreen fixes that.

**Comment by famichiki** [comment]
> Also does really weird things with for playing/pausing - try pressinge a few times after clicking on the current track or another track in the playlist. Again, fullscreening/exiting fullscreen fixes that.

This seems related to the issue with the space bar changing from toggling play/pause when the media area is active, or selecting a track when the playlist area is active. It's also odd in that currently it selects the track, but then kind of cycles between playing that track from the start or doing nothing each time you press it.

I can't find anyway to disable to space bar keyboard shortcut for selecting items in the playlist, is this user configurable? 

Ideally the space bar should always act as a play/pause button and only either the mouse or enter key be used to select tracks in the playlist.
