### ISSUE TITLE
Playlist takes more space everytime when it opens a new video

### ISSUE THREAD

**Issue by tahir-asadov** [celluloid-player/celluloid#788]
Overview Description: If I show playlist and then close the media player and open a new file video playlist takes more space then previous time.

Steps to Reproduce:
1.Open a video.
2. Press F9 to show playlist
3. Close the Celluloid
4. Open a new video

Actual Results:
Playlist take more space than before

Expected Results:
Playlist should take same space as before

Version: 0.20

Additional Information:
https://i.imgur.com/X4mWnhn.png
https://i.imgur.com/LtGYSw3.png

**Comment by gnome-mpv** [comment]
Can you check if this is still reproducible with v0.23?

**Comment by tahir-asadov** [comment]
No. I test 0.23 flatpak. And I didn't see the same issue.

Thanks.
