### ISSUE TITLE
Search in playlist does nothing (flatpak)

### ISSUE THREAD

**Issue by gordebak** [celluloid-player/celluloid#795]
Overview Description:
I have some pretty long m3u playlists, and being able to search in them would be nice. But in the flatpak version, search function doesn't work.

Steps to Reproduce:
1. Load a playlist
2. Press Ctrl F and search box appears
3. Type something in the box and press Enter

Actual Results:
Nothing happens.

Expected Results:
To find the search query.

Version:
0.23 flatpak on Ubuntu 22.04
Additional Information:

**Comment by gnome-mpv** [comment]
Confirmed.
