### ISSUE TITLE
Audio delay keyboard shortcut is wrong

### ISSUE THREAD

**Issue by iliqiliev** [celluloid-player/celluloid#801]
It says **ctrl +** / **ctrl -** to adjust but is actually **ctrl shift +** / **ctrl -**
![image](https://user-images.githubusercontent.com/25604760/187047192-98c21de1-2e41-4ca1-ba46-3faa932ac4a9.png)

Pretty self explanatory 

Version: 0.23 on arch cinnamon

**Comment by gnome-mpv** [comment]
`Ctrl` + `+` is already correct. On the US layout, `+` is on the same button as `=`, so you have to press `Shift` to get `+`, but this isn't necessarily true for all layouts.

**Comment by iliqiliev** [comment]
Thank you
