### ISSUE TITLE
Translation of the io.github.celluloid_player.Celluloid.desktop file

### ISSUE THREAD

**Issue by marcelocripe** [celluloid-player/celluloid#803]
Hello dear developers.

In addition to the graphical interface being translated, could we have the file "io.github.celluloid_player.Celluloid.desktop" with these translations?

Can we add "Audio" to the category entry of the file "io.github.celluloid_player.Celluloid.desktop"?

I appreciate you creating, maintaining and updating WinFF.

Thank you very much.

marcelocripe
(Original text in Brazilian Portuguese)

Note: Please remove the .txt from the .desktop filename.

[io.github.celluloid_player.Celluloid.desktop.txt](https://github.com/celluloid-player/celluloid/files/9479906/io.github.celluloid_player.Celluloid.desktop.txt)

- - - - -

Olá caros desenvolvedores.

Além da interface gráfica ser traduzida, poderíamos ter o arquivo "io.github.celluloid_player.Celluloid.desktop" com estas traduções?

Podemos adicionar "Audio" a entrada categoria do arquivo "io.github.celluloid_player.Celluloid.desktop"?

Eu agradeço por você criar, manter e atualizar o WinFF.

Muito obrigado.

marcelocripe
(Texto original em idioma Português do Brasil) 

Obs.: Por favor, remova o .txt do nome do arquivo .desktop.

[io.github.celluloid_player.Celluloid.desktop.txt](https://github.com/celluloid-player/celluloid/files/9479906/io.github.celluloid_player.Celluloid.desktop.txt)

**Comment by gnome-mpv** [comment]
> In addition to the graphical interface being translated, could we have the file "io.github.celluloid_player.Celluloid.desktop" with these translations?

Translations are already being included at build time.

> Can we add "Audio" to the category entry of the file "io.github.celluloid_player.Celluloid.desktop"?

Done.

> Note: Please remove the .txt from the .desktop filename.

The build/install script doesn't install any txt files. If you see one instead of a regular desktop file, there might be a problem with your distro's package.

**Comment by marcelocripe** [comment]
Hello gnome-mpv.

"The build/install script doesn't install any txt files. If you see one instead of a regular desktop file, there might be a problem with your distro's package."
What I meant, which is for you to remove the ".txt" extension from the "io.github.celluloid_player.Celluloid.desktop" file that I attached in the previous message, as it is actually one of the .desktop file and GitHub does not allow attaching a .desktop file. The "io.github.celluloid_player.Celluloid.desktop" file has the translation of several languages ​​that are not in the .desktop file that I found in antiX Linux 21 (Debian 11). The antiX community has been working to get the translation of several .desktop files and Celluloid is one of those with few languages ​​translated.

"Translations are already being included at build time."
How can the texts be the same as the file "io.github.celluloid_player.Celluloid.desktop" that I attached in the previous message? For languages ​​that have been reviewed by humans native to the languages: de, fr, fr_BE, it, pt and pt_BR. The other languages ​​that were added in the "io.github.celluloid_player.Celluloid.desktop" file are from automatic translations from internet services.

Thanks for adding "Audio" to the category entry of the "io.github.celluloid_player.Celluloid.desktop" file, this is important information that was not present in the original "io.github.celluloid_player.Celluloid.desktop" file.

Thank you very much.

- - - - -

Olá gnome-mpv.

"The build/install script doesn't install any txt files. If you see one instead of a regular desktop file, there might be a problem with your distro's package."
O que eu quis dizer, que é para você remover a extensão ".txt" do arquivo "io.github.celluloid_player.Celluloid.desktop" que eu anexei na mensagem anterior, pois na verdade ele é um do arquivo .desktop e o GitHub nã permite anexar um arquivo .desktop. O "io.github.celluloid_player.Celluloid.desktop" arquivo possui a tradução de vários idiomas que não estão no arquivo .desktop que eu encontrei no antiX Linux 21 (Debian 11). A comunidade antiX vem trabalhando para obter a tradução de vários arquivos .desktop e no cado o Celluloid é um dos que estão com poucos idiomas traduzidos.

"Translations are already being included at build time."
Como os textos podem ficar iguais do arquivo "io.github.celluloid_player.Celluloid.desktop" que eu anexei na mensagem anterior? Para os idiomas que foram revisados por seres humanos nativos dos idiomas: de, fr, fr_BE, it, pt e pt_BR. Os outros idiomas que foram adicionados no arquivo "io.github.celluloid_player.Celluloid.desktop" são de traduções automáticas dos serviços da internet.

Obrigado por adicionar "Audio" a entrada categoria do arquivo "io.github.celluloid_player.Celluloid.desktop", esta é uma informação importante que não estava presente no arquivo "io.github.celluloid_player.Celluloid.desktop" original.

Muito obrigado.

**Comment by gnome-mpv** [comment]
>What I meant, which is for you to remove the ".txt" extension from the "io.github.celluloid_player.Celluloid.desktop" file that I attached in the previous message, as it is actually one of the .desktop file and GitHub does not allow attaching a .desktop file. The "io.github.celluloid_player.Celluloid.desktop" file has the translation of several languages ​​that are not in the .desktop file that I found in antiX Linux 21 (Debian 11). The antiX community has been working to get the translation of several .desktop files and Celluloid is one of those with few languages ​​translated. Please check out the .desktop file I sent you.

I see. I checked our Weblate, and it looks like our de, fr, it, and pt_BR already include all the translations in your desktop file.

We don't currently have fr_BE, but I think users who use this language code should automatically see fr as fallback. The fr_BE translations in your desktop file match our fr translations exactly, so I don't think there's a reason to add fr_BE yet.

We don't have pt, but we do have pt_PT. Do you know if they are supposed to be different?

I decided not to include automatic translations since I have no way to verify that they're correct.

**Comment by marcelocripe** [comment]
"I see. I checked our Weblate, and it looks like our de, fr, it, and pt_BR already include all the translations in your desktop file."
The pt_BR entries were revised by me and all the texts are different from the original. I was able to describe in much more detail the entries "Name[pt_BR]=", "GenericName[pt_BR]=", "Comment[pt_BR]=", "Name[pt_BR]=" of "[Desktop Action new-window]" , I also included details in the entry "Keywords[pt_BR]=".

"We don't currently have fr_BE, but I think users who use this language code should automatically see fr as fallback."
Wallon is the native translator for the "fr_BE" language and helps with the "fr" language due to the absence of a voluntary native "fr" translator. You can see some of Wallon's participation in this thread:
https://www.antixforum.com/forums/topic/antix-and-antix-application-program-translation-platforms/#post-70426
https://forum.mxlinux.org/viewtopic.php?t=63237
In the antiX forum thread you will also see the Italian and German translators.
If it is possible to add fr_BE, it will be useful for operating systems that when there is no entry in the .desktop file of the respective 4-letter language or more, it does not display the 2-letter language and starts to display the English language (which is totally inconsistent, but unfortunately there are such cases).

"We don't have pt, but we do have pt_PT. Do you know if they are supposed to be different?"
R: Yes, it is extremely important to include the language "pt", despite being spoken the same Portuguese language, there is an ocean between the two countries (Portugal and Brazil), the orthographic norms are different, the understanding and meaning of words change significantly and each of the languages ​​developed differently. It has another very important detail, when there is no entry in the .desktop file of the respective 4-letter language or more, it displays the 2-letter language, if the 2-letter language does not exist, it displays the English language. This is the case for users who start antiX in the pt language, as there is no pt entry in the .desktop file, the language displayed will be English. The analysis of the language identifier occurs from the largest number of letters in the identifier of [language_country] to the smallest number of letters in the identifier of [language], the reverse does not happen (as far as I was able to understand and test).

"I decided not to include automatic translations since I have no way to verify that they're correct."
Okay, it's up to you to use automatic translations or not. The objective of the voluntary translators of the antiX community is to bring communication to the greatest possible number of people on planet Earth, in this way GNU/Linux will reach a much greater number of people, even if it is through automatic translations. Our hope is that other people will do the necessary revision and corrections to the machine translations we are using until more people become voluntary translators of their respective languages.

Please include in your .desktop file the entries of the languages ​​that do not exist, the texts that are different from your .desktop file in relation to the file I sent you, at least for the languages ​​"de", "fr_BE", "it ", "pt", "pt_BR" (these languages ​​I'm sure have been proofread by humans).

Thank you very much.

- - - - -

"I see. I checked our Weblate, and it looks like our de, fr, it, and pt_BR already include all the translations in your desktop file."
As entradas pt_BR foram eu que revisei e todas os textos estão diferentes do original. Eu consegui descrever com muito mais detalhes as entradas "Name[pt_BR]=", "GenericName[pt_BR]=", "Comment[pt_BR]=", "Name[pt_BR]=" de "[Desktop Action new-window]", eu incluí ainda detalhes na entrada "Keywords[pt_BR]=".

"We don't currently have fr_BE, but I think users who use this language code should automatically see fr as fallback."
O Wallon é o tradutor nativo do idioma "fr_BE" e ajuda com o idioma "fr" devido a ausência de um tradutor voluntário nativo do "fr". Você pode ver algumas das participações do Wallon neste tópicos:
https://www.antixforum.com/forums/topic/antix-and-antix-application-program-translation-platforms/#post-70426
https://forum.mxlinux.org/viewtopic.php?t=63237
No tópico do fórum do antiX você verá também os tradutores italianos e alemão.
Se for possível adicionar o fr_BE, será útil para os sistemas operacionais que quando não existe a entrada no arquivo .desktop do respectivo idioma de 4 letras ou mais, não exibe o idioma de 2 letras e passa a exibir o idioma Inglês (o que é totalmente inconsistente, mas infelizmente existem casos assim).

"We don't have pt, but we do have pt_PT. Do you know if they are supposed to be different?"
R: Sim extremamente importante a inclusão do idioma "pt", apesar de ser falado o mesmo idioma Português, existe um oceano entre os dois países (Portugal e Brasil), as normas ortográficas são diferentes, a compreensão e o sentido das palavras mudam significativamente e cada um dos idiomas se desenvolveram de forma diferente. Tem um outro detalhes muito importante, quando não existe a entrada no arquivo .desktop do respectivo idioma de 4 letras ou mais, exibe o idioma de 2 letras, se idioma de 2 letras não existir, passa a exibir o idioma Inglês. Este é o caso dos usuários que iniciam o antiX em idioma pt, como não existe a entrada pt no arquivo .desktop, o idioma que é exibido será o Inglês. A análise do identificador do idioma ocorre da quantidade maior de letras no identificador do [idioma_país] para a quantidade menor de letras no identificador do [idioma], o inverso não acontece (até onde eu consegui compreender e testar).

"I decided not to include automatic translations since I have no way to verify that they're correct."
Tudo bem, fica a seu critério utilizar ou não as traduções automáticas. O objetivo do tradutores voluntários da comunidade antiX é de levar a comunicação ao maior número possível de pessoas do planeta Terra, desta forma o GNU/Linux chegará a um número muito maior de pessoas, mesmo que seja por meio das traduções automáticas. A nossa esperança é que outras pessoas farão a revisão e correções necessárias das traduções automáticas que estamos utilizando até que mais pessoas se tornem tradutores voluntários dos seus respectivos idiomas.

Por favor, inclua no seu arquivo .desktop as entradas dos idiomas que não existem, os textos que estão diferentes do seu arquivo .desktop em relação ao arquivo que eu te enviei, ao menos dos idiomas "de", "fr_BE", "it", "pt", "pt_BR" (estes idiomas eu tenho certeza que foram revisados por seres humanos).

Muito obrigado.

**Comment by gnome-mpv** [comment]
Thank you for taking the time to submit the translations, but I won't be able to merge them at this time.

The `it` translation matches what we already have exactly so there's nothing to change. The `de` translation also matches, except that "Celluloid" is translated to "Zelluloid", but it probably shouldn't be since "Celluloid" here is the application name here.

The `fr_BE` translation matches existing `fr` translation exactly, and since `fr_BE` users already will see the `fr` translation as a fallback (I checked), there's no reason to add `fr_BE` yet.

The `pt` translation is different from our existing `pt_PT` translation (both of these refer to Portuguese as spoken in Portugal), but word usage in the `pt` translation seem to deviate from what I found in other similar projects. For example, "Play movies and videos" in the `pt` translation is translated to "Ver vídeos e filmes" while the existing the `pt_PT` translation translates it to "Reproduzir filmes e vídeos". In [Totem](https://gitlab.gnome.org/GNOME/totem),  "Play movies" is translated to "Reproduzir filmes". It isn't clear to me which of these is correct, so I'm not comfortable overwriting the existing `pt_PT` translation.

The new `pt_BR` translation changed the generic name from "Tocador Multimídia" to "Reprodutor ou Tocador de Multimídia Celluloid", but "Celluloid" is non-generic so I think the original version is correct here. Likewise, the name "Celluloid" was changed to "Reprodutor de Multimídia Celluloid", but just the application name should be used here.

**Comment by marcelocripe** [comment]
I already found .desktop files with the entries "pt" and "pt_PT", the same goes for the folders "/usr/share/locale/pt/LC_MESSAGES" and "/usr/share/locale/pt_PT/LC_MESSAGES". On some operating systems, the language selection occurs as follows, the user chooses "Portuguese" and then indicates the country Portugal = "PT" or Brazil = "BR", I do not believe it is a problem to have both "pt" entries " and "pt_PT". As I'm not sure about this, we would need an opinion from someone else who knows more about this subject.

"The new pt_BR translation changed the generic name from "Tocador Multimídia" to "Reprodutor ou Tocador de Multimídia Celluloid", but "Celluloid" is non-generic so I think the original version is correct here. Likewise, the name "Celluloid" was changed to "Reprodutor de Multimídia Celluloid", but just the application name should be used here."
About me using this "Reprodutor de Multimídia Celluloid" model, it's the same model I found from another Brazilian volunteer translator. I don't know this person's name, but he did an excellent job on Thunderbird. In the .desktop file, the pt_BR entry looks like this: "Name[pt_BR]=Cliente de E-mail Thunderbird".
People are not required to know what is or what does "Thunderbird", "CherryTree", "Celluloid", "MPV", "Connman UI Setup", "Feh", etc. At least in my language, the information of what it is or what it is for in front of the name is the natural order for us. It doesn't matter the name in English that comes after it, it doesn't matter if it's "Cliente de E-mail Thunderbird" or "Cliente de E-mail Claws Mail", because the translation of the name doesn't make any sense to what the program proposes to to do. Since when I saw this model, I started to ask in Brazilian user groups on social networks (WhatsApp, Telegram, Matrix, Facebook, etc.) whether they like this model or not, I received support from the majority of users of various GNU/ Linux, including MX Linux, Trisquel, Arch Linux, antiX, PCLinuxOS BR, etc.
I hope you will use the texts I sent you from my language, my goal is to make the menus fully understandable according to the "Thunderbird" example, that is, as follows:

Name=Thunderbird
Name[pt_BR]=Cliente de E-mail Thunderbird

Name=Celluloid
Name[pt_BR]=Reprodutor de Multimídia Celluloid

Name=Connman UI Setup
Name[pt_BR]=Gerenciador de Conexões de Rede CMST ConnMan

It doesn't matter how big the text is, what matters is that all Brazilians will be able to easily understand which program is "E-mail Client", "Multimedia Player" and "Network Connection Manager", note that the name has been kept, but the information will be understood by everyone who speaks my language and in any part of Brazil.

About the entry "GenericName[pt_BR]=Reprodutor ou Tocador de Multimídia Celluloid", the words "Reprodutor" e "Tocador" are different forms used in Brazil (in English there is no difference, but in my language, the two forms are the most used.). In some operating systems, when the cursor is stopped over the menu, the texts of the entry "GenericName[pt_BR]" or of the entry "Comment[pt_BR]=" are displayed.
On second thought, the text of the entry "Comment[pt_BR]=", I should have included the word "audio", being like this: "Comment[pt_BR]=Reproduz filmes, vídeos e áudio".

They say a picture says more than a thousand words, so I'll give you an example:

"Textos dos Menus em pt-BR (1).png" - To be translated/adapted to pt-BR: "Ceni", "Claws Mail", "Dillo", "Firefox ESR", "gFTP", "GNOME PPP", "HexChat" e "Links2". The others are duly translated or adapted to pt-BR.
"Textos dos Menus em pt-BR (2).png" - Exemplifies the "ideal condition", since any Brazilian who can read will be able to understand each of the menus. All these menus are being distributed in antiX updates (my thanks to the creator of antiX for their trust in me).
"Menu Texts in pt-BR (3).png" - The first three menus at the top are perfect. The three menus that are at the bottom, nobody knows what it is, the user has to search the internet or read manuals to find out what is "Gtkam", "Draw" ou "Mirage". Nobody knows what it is.
"Textos dos Menus em pt-BR (4).png" - The same goes for these menus that are in English, nobody knows what "Asunder CD Riper", "Celluloid", "GUVCView", "MPV Media Player" is (it's in English and should be in pt-BR), "SMTUbe", etc.

Does the text template of "MPV Media Player" serve as a comparison for Celluloid?

The translation of "MPV Media Player" will be "Reprodutor de Multimídia MPV", just like the model I want it to be for Celluloid.

I could stay here for hours showing you examples of how full communication can be in my language.

Just a simple question: Do all native English speakers know what Celluloid is or what it's for?

Now did you understand what I'm getting at?

- - - - -

Eu já encontrei arquivos .desktop com as entradas "pt" e "pt_PT", o mesmo vale para as pastas "/usr/share/locale/pt/LC_MESSAGES" e "/usr/share/locale/pt_PT/LC_MESSAGES". Eu alguns sistemas operacionais, a seleção do idioma ocorre da seguinte forma, o usuário escolhe "Português" e depois indica o país Portugal = "PT" ou Brasil = "BR", eu não acredito que seja um problema ter as duas entradas "pt" e "pt_PT". Como eu não tenho certeza disso, nós precisaríamos de uma opinião de um outra pessoa que domine mais este assunto.

"The new pt_BR translation changed the generic name from "Tocador Multimídia" to "Reprodutor ou Tocador de Multimídia Celluloid", but "Celluloid" is non-generic so I think the original version is correct here. Likewise, the name "Celluloid" was changed to "Reprodutor de Multimídia Celluloid", but just the application name should be used here."
Sobre eu utilizar este modelo "Reprodutor de Multimídia Celluloid", é o mesmo modelo que eu encontrei de um outro tradutor voluntário Brasileiro. Eu não sei o nome desta pessoa, mas fez um excelente trabalho no Thunderbird. No arquivo arquivo .desktop, a entrada pt_BR está assim: "Name[pt_BR]=Cliente de E-mail Thunderbird".
As pessoas não são obrigadas as saber o que é ou o que faz o "Thunderbird", "CherryTree", "Celluloid", "MPV", "Connman UI Setup", "Feh", etc. Pelo menos em meu idioma, a informação do que é ou para que serve na frente do nome é o ordem natural para nós. Pouco importa o nome em Inglês que vem depois, não importa se é "Cliente de E-mail Thunderbird" ou "Cliente de E-mail Claws Mail", até porque a tradução do nome não faz sentido algum ao que o programa se propõe a fazer. Desde quando eu vi este modelo, passei a perguntar nos grupos de usuários Brasileiros nas redes sociais (WhatsApp, Telegram, Matrix, Facebook, etc.) se gostam ou não deste modelo, eu recebi o apoio da maioria dos usuários de várias distribuições GNU/Linux, entre elas MX Linux, Trisquel, Arch Linux, antiX, PCLinuxOS BR, etc.
Eu espero que você utilize os textos que eu te enviei do meu idioma, o meu objetivo é tornar os menus totalmente compreensíveis conforme o exemplo do "Thunderbird", ou seja, ficando da seguinte forma:

Name=Thunderbird
Name[pt_BR]=Cliente de E-mail Thunderbird

Name=Celluloid
Name[pt_BR]=Reprodutor de Multimídia Celluloid

Name=Connman UI Setup
Name[pt_BR]=Gerenciador de Conexões de Rede CMST ConnMan

Não importa se o texto ficou grande, o que importa é que todos os Brasileiros conseguirão compreender facilmente qual é o programa "Cliente de E-mail", "Reprodutor de Multimídia" e o "Gerenciador de Conexões de Rede", observe que o nome foi mantido, mas a informação será compreendida por todos que falam o meu idioma e em qualquer parte do Brasil.

Sobre a entrada "GenericName[pt_BR]=Reprodutor ou Tocador de Multimídia Celluloid", as palavras "Reprodutor" e "Tocador" são formas diferentes utilizadas no Brasil (em idioma Inglês não possui diferença, mas no meu idioma, as duas formas são as mais utilizadas.). Em alguns sistemas operacionais, quando o cursor fica parado sobre o menu, os textos da entrada "GenericName[pt_BR]" ou da entrada "Comment[pt_BR]=" são exibidos.
Pensando bem, o texto da entrada "Comment[pt_BR]=", eu deveria ter incluído a palavra "áudio", ficando assim: "Comment[pt_BR]=Reproduz filmes, vídeos e áudio".

Dizem que uma imagem diz mais do que mil palavras, então eu vou exemplificar com as imagens:

"Textos dos Menus em pt-BR (1).png" - Faltam ser traduzidos/adaptados para pt-BR: "Ceni", "Claws Mail", "Dillo", "Firefox ESR", "gFTP", "GNOME PPP", "HexChat" e "Links2". Os demais estão devidamente traduzidos ou adaptados para pt-BR.
"Textos dos Menus em pt-BR (2).png" - Exemplifica a "condição ideal", pois qualquer Brasileiro que saiba ler conseguirá compreender cada um dos menus. Todos estes menus estão sendo distribuídos nas atualizações do antiX (meus agradecimentos ao criador do antiX por sua confiança em mim).
"Textos dos Menus em pt-BR (3).png" - Os três primeiros menus que estão na parte superior estão perfeitos. Os três menus que estão na parte inferior, ninguém sabe o que é, o usuário precisa pesquisar na internet ou ler manuais para descobrir o que é "Gtkam", "Draw" ou "Mirage". Ninguém sabe o que é isso.
"Textos dos Menus em pt-BR (4).png" - O mesmo vale para estes menus que estão em Inglês, ninguém sabe o que é "Asunder CD Riper", "Celluloid", "GUVCView", "MPV Media Player" (está em Inglês e deveria estar em pt-BR), "SMTube", etc.

O modelo do texto do "MPV Media Player" serve como comparação para o Celluloid?

A tradução do "MPV Media Player" será "Reprodutor de Multimídia MPV", igual ao modelo que eu quero que fique para o Celluloid.

Eu poderia ficar aqui por horas te mostrando exemplos de como a comunicação pode ser plena em meu idioma.

Apenas uma pergunta simples: Todos os nativos do idioma Inglês sabem o que é ou para que serve o Celluloid?

Agora você conseguiu compreender onde eu quero chegar?

**Comment by gnome-mpv** [comment]
I think I understand what you're trying to do, but this is something that would be better done in the application launcher. In the [specs for desktop files](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) (see table 2), there are separate entries for the name of the application and its generic name. In Celluloid's case:

```
Name=Celluloid
GenericName=Multimedia player
```

The application launcher can choose whether not to display these entries individually. For example, it can choose to display `GenericName` below `Name` like this:

```
┌─────────────────┐
│Celluloid        │
│Multimedia Player│
└─────────────────┘
```

or it could put `GenericName` after `Name` like this:

```
┌─────────────────────────────┐
│Celluloid - Multimedia player│
└─────────────────────────────┘
```

Or it could just display `Name` and only display `GenericName` as a tooltip. That's why I don't think it's a good idea to include the generic part in the `Name` entry. It doesn't conform to the specs, and it also gives the application launcher less flexibility.

**Comment by marcelocripe** [comment]
"Or it could just display Name and only display GenericName as a tooltip. That's why I don't think it's a good idea to include the generic part in the Name entry. It doesn't conform to the specs, and it also gives the application launcher less flexibility."
Translations need to make complete sense to end users, as I wrote earlier "computer users don't have to understand the English language just to be able to use programs, that's what translations are for". In the case of displaying only the name of a program in English, it does nothing for people who cannot read the English language. Furthermore, the word "Celluloid" does not have the meaning of "Multimedia Player", people are not required to know what "Celluloid" is or what it is for. That's why I include the description to ensure the information is understood. What I am saying is that it will be up to each volunteer translator to assess whether or not it is coherent to adapt the translation in such a way that it makes complete sense in the respective language.

"It doesn't conform to the specs, and it also gives the application launcher less flexibility."
A: The specifications were designed for the English language and not for the Brazilian Portuguese or Japanese languages. The complete structure to make sense in my language (pt-BR) would be "GenericName + Name", as this is the natural organization in my language, while for the English language "Name + GenericName" (I believe, as it is in MPV Media Player).

For example, I don't know how to write or read in English and the texts I send you are automatic translations of my original text in Brazilian Portuguese.

Can I have your antiX program translated into my language?

I want to have all menus translated and all programs translated into my language, is that too much to ask?

Can we at least have the menu texts translated into the languages ​​"de", "fr_BE", "it", "pt", "pt_BR"?

Please include in your .desktop file the entries of the languages ​​that do not exist, at least for the languages ​​"de", "fr_BE", "it", "pt", "pt_BR", these languages ​​I'm sure have been reviewed by human beings.

Will I need to do another "Pull Requests" for the languages ​​I listed above?

- - - - -

"Or it could just display Name and only display GenericName as a tooltip. That's why I don't think it's a good idea to include the generic part in the Name entry. It doesn't conform to the specs, and it also gives the application launcher less flexibility."
As traduções precisam fazer sentido completo para os usuários finais, como eu havia escrito anteriormente "os usuários de computadores não são obrigados a compreender o idioma Inglês só para poder utilizar os programas, para isso existem as traduções". No caso de exibir apenas o nome de um programa em Inglês, isso não representa nada para as pessoas que não sabem  ler em idioma Inglês. Além do mais, a palavra "Celluloid" não possui o significado de "Multimedia Player", as pessoas não são obrigadas a saber o que é ou para que serve o "Celluloid". É por isso que eu incluo a descrição para garantir que a informação seja compreendida. O que eu estou dizendo é que caberá a cada tradutor voluntário avaliar se é coerente ou não adaptar a tradução de tal forma que possa fazer sentido completo no respectivo idioma. 

"It doesn't conform to the specs, and it also gives the application launcher less flexibility."
R: As especificações foram pensadas para o idioma Inglês e não para o idioma Português do Brasil ou Japonês. A estrutura completa para fazer sentido em meu idioma (pt-BR) seria "GenericName + Name", pois é esta a organização natural em meu idioma, enquanto que para o idioma Inglês "Name + GenericName" (acredito eu, assim como é no MPV Media Player).

Por exemplo, eu não sei escrever ou ler em idioma Inglês e os textos que eu te envio são traduções automáticas do meu texto original em idioma Português do Brasil. 

Eu posso ter o seu programa no antiX traduzido para o meu idioma?

Eu quero ter todos os menus traduzidos e todos os programas traduzidos  para o meu idioma, será que isso é pedir muito? 

Nós podemos ter ao menos os textos dos menus traduzidos para os idiomas "de", "fr_BE", "it", "pt", "pt_BR"?

Por favor, inclua no seu arquivo .desktop as entradas dos idiomas que não existem, ao menos dos idiomas "de", "fr_BE", "it", "pt", "pt_BR", estes idiomas eu tenho certeza que foram revisados por seres humanos.

Eu precisarei fazer outro "Pull Requests" para os idiomas que eu listei acima?
