### ISSUE TITLE
[Solved] (v0.21) Problems that turn off when multiple new windows are opened and the close button is pressed.

### ISSUE THREAD

**Issue by bdh1993** [celluloid-player/celluloid#807]
### Overview Description:
**This issue does not occur in the latest 0.24 version.
However, it all occurs in Ubuntu 20.04 (Celluloid 0.21 or lower).
It should also be tested whether it was solved by gtk4.**

This problem has been a bug for a long time.
As a result of comparing and checking, this is a bug caused by updating from version 0.15 to version 0.16.
The problematic file was named **gmpv_video_area.c** file, which was renamed **celluloid-video-area.c.**

**line 143 : GTK_WIDGET_CLASS(gmpv_video_area_parent_class)->destroy(widget);**

If you erase and check the following contents, you can see that there is no problem.
The problem was resolved, but other effects of clearing could not be determined.

### Steps to Reproduce:
1. Start Celluloid (Version 0.21 or lower)
2. Open several new windows.
3. Press the X button one by one to close it.
4. If you close more than two windows, all the windows will be closed.

### Actual Results:
All windows close

### Expected Results:
The windows close one by one.

### Version:
0.21

### Additional Information:
#715
#625

**Comment by gnome-mpv** [comment]
Closing since this is already fixed in git master.

If you want the fix in Ubuntu LTS, you should report this with them so they can apply relevant patches.
