### ISSUE TITLE
[Request] In fullscreen, UI elements only show up if the mouse pointer is near them

### ISSUE THREAD

**Issue by Yasand123** [celluloid-player/celluloid#809]
First of all, big thankyou to the devs and designers for creating such a nice and elegant media player.

So, I use the mouse to control the volume, and it's not ideal seeing the UI pop up every time I do so, because you most likely will move the mouse if you're like me. It's also nice even if you don't use the mouse, accidental movements, too, make the UI show up.

I think a better way to address the UI in fullscreen is make it so they show up on two conditions, first if there's mouse movement, second if the movement is near an element (i.e. timeline or headerbar) as users most likely want them to show up at that point, but not otherwise.

This might sound a little unnecessary to you, but it's a big QoL improvement if you tried it yourself, and it's the details that make the overall experience all the more polished.

**Comment by gnome-mpv** [comment]
Would a *deadzone* work for your use case? It is an area where cursor movements will not cause the controls to be shown, similar to the deadzone in mpv's [OSC](https://github.com/tmm1/mpv-player/blob/master/DOCS/man/osc.rst#configurable-options). In Celluloid, you can control the size of the deadzone with the dconf key `io.github.celluloid-player.Celluloid controls-dead-zone-size`.

**Comment by Yasand123** [comment]
> Would a deadzone work for your use case?
This works perfectly for that. Thanks!
