### ISSUE TITLE
Doubt weblate translation

### ISSUE THREAD

**Issue by gallegonovato** [celluloid-player/celluloid#812]
Good afternoon 

First of all I apologize, if this question is not here. But I didn't know how to ask it.

I happen to be looking at weblate to help in the trafuction. And I find for example: mpv

Apart from being about analytics. It is also Minimum Viable Product. But I think you are looking for or talking about the file (extension) that usually comes or was associated with Microsoft Media Player. That could also open Cyberlink Powerdvd.

But I don't know if it would be better to translate it as .mpv or mpv extension.

Hence my doubt.

I apologize for the inconvenience and thank you for your help.

**Comment by gnome-mpv** [comment]
[`mpv`](https://github.com/mpv-player/mpv) is the name of the library that Celluloid uses for handling audio/video playback. You can probably leave it untranslated, or translate it as "mpv player".

Thanks for translating!

**Comment by gallegonovato** [comment]
Good afternoon @gnome-mpv

First of all thank you very much for your answer and help.

About mpv as you see fit. Because you can also put .mpv (as an extension, since it is also an audio and video compression). So as you tell me, that's how I put it :)

You don't have to thank me for helping with the translation. I will be happy to do it for you in the languages that you want ;) :)

Best regards
