### ISSUE TITLE
"Open Folder..." and "Open Disc" are not translated in russian

### ISSUE THREAD

**Issue by BrainKicker** [celluloid-player/celluloid#836]
Overview Description:

"Open Folder..." and "Open Disc" are not translated in russian. I tried to translate it on Weblate, but I haven't found these strings there.

![изображение](https://user-images.githubusercontent.com/30545094/209910606-9407007a-f7eb-4bd0-8190-5725d3dd1751.png)

Steps to Reproduce:
1. Switch to russian
2. Press the "+" button on the top left corner

Version:
Celluloid 0.21

Additional Information:
Linux Mint 21 Vanessa

**Comment by gnome-mpv** [comment]
The translations will start appearing once I sync them from Weblate, which I'll do some time before the next release.
