### ISSUE TITLE
MPV size shortcut doesn't work; or ability to change Alt+0/1/2

### ISSUE THREAD

**Issue by HubKing** [celluloid-player/celluloid#839]
Resizing the video window is what I do very often. Using mouse is not often convenient, so for MPV, I have set easy-to-press shortcuts 1,2,3,4 for the sizes I often use like 50%, 100%, 150%, 200%. I have made Celluloid to load MPV input settings, but pressing such keys does not change the window and only shows the OSD "Current window scale (unavailable)". Can Celluloid honour MPV resize event?

If not, can Celluloid allow users to change the default shortcuts? I mean, alt+0,1,2 may look logical but in reality, it is very awkward because the order of numbers on a keyboard  is 1,2,3,...9,0, NOT, 0,1,2,...9. Pressing Alt + 0 is very difficult.

**Comment by gnome-mpv** [comment]
> I have made Celluloid to load MPV input settings, but pressing such keys does not change the window and only shows the OSD "Current window scale (unavailable)".

What command are you using for this? The default keybindings are using `set window-scale 0.5` etc. so it should work if you use the same command.

**Comment by HubKing** [comment]
I had been using `set current-window-scale <number>`. Removing `current-` worked.

**Comment by spamegg1** [comment]
Can we reopen this? I have the same issue on Celluloid 0.21 and mpv 0.34.1. I am NOT using any mpv input config.
Celluloid's keyboard shortcuts page says to use Alt+0,1,2 shortcuts:
![Screenshot from 2023-05-22 20-44-39](https://github.com/celluloid-player/celluloid/assets/4255997/846ba78e-210d-49f9-9355-12cf5f956f00)
But it gives the error as the OP:
![Screenshot from 2023-05-22 20-48-01](https://github.com/celluloid-player/celluloid/assets/4255997/8c30edf0-cc0a-4357-ade9-902211f2c93a)
Tried it on every video file I could find, same result.

**Comment by miguelrdev** [comment]
I had the same issue like @spamegg1 with a fresh OS install and no user config files.

I created .config/mpv/input.conf with these contents, loaded it in Celluoid preferences, and now it works:

```
Alt+0 set window-scale 0.5             # halve the window size
Alt+1 set window-scale 1               # reset the window size
Alt+2 set window-scale 2               # double the window size
```
