### ISSUE TITLE
10430 segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Razer0123** [celluloid-player/celluloid#844]
Overview Description:

Steps to Reproduce:
1. Just open the app
2.
3.

Actual Results:
Crash

Expected Results:
No crash
Version:
0.24-4

Additional Information:
Fedora 36 - GPU 7900 XTX

**Comment by gnome-mpv** [comment]
I can't reproduce this.

Can you provide a [backtrace](https://github.com/celluloid-player/celluloid/blob/master/.github/CONTRIBUTING.md)?

**Comment by Razer0123** [comment]
Not sure what happened, restarting fixed the issue, thanks
