### ISSUE TITLE
YouTube URL support currently broken

### ISSUE THREAD

**Issue by MaxBrandtner** [celluloid-player/celluloid#848]
**Overview Description:**
When trying to run a YouTube video from a URL, it will throw an error message and quit.

**Steps to Reproduce:**
```bash
flatpak run io.github.celluloid_player.Celluloid https://www.youtube.com/watch?v=[...]
```

**Actual Results**

```bash
zsh: no matches found: https://www.youtube.com/watch?v=[...]
```

*Note that the video URL has been redacted*

**Expected Results:**

*plays YouTube video*

**Version:**

`Celluloid 0.24`

**Additional Information:**

I've installed:
   `yt-dlp`
   `youtube-dl`

Furthermore, from my current understanding, it seems as if celluloid is meant to use `yt-dlp` *(though it seems as if that doesn't work right now)*. Thus, it would be great to add some options like `quality` options, a `download` option and the option to enable `sponsorblock`.

**Comment by gnome-mpv** [comment]
`yt-dlp` was broken recently, so the Flatpak package needs to be updated with the new version.

> Furthermore, from my current understanding, it seems as if celluloid is meant to use yt-dlp (though it seems as if that doesn't work right now). Thus, it would be great to add some options like quality options, a download option and the option to enable sponsorblock.

You can do that using the [`--mpv-ytdl-raw-options`](https://mpv.io/manual/stable/#options-ytdl-raw-options) option.

**Comment by moshiur-raj** [comment]
@MaxBrandtner You need to surround the link in quotes. zsh interprets the ? sign in the link as a regular expression.

**Comment by MaxBrandtner** [comment]
that solves it. However and I am aware that you may not see that as your issue some applications (gfeeds) don't pass the youtube links in quotes. Would there be a way on your end to get around that issue?

**Comment by moshiur-raj** [comment]
You'll need to use application specific flags then. I dont know what options to use for gfeeds. Sorry.
Maybe you can try using \ before special characters (inside the quotes).

**Comment by MaxBrandtner** [comment]
this is a different issue *(and thus perhaps this issue should maybe  be renamed)*, but the audio doesn't work in playback with youtube-dl

**Comment by gnome-mpv** [comment]
> this is a different issue (and thus perhaps this issue should maybe be renamed), but the audio doesn't work in playback with youtube-dl

This is a compatibility issue between mpv and the latest version of yt-dlp. See https://github.com/yt-dlp/yt-dlp/issues/6496.

**Comment by gnome-mpv** [comment]
The flatpak is now using mpv 0.35.1 which contains the fix for this issue.
