### ISSUE TITLE
Update About Window to AdwAboutWindow

### ISSUE THREAD

**Issue by gianni-rosato** [celluloid-player/celluloid#850]
Overview Description: While older versions of libadwaita did not support this, updating the manifest & changing the code accordingly lets you implement a cleaner & easier to use about window in the form of [AdwAboutWindow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.AboutWindow.html) to be more consistent with modern GNOME.

Steps to Reproduce:
1. Click hamburger menu in the top right
2. Click the "About Celluloid" menu item
3. Observe the older about window

Actual Results: About window uses outdated styling

Expected Results: About windows uses current styling consistent with AdwAboutWindow

Version: 0.24

Additional Information:

**Comment by gnome-mpv** [comment]
Already implemented in afa7d7c237a20683119aa348cece997f1c24c340. It'll be included in the next release.
