### ISSUE TITLE
Celluloid crashes

### ISSUE THREAD

**Issue by DisplayName101** [celluloid-player/celluloid#860]
.deb Celluloid crash when opening, it should not crash, flatpak version doesn't reproduce a video and crashes. I just removed and installed a lot of times but it didin't worked.

user@pcname:~$ exec celluloid

(io.github.celluloid_player.Celluloid:3222): Gtk-WARNING **: 00:16:35.516: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4284:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
Bail out! GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4284:invoke_get_property_in_idle_cb: assertion failed: (error != NULL).

**Comment by gnome-mpv** [comment]
This sounds like it could be a packaging issue. You should report this with your distro.

**Comment by DisplayName101** [comment]
I'm using linux mint.

**Comment by DisplayName101** [comment]
It just started to work again i think after autoremoving unnecessary packages.
