### ISSUE TITLE
Dragging the window is laggy when a video is playing

### ISSUE THREAD

**Issue by massassignment** [celluloid-player/celluloid#861]
I use Celluloid on Gnome (43, now 44) under Wayland. I've used both native and flatpak across Fedora and Arch, with the same issue.
Essentially there's a responsiveness issue when dragging the window when a video is playing. The cursor does not track the window accurately when moving it, such that the cursor will end up in the middle of the video window, or at a different point on the titlebar by the time you stop dragging. It gives Celluloid this laggy feeling, when I really don't feel like the issue here is performance. 

The same issue does not happen with mpv alone (nor Clapper or Totem).
I don't feel it's my particular setup here so I've not delved deeply into logs, etc. I'd be surprised if not everyone has the same experience, but if there's something I can change please let me know how. I am currently using flatpak (and vaapi setting, but no difference).

Lastly, the app is otherwise great, thank you very much.

**Comment by gnome-mpv** [comment]
> The cursor does not track the window accurately when moving it, such that the cursor will end up in the middle of the video window, or at a different point on the titlebar by the time you stop dragging.

I don't think I have ever seen something like that. Would you be able to share a screen recording of it?

**Comment by massassignment** [comment]
Sure, hopefully this helps show what I mean, the difference between a video playing or not. Thanks.

[Screencast from 2023-05-01 14-56-58.webm](https://user-images.githubusercontent.com/132239018/235411537-4fbeab3a-8c3b-42b6-ab7d-c49b21cf5783.webm)

**Comment by gnome-mpv** [comment]
Hmm. I can't seem to reproduce this. I see some minor drifting when dragging the window on X11, but nothing close to what's shown in the video. I don't see any drifting on Wayland.

**Comment by massassignment** [comment]
Well I just switched back to a regular package in Arch (from flatpak in Fedora) and it all seems fine, I don't have this issue now so who knows. Thanks for your time!
