### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Frost4142** [celluloid-player/celluloid#862]
Overview Description:
Bail out! GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4284:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Version:0.20

Additional Information:

**Comment by gnome-mpv** [comment]
Sounds like the same issue as #860.

**Comment by gnome-mpv** [comment]
Feel free to reopen if you still experience the problem after autoremoving packages as suggested in #860.
