### ISSUE TITLE
Update Snap Listing

### ISSUE THREAD

**Issue by CapeCrusader321** [celluloid-player/celluloid#864]
@gnome-mpv  Sorry for this, but i have rebuild the snap under the original name celluloid instead of celluloid-snap, also the current builds have mpris by default, and as such please update the snap listing with the following links, thanks.

<a href="https://snapcraft.io/celluloid">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

Manifest/Source : https://github.com/CapeCrusader321/Celluloid-Snapcraft

**Comment by gnome-mpv** [comment]
Done.
