### ISSUE TITLE
MPRIS ID For Celluloid ?

### ISSUE THREAD

**Issue by CapeCrusader321** [celluloid-player/celluloid#865]
Hey there i want to know which mpris id celluloid owns, i meant the mpris id for celluloid ??

**Comment by gnome-mpv** [comment]
We use this bus name `org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid.instance-%u` where `%u` is a positive integer, e.g. `org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid.instance-1`. The `%u` is incremented for each new instance (window) to generate unique bus names.

**Comment by CapeCrusader321** [comment]
> We use this bus name `org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid.instance-%u` where `%u` is a positive integer, e.g. `org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid.instance-1`. The `%u` is incremented for each new instance (window) to generate unique bus names.

Thanks but can you also tell me the files where this specified, snap doesnt support mpris names with periods, i will have to use maybe some bash scripting to change  org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid.instance to Celluloid to get celluloid use in snap.

**Comment by gnome-mpv** [comment]
> Thanks but can you also tell me the files where this is specified, snap doesnt support mpris names with periods, i will have to use maybe some bash scripting to change org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid.instance to Celluloid to get celluloid use mpris in snap.

The base part (`org.mpris.MediaPlayer2.io.github.celluloid_player.Celluloid`) is defined in `celluloid-def.h`, but I don't think that's a good solution. It looks like there's a way to [allow bus names directly](https://snapcraft.io/docs/dbus-interface), so it's probably better to just use that instead.

**Comment by CapeCrusader321** [comment]
@gnome-mpv  I do have defined dbus id but the snappy-debug tool always reports me error saying 'mpris slot missing so i thought it would be good  if i could do that, i am looking into this, the celluloid snap package has some outstanding issue like crashing on maximizing, controls like loop video button always turned on by default and cant be turned off. this all occurs even though i didnt do any mods from side. The settings used to break but after porting it to libadwaita it works fine, i think it has something to do with gtk4 or libadwaita ??
