### ISSUE TITLE
The window size does not automatically scale correctly

### ISSUE THREAD

**Issue by Reaper1121** [celluloid-player/celluloid#868]
Overview Description:

When a video file is opened, the window scale is not of "1", when a keyboard shortcut "Alt + 1" is pressed, the window scale becomes correct, giving me the expected results.

The results show me opening a 1080p video file, which should be taking up all of the available screen space (the expected result) but does not until window scale is reset to "1".

Steps to Reproduce:
1. Open any video file of any resolution

Actual Results: ![Sample1](https://github.com/celluloid-player/celluloid/assets/24590695/f4db7101-c4ba-45b9-b50e-cf12730d8f69)

Expected Results: ![Sample2](https://github.com/celluloid-player/celluloid/assets/24590695/db30fabb-842f-4ad8-9289-f52776db94f4)

Version: 0.25

Additional Information:

I have tried writing a Lua script to automatically reset the window scale on file load hopefully fixing this problem, but even though the script is in the correct directory and added to the plugins menu in the preferences, the script never executed, might be related to: #867

In case it matters, I am using Arch Linux with Openbox WM (X11).

**Comment by gnome-mpv** [comment]
That's by design. You can add `--autofit-larger=` to extra mpv options to get the behavior you want.

**Comment by Alluseri** [comment]
> That's by design. You can add `--autofit-larger=` to extra mpv options to get the behavior you want.

@gnome-mpv No, that doesn't work... Neither `--autofit-larger=100%`, nor `--autofit-larger=100%x100%`, nor `--autofit=100%`, nor `--autofit=100%x100%`, nor `--autofit-smaller=100%`, nor `--autofit-smaller=100%x100%`, nor all of them at once or combined individually give expected results(99% also doesn't work, lol). In the absolute best case scenario, the window is correctly sized, while being positioned into the bottom half of the screen, and has to be moved manually. Both the screen resolution and the video resolution are 1920x1080.

Tested on Arch Linux with KDE Plasma 5.27.6-2, screen recording upon request if needed.

**Comment by gnome-mpv** [comment]
> @gnome-mpv No, that doesn't work... Neither --autofit-larger=100%, nor --autofit-larger=100%x100%, nor --autofit=100%, nor --autofit=100%x100%, nor --autofit-smaller=100%, nor --autofit-smaller=100%x100%, nor all of them at once or combined individually give expected results(99% also doesn't work, lol).

Did you try leaving out the part after the equal sign?
