### ISSUE TITLE
Celluloid gtk-file-picker appears broken

### ISSUE THREAD

**Issue by capecrusader-121** [celluloid-player/celluloid#869]
Overview Description:
This is yet another celluloid specific issue where the gtk file picker appears broken, i can confirm this on my intel-x11 and picom device though i cant confirm if this occurs on wayland or pure x11.

Steps to Reproduce:
1. Install celluloid, (I used Snap Version)
2. Once opened, choose open files.
3. Face the issue.

Actual Results:
The file chooser is broken. and has elements misaligned. 

Expected Results:
Appears normal as it appears usually in xdg-portals, with proper element aliening. 

Version:
0.25 

Additional Information:
I Face this with lxqt x11-openbox with picom (Lubuntu 22.04 to be specific).

Screenshots:

![screen](https://github.com/celluloid-player/celluloid/assets/100503303/06106bcf-c158-4966-b011-16d47346bf3f)

See --> https://bugs.launchpad.net/celluloid-snap/+bug/2023969 for more details.

**Comment by gnome-mpv** [comment]
Can you check if this happens with other GTK apps as well?

**Comment by capecrusader-121** [comment]
@gnome-mpv  No only with celluloid, i use multiple libadwaita/gtk apps all fine, although this may be helpful, the gtk-file-portal used by celluloid has starking differences with other gtk/libadwaita apps i mean the celluloid looks more stylish/modern while other gtk apps use the normal xdg-gtk-portal which i believe celluloid doesnt or is doing some custom tweaks.

This is how the file-picker works with other libadwaita/gtk app

![screen](https://github.com/celluloid-player/celluloid/assets/100503303/7fa48a46-a99c-4705-905e-33a9f94c3531)

**Comment by capecrusader-121** [comment]
@gnome-mpv  I think the error may be ! coming from the fact that i am not using the buildtype flag and setting to release after a brief investigation i dicovered celluloid building in native mode, and snaps are built upon gnome-42 powered core22 so i think (just an assumption) the snap is being built gnome specific (the file picker/xdg-portals used by gnome is different than the normal xdg-gtk-portals) ,  correct me if am wrong ?
On my level i will try using the buildtype=release flag to see if anything improves ?

**Comment by gnome-mpv** [comment]
I'm not familiar with Snap so I'm not entirely sure, but it looks like the problem might have something to do with themes.

> On my level i will try using the buildtype=release flag to see if anything improves ?

I don't think that will change anything.

**Comment by capecrusader-121** [comment]
@gnome-mpv  Well i couldnt even succeed in it since surprisingly using the build flag leads to build failures, it only builds without the flag, so removing it in the future.

Libadwaita is theme-free ? mine gtk theme is yaru-dark using xsettingsd.

**Comment by capecrusader-121** [comment]
@gnome-mpv  I believe your assumption that this is theming related may be correct as i am unable to reproduce this is Xubuntu (Xfce) 22.04.3, i could reproduce the above only in Lubuntu(Lxqt) 22.04.3 .

Closing this than, as i believe this is due to poor integration of Gtk/Libadwaita toolkit in Qt DEs like Lxqt .
