### ISSUE TITLE
Click to pause

### ISSUE THREAD

**Issue by K24A3** [celluloid-player/celluloid#870]
How does one suggest a feature in Github? | confused |
Sorry if I didnt fill out the details provided.
Like youtube and most other video players, they allow to to clock the video to pause which is super handy when you need to do something quick like answer the phone or door etc... 

Can we please add this feature to Celluloid? :)

**Comment by gnome-mpv** [comment]
You can already right-click to pause/unpause.

If you want to do the same by left-clicking, you can rebind the button with an input config file.
```
MBTN_LEFT cycle pause
```

**Comment by K24A3** [comment]
Where is the config file?

.\config\  (there is no mpv folder)
.\config\celluloid\  (there are no files, only two empty folders 'scripts' and 'watch_later')

**Comment by stabilergriller** [comment]
~/.config/celluloid/mpv.conf works for me. Just create a new file, if it's missing and set the file path in the config

![image](https://github.com/celluloid-player/celluloid/assets/115423284/29d69e9c-2f36-416e-9665-d8a383546a00)

**Comment by K24A3** [comment]
I did all that and restarted the app, but it only pauses using right click.

![trim](https://github.com/celluloid-player/celluloid/assets/21253896/5039bb2b-9f19-4a71-8de9-879a10c60c3f)

**Comment by gnome-mpv** [comment]
> I did all that and restarted the app, but it only pauses using right click.

Your `mpv.conf` is an input config file, so it should go in the box on the bottom.

**Comment by K24A3** [comment]
Works now, Thanks :)
Suddenly jumping from Windows to Mint causes a lot of head scratching :yum:

**Comment by K24A3** [comment]
gnome-mpv has resolved this issue
