### ISSUE TITLE
Please use time-stamped screenshot file names.

### ISSUE THREAD

**Issue by HT-7** [celluloid-player/celluloid#875]
While I am mostly satisfied with celluloid as a worthy successor to xplayer, the first major disappointment I stumbled upon is `celluloid-shot0001.jpg`. 

2005 called. It wants its numbered file names back.

Just like xplayer, Celluloid, the new default media player of Linux Mint, should use proper, i.e. time-stamped names such as `celluloid-2023-04-10T00-47-42.jpg` or `celluloid-video_file_name-2023-04-10T00-47-42.jpg` screenshots taken from videos, to eliminate the possibility of file name conflicts if files are moved into other directories, to make screenshots searchable by video file name, and to retain the date and time information if the files are moved to a device that does not support date and time stamp retention such as MTP (Media Transfer Protocol), and to allow for date range selection using wildcards in the terminal (e.g. `celluloid-2023-04*` for all screenshots from April 2023).

As a reference, the gnome and mate screenshot tools also pre-fill time stamps into the file name field.

Numbered file names were useful in an era when there was no VFAT and file names needed to have 8.3 file names that could impossibly fit a date and a time, and compact cameras used such names, but those times are long over. Just like the useless and annoying pull-to-refresh gesture on mobile apps and the Media Transfer Protocol, numbered file names belong to the technological graveyard.

If numbers are really desirable, at least make the name `celluloid-shot0001.2023-04-10T00-47-42.jpg` to include both a number and a date.

Implementing time stamped file names would not even take three minutes, so there is no reason not to do it right now. The command to get this date format is `date +"%Y-%m-%dT%H-%M-%S"`. For compatibility across operating systems, dashes instead of colons have to be used to separate hours and minutes and seconds.

Numbered file names are a thing of the past. Use time stamps please.

**Comment by gnome-mpv** [comment]
It sounds like you're running an old version of Celluloid. We stopped using sequentially numbered filenames 2 years ago. We use filename and timestamp (of the video) now.

In any case, you can set a custom screenshot filename template using the `--screenshot-template` option. See mpv's manual for more details.

**Comment by HT-7** [comment]
So it was thought about long ago, and the best possible format (video file name and time stamp) is used? Good to hear.

My operating system is from last year. I guess the version of Celluloid that was bundled with it is somewhat earlier.
