### ISSUE TITLE
PNG screenshots

### ISSUE THREAD

**Issue by HT-7** [celluloid-player/celluloid#876]
Celluloid saves screenshots as JPG.

JPG files are much smaller and sufficient most of the time, but occasionally it is useful to have lossless screenshots, and xplayer, the pre-installed predecessor of Celluloid on Linux Mint, also saved in PNG.

Please provide an option to save screenshots as PNG. Thank you very much.

**Comment by HT-7** [comment]
That was quick. I am impressed. Thank you very much for your good work.

**Comment by jannuary** [comment]
I don't think this is a good default. Right now, Celluloid generates screenshots several MBs in size *each* (for fairly simple 1080p video), which adds up, especially if you take a lot of screenshots. We could have screenshots in basically identical quality by using JPEG with 99% quality, which is still **leagues** more efficient than PNG. 

Also, while not being exposed in the UI (should it be?), mpv already has comprehensive screenshot settings, which could be used instead, should true lossless output be desired.
