### ISSUE TITLE
celluloid: ../stream/stream.c:416: stream_create_with_args: Assertion `args->url' failed.

### ISSUE THREAD

**Issue by breunigs** [celluloid-player/celluloid#880]
Overview Description:
This error appears when I start `celluloid` without arguments. It still starts with `--help`. This happened after updating the Debian testing release, which pulled in a new version of Celluloid as well as various other dependencies. The issue is not reproducible for others on Debian, so presumably something specific on my system is different. I have no good idea what.

Steps to Reproduce:
Apart from starting celluloid, there are no steps to reproduce. Finding the STR will be the tricky part.

Actual Results:
```
$ /usr/local/bin/celluloid
celluloid: ../stream/stream.c:416: stream_create_with_args: Assertion `args->url' failed.
```

Version:
0.25 from Debian
0.25, 0.24, 0.23, 0.22 built from git, using the dependencies of Debian/testing

Additional Information:
The attachments were produced against the 0.25 version from Debian with the following command lines:
* [celluloid.log](https://github.com/celluloid-player/celluloid/files/12380702/celluloid.log) `G_MESSAGES_DEBUG=all celluloid --mpv-msg-level=all=trace > celluloid.log`
* [ltrace_celluloid.log](https://github.com/celluloid-player/celluloid/files/12380697/ltrace_celluloid.log) `env -i XAUTHORITY=~/.Xauthority DISPLAY=:0 ltrace /usr/bin/celluloid > ltrace_celluloid.log 2>&1`
* [strace_fff_ttt_s1000_celluloid.log](https://github.com/celluloid-player/celluloid/files/12380698/strace_fff_ttt_s1000_celluloid.log) `env -i XAUTHORITY=~/.Xauthority DISPLAY=:0 strace -ttt -fff -s 1000 /usr/bin/celluloid > strace_fff_ttt_s1000_celluloid.log 2>&1`
* [ldd_celluloid.log](https://github.com/celluloid-player/celluloid/files/12380699/ldd_celluloid.log) `ldd /usr/bin/celluloid > ldd_celluloid.log`
* [gdb_bt_celluloid.log](https://github.com/celluloid-player/celluloid/files/12380745/gdb_bt_celluloid.log) `gdb -ex 'set pagination off' -ex run -ex bt celluloid`
* [gsettings_list.log](https://github.com/celluloid-player/celluloid/files/12380774/gsettings_list.log) `gsettings list-recursively io.github.celluloid-player.Celluloid > gsettings_list.log`

Regular `mpv` works fine. I am certain Celluloid worked fine at some point, and the same error even on old version suggests a change in a dependency might be the cause for this, as opposed to a change in celluloid. 

My best guess is the assert fails here https://github.com/mpv-player/mpv/blob/f97584cadc23c4e2f20076b7d313b37211412a74/stream/stream.c#L413-L416 
presumably triggered from here: https://github.com/celluloid-player/celluloid/blob/a070fd7af856bc1b3eeb59aca06007bb7bef7078/src/celluloid-player.c#L785-L798

I am not sure why Celluloid apparently reads `mpv-config-enable` as `true`, but then sees `mpv-config-file` as `null` when both are set:
```
io.github.celluloid-player.Celluloid mpv-config-enable true
io.github.celluloid-player.Celluloid mpv-config-file '/home/stefan/.mpv/config'
```
The file also exists and is readable.

For reference, this is the downstream bug report I created https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1049458 .

Let me know if I can provide more info or test something else.

**Comment by antme0** [comment]
I have the same problem with celluloid in Arch Linux:

```shell
$ celluloid
celluloid: ../mpv/stream/stream.c:416: stream_create_with_args: Assertion `args->url' failed.
Aborted (core dumped)
```

celluloid version:  0.25
mpv version: 0.36 (2023-07-24)

**Comment by leandrocunha526** [comment]
I use Plasma and I used it with Gnome and I couldn't reproduce this problem, could it be that it has something to do with hardware? @antme0 and @breunigs

**Comment by gnome-mpv** [comment]
@breunigs Thank you for the very detailed bug report. Is Celluloid able to start if you change `mpv-config-file` to `file:///home/stefan/.mpv/config`?

**Comment by jberli** [comment]
I have the exact same crash on Debian testing, with celluloid 0.25 and mpv 0.36.0. It also happened right after the upgrade.

I have my celluloid configuration file place here `~/.config/celluloid/configuration/celluloid.conf` and provided the location inside celluloid when it used to work.

Here is the content of the `celluloid.conf` file:
```
hwdec=yes
sub-pos=95
sub-font='Ubuntu'
sub-font-size=40
sub-border-size=2
```

**Comment by gnome-mpv** [comment]
> Starting celluloid using the command celluloid --mpv-mpv-config-file=/home/jberli/.mpv/config with the same config file still crashed celluloid with:

I was referring to the GSettings key. You can set the key with `gsettings set io.github.celluloid-player.Celluloid mpv-config-file 'file:///home/jberli/.config/celluloid/configuration/celluloid.conf'`.

**Comment by jberli** [comment]
> > Starting celluloid using the command celluloid --mpv-mpv-config-file=/home/jberli/.mpv/config with the same config file still crashed celluloid with:
> 
> I was referring to the GSettings key. You can set the key with `gsettings set io.github.celluloid-player.Celluloid mpv-config-file 'file:///home/jberli/.config/celluloid/configuration/celluloid.conf'`.

Celluloid does work when changing the mpv-config-file key with gsettings. Thanks for your solution.
Is this the expected behavior? Is this fix temporary or definitive?

**Comment by gnome-mpv** [comment]
>  Is this the expected behavior? Is this fix temporary or definitive?

No. This is just a workaround. I'll fix it properly.

**Comment by leandrocunha526** [comment]
Until I deleted my question, I didn't even think that this would be the problem and should insert this patch for @Debian. I thought it was a hardware problem, but it has nothing to do and it doesn't happen here.

**Comment by leandrocunha526** [comment]
This has been fixed in Debian, thanks!
https://metadata.ftp-master.debian.org/changelogs//main/c/celluloid/celluloid_0.25-2_changelog
