### ISSUE TITLE
show frame rate and bit rate during playback

### ISSUE THREAD

**Issue by HT-7** [celluloid-player/celluloid#888]
Media Player Classic (only for Windows) has the ability to show technical details during playback that tools such as `mediainfo` can not show, such as the current bitrate and framerate in real time, which means during playback.

This would not be necessary if all video files had constant frame rates and bit rates throughout the video, however, video files can have variable frame rates and bit rates, and video files concatenated using `ffmpeg` can even have variable resolutions (don't worry, it is already playable), so please add an option to show these technical details in real-time.

It can be displayed as a status bar that appears above or below the playback control / seek bar row.

**Comment by gnome-mpv** [comment]
You can already see this kind of info by pressing `I`.
