### ISSUE TITLE
Cannot seek using global shortcuts

### ISSUE THREAD

**Issue by p-fruck** [celluloid-player/celluloid#889]
Overview Description:

I am using the [Gnome media controls extension](https://extensions.gnome.org/extension/4470/media-controls/) in order to have a global media menu I can use to play/pause/ff/rewind media playback. 

Actual Results:

Using the extension with celluloid works fine for play/pause, but seek forward/backward won't work (it works for other video players though, tested with VLC)

Expected Results:

FF/Rewind should work with celluloid too

Version:

0.25

Additional Information:

Running Fedora 38, Gnome 44, Wayland. Installed Celluloid as Flatpak

**Comment by gnome-mpv** [comment]
This is no longer reproducible in git master.

**Comment by p-fruck** [comment]
Confirmed, version 0.26 fixes this issue :+1:
