### ISSUE TITLE
libmpv no render context set, video broken 

### ISSUE THREAD

**Issue by TheBestKmanEver** [celluloid-player/celluloid#891]
Overview Description:
video output is broken

Steps to Reproduce:
1. open video file
2. 
3.

Actual Results:
(seen in screenshot)

Expected Results:
not broken video

Version:
0.25-0.1

Additional Information:
![Screenshot_20230903_114431](https://github.com/celluloid-player/celluloid/assets/35676228/7eef9ab7-5ebb-4a39-92ed-ac4c8bc40a68)

[system info.txt](https://github.com/celluloid-player/celluloid/files/12506505/system.info.txt)

**Comment by gnome-mpv** [comment]
Can you check if this also happens with `mpv`?

**Comment by TheBestKmanEver** [comment]
same issue

**Comment by gnome-mpv** [comment]
> same issue

In that case, it is an mpv bug. You should file a bug report with them.

**Comment by TheBestKmanEver** [comment]
will do, thank you
