### ISSUE TITLE
Celluloif keeps crashing when an MTP USB device status change is published.

### ISSUE THREAD

**Issue by alainpannetier** [celluloid-player/celluloid#904]
Overview Description:
Celluloif keeps crashing when an MTP USB device status change is published.

Steps to Reproduce:
1. Plug or unplug some smartphone through USB. MTP protocol (gvfs).
2. Nearly always celluloid SEGV

Actual Results:
Crash and core dump
[issues.dmp.txt](https://github.com/celluloid-player/celluloid/files/13196132/issues.dmp.txt)

Expected Results:
Guard against SEGV inside celluloid in the code.

Version:
0.21

Additional Information:
Search through the issues with "crash" search word. Saw a lot. None matching this case.
I can upload core dumps in zst format (size range from 39M to 190M)

**Comment by gnome-mpv** [comment]
I can't reproduce this. Can you upload a coredump?

Also, would you be able check if v0.26 crashes the same way?

**Comment by alainpannetier** [comment]
Due to upload limit: upload size is 25MB. Uploading my smallest core dump (53MB in 3 volumes 7zip of ZST).  Remove ".txt" extensions wherever applicable. Volume 1 here.
[core.celluloid.1000.979ebadb184042a69b7563e4517383a3.277803.1698334145000000.zst.txt.7z.001.txt](https://github.com/celluloid-player/celluloid/files/13199217/core.celluloid.1000.979ebadb184042a69b7563e4517383a3.277803.1698334145000000.zst.txt.7z.001.txt)

**Comment by alainpannetier** [comment]
volume 2: 
[core.celluloid.1000.979ebadb184042a69b7563e4517383a3.277803.1698334145000000.zst.txt.7z.002.txt](https://github.com/celluloid-player/celluloid/files/13199221/core.celluloid.1000.979ebadb184042a69b7563e4517383a3.277803.1698334145000000.zst.txt.7z.002.txt)

**Comment by alainpannetier** [comment]
volume 3 (last):
[core.celluloid.1000.979ebadb184042a69b7563e4517383a3.277803.1698334145000000.zst.txt.7z.003.txt](https://github.com/celluloid-player/celluloid/files/13199223/core.celluloid.1000.979ebadb184042a69b7563e4517383a3.277803.1698334145000000.zst.txt.7z.003.txt)

**Comment by alainpannetier** [comment]
Just upgraded to 0.24 from PPA (http://ppa.launchpad.net/xuzhen666/gnome-mpv/).
Testing.
