### ISSUE TITLE
Calling org.gnome.SessionManager.Inhibit failed: GDBus.Error:org.gnome.SessionManager.GeneralError: Invalid inhibit flags

### ISSUE THREAD

**Issue by nekohayo** [celluloid-player/celluloid#905]
With Celluloid 0.26 from the Fedora 39 package, launching playback of any video in Celluloid via Nautilus will trigger this warning in the system logs, as soon as the video playback starts:

`Calling org.gnome.SessionManager.Inhibit failed: GDBus.Error:org.gnome.SessionManager.GeneralError: Invalid inhibit flags`

This gets can be seen with `journalctl -f`, or when running Celluloid from a terminal.

**Comment by gnome-mpv** [comment]
I think this might be a GTK or gnome-session bug. All we're doing is call `gtk_application_inhibit` with `GTK_APPLICATION_INHIBIT_IDLE`, which is a GTK-provided flag, so I don't see how that could be invalid.

**Comment by nekohayo** [comment]
Hm, interesting! I had not suspected that possibility, as it occurs on more than one computer.

I have now installed celluloid as a flatpak from flathub, and at least running that from the terminal does not yield this error/warning.

That said, Totem (also installed from the Fedora repositories) does not give this warning when playing the same video in the terminal. I would have thought that Celluloid and Totem would use the same power management inhibition APIs...

How to tell whether it's a bug in the downstream celluloid distro package, or in GTK or GNOME Session upstream?

**Comment by gnome-mpv** [comment]
> That said, Totem (also installed from the Fedora repositories) does not give this warning when playing the same video in the terminal. I would have thought that Celluloid and Totem would use the same power management inhibition APIs...

Since this started happening recently, it's probably something related to GTK4. Totem still uses GTK3, so it wouldn't make for a good comparison.

> How to tell whether it's a bug in the downstream celluloid distro package, or in GTK or GNOME Session upstream?

You can try downgrading GTK/gnome-session and see if the problem goes away.

**Comment by darix** [comment]
Reported to gtk upstream at https://gitlab.gnome.org/GNOME/gtk/-/issues/6470

**Comment by darix** [comment]
JFYI you can close this bug. the fix was committed in gtk today.
