### ISSUE TITLE
Celluloid automatically resizes when preference window is closed

### ISSUE THREAD

**Issue by Rid1-fz-06** [celluloid-player/celluloid#910]
Overview Description: When I maximize the celluloid window, open the `Preferences`, and close it, celluloid automatically resizes and restores itself.

Steps to Reproduce:
1. Open `Celluloid`
2. Maximize `Celluloid` window
3. Open `Preferences` window
4. Close `Preferences` window

Actual Results: `Celluloid` automatically resizes and restores itself from maximized size.

Expected Results: The window size should not be changed

Version: Celluloid 0.26

Additional Information: I installed `Celluloid` from the official repo of `Fedora 39`. Here are the details of my system...

- **Firmware Version:**                            F.3C
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.3-200.fc39.x86_64

**Comment by capecrusader-121** [comment]
I can confirm this happens with me to.

Using snap format.

**Comment by Rid1-fz-06** [comment]
@capecrusader-121 it also happens with the flatpak version of `Celluloid`

**Comment by gnome-mpv** [comment]
Should be mostly fixed in git master. Now resize will only happen if you make changes to options that require re-initializing mpv.
