### ISSUE TITLE
FR: use arrow up/down buttons for Volume like VLC

### ISSUE THREAD

**Issue by firefoxlover** [celluloid-player/celluloid#917]
currently they are simply duplicating the arrow left/right buttons.

is there a way to remap them?

this would be the internal volume, so related to https://github.com/celluloid-player/celluloid/issues/753

**Comment by gnome-mpv** [comment]
> currently they are simply duplicating the arrow left/right buttons.

They're not exactly the same. Up/down arrows seek in 1-minute steps while left/right arrow seek in 5-second steps.

> is there a way to remap them?

Yes, you can create an [`input.conf`](https://mpv.io/manual/master/#input-conf) and load it in the preferences dialog.

**Comment by firefoxlover** [comment]
Thanks a lot!

**Comment by andyzukunft** [comment]
Hey @firefoxlover 
I am interested in the same shortcut. Can you share your input.conf with the volume change?

**Comment by firefoxlover** [comment]
```
cat ~/.var/app/io.github.celluloid_player.Celluloid/config/celluloid/input.conf <<EOF
# Arrow keys control volume
UP add volume 2
DOWN add volume -2
EOF
```

Then load this file through the Celluloid settings.
