### ISSUE TITLE
[Feature request]: single mouse click on video playback area should pause it

### ISSUE THREAD

**Issue by marek-lach** [celluloid-player/celluloid#918]
Overview Description:

Steps to Reproduce:
1. Launch celluloid
2. Play some video
3. When the video is playing, single click on it. It will continue to play. It should pause.

Version: 0.26

**Comment by gnome-mpv** [comment]
Right clicking will pause the video. If you want to, you can bind left click to pause using an [input.conf](https://mpv.io/manual/stable/#input-conf) file.
