### ISSUE TITLE
[FEATURE REQUEST] Enable XML subtitle format

### ISSUE THREAD

**Issue by Palace4Software** [celluloid-player/celluloid#924]
In VLC Media Player is it possible to use XML format as subtitles.
It would be great if Celluloid have also an XML-subtitle function.

**Comment by gnome-mpv** [comment]
Are you referring to TTML? That's something that should be implemented in ffmpeg, which one of mpv's dependencies. There's already an [open ticket](https://trac.ffmpeg.org/ticket/4859) for it.

**Comment by Palace4Software** [comment]
Could be...
I don't know if this is the same.


`
<tt:tt ttp:timeBase="media" ttp:cellResolution="50 30" xml:lang="de-DE">
<tt:head>
<tt:metadata>
<ebuttm:documentMetadata>
<ebuttm:documentEbuttVersion>v1.0</ebuttm:documentEbuttVersion>
</ebuttm:documentMetadata>
</tt:metadata>`

This is the beginning of the XML file. Is this an TTML document?

**Comment by Palace4Software** [comment]
Could be...
I don't know if this is the same.


`
<tt:tt ttp:timeBase="media" ttp:cellResolution="50 30" xml:lang="de-DE">
<tt:head>
<tt:metadata>
<ebuttm:documentMetadata>
<ebuttm:documentEbuttVersion>v1.0</ebuttm:documentEbuttVersion>
</ebuttm:documentMetadata>
</tt:metadata>`

This is the beginning of the XML file. Is this an TTML document?

**Comment by gnome-mpv** [comment]
Yeah, that looks like TTML.

**Comment by Palace4Software** [comment]
So should I close the issue here?

**Comment by gnome-mpv** [comment]
Yeah, I guess we can close this issue.
