### ISSUE TITLE
Sidebar icon issue

### ISSUE THREAD

**Issue by Rid1-fz-06** [celluloid-player/celluloid#926]
Overview Description: There are two issues with the sidebar icon. First, hovering over this icon, shows `Toggle Fullscreen` as tooltip. Second, this icon doesn't work in fullscreen mode. The icon is still there, but clicking this doesn't open the sidebar.

Version: Celluloid 0.26

Additional Information:
![image](https://github.com/celluloid-player/celluloid/assets/92540820/fcdb70b6-dccc-4c7c-8f57-eb0ce5794364)

**Comment by gnome-mpv** [comment]
The commit only fixes the second issue. The first issue with the tool tip has already been fixed some time ago.
