### ISSUE TITLE
Weird theme issue -- not all control buttons display properly

### ISSUE THREAD

**Issue by kdato** [celluloid-player/celluloid#928]
Overview Description: I am on Enlightenment 0.26.99.xxx.  Update: I have now tried celluloid on the very simple Motif WM and I am seeing the same issue. This suggests that it's an X11 issue (not seeing it on Wayland).

Steps to Reproduce:
1. the issue is always present

Actual Results:
Previous Chapter, Rewind, Next Chapter, Shuffle Playlist, Toggle Playlist, Toggle Playlist -- the buttons do not display properly (although they are functional); what I see is a box with an ! inside.

Expected Results: All video control buttons should display properly

Version: celluloid-git; but earlier versions have the same issue

Additional Information: I attach a screenshot
![shot-2024-02-17_02-01-07](https://github.com/celluloid-player/celluloid/assets/42091527/339b4103-95ed-42f7-b28c-8eee552831d1)

**Comment by gnome-mpv** [comment]
It looks like your system is missing some icons. If you install a theme with those icons (e.g. Adwaita), that should fix the problem.

**Comment by kdato** [comment]
Thanks for the tip, which has resolved the issue.
