### ISSUE TITLE
Progress bar not behaving as expected

### ISSUE THREAD

**Issue by kdato** [celluloid-player/celluloid#929]
Overview Description: I am on Enlightenment-0.26.99.xxx and I am experiencing unexpected progress bar behavior. Edit: this is not Enlightenment-specific. I tried different Xorg WMs, and I tried different Wayland compositors -- the issue exists everywhere.

Steps to Reproduce:
1. always present

Actual Results: when clicking a point on the progress bar, the actual result is that the video forwards as if the Forward button was pressed.

Expected Results: jump to the point that was clicked on the progress bar.

Version: celluloid from git

Additional Information:

**Comment by gnome-mpv** [comment]
Does [this](https://github.com/celluloid-player/celluloid/issues/595#issuecomment-710775057) fix the problem for you?
