### ISSUE TITLE
[Celluloid player v 0.26] Loop single file / Loop current file

### ISSUE THREAD

**Issue by mrandremendes** [celluloid-player/celluloid#935]
**Overview Description:**
Looping single file in playlist

**Question**
Hello! I've just started using Celluloid Player on Ubuntu. I'm loving it.
I have a playlist with images and videos, and I would like the images to have infinite playback time. When selecting "Loop file" on a single file in the playlist, all files are looped.
When using the shortcut Shift+L, the information "Loop current file: inf" appears, however, all other files in the playlist stay in loop, not just the single file I was playing.
Why is this happening, is there any way to make it work correctly?

**Actual Results:**
All files are looped

**Expected Results:**
A single .png file is looped, and it is remembered every time i play the playlist

**Version:**
0.26

**Additional Information:**
I'm using Ubuntu 22.04.4 LTS X11

**Comment by gnome-mpv** [comment]
The UI might be a bit confusing here, but the `Loop File` option isn't supposed to be a specific to single file. It's more like a global variable.

If you just want images to be displayed indefinitely, you can set `--image-display-duration=inf` in `Extra mpv options` or use an external config file.

**Comment by mrandremendes** [comment]
That makes sense. Thanks!
It worked just fine.
