### ISSUE TITLE
Which MPV versions are supported?

### ISSUE THREAD

**Issue by kuraga** [celluloid-player/celluloid#938]
Which MPV versions are supported?

* https://github.com/celluloid-player/celluloid/blob/6c2b83e8318fb4383ed5f9da3108aae1bf374d12/README.md?plain=1#L19
* https://github.com/celluloid-player/celluloid/blob/6c2b83e8318fb4383ed5f9da3108aae1bf374d12/configure.ac#L93

(Also don't know whether GDK - https://github.com/celluloid-player/celluloid/blob/6c2b83e8318fb4383ed5f9da3108aae1bf374d12/configure.ac#L99-L100 - should be mentioned in README or it's a part of GTK.)

Thanks!

**Comment by gnome-mpv** [comment]
> Which MPV versions are supported?

`mpv` version 0.32 or newer is supported. The version number in `configure.ac` refers to the `libmpv` API version. `mpv`'s [documentation](https://raw.githubusercontent.com/mpv-player/mpv/master/DOCS/client-api-changes.rst) has more details.

> (Also don't know whether GDK should be mentioned in README or it's a part of GTK.)

It's a part of GTK.

**Comment by kuraga** [comment]
Thanks!
