### ISSUE TITLE
How this capture events? (Just a humble request for help)

### ISSUE THREAD

**Issue by Gzushgshsh** [celluloid-player/celluloid#939]
Context: I'm trying to make a miniplayer for my gtksharp program with libmpv and a small glue library adapted from winforms.

Question: After defining a GdkWindow for the mpv, it doesn't recognize the events as Button Press Event, do you have any idea how to solve this?

**Comment by gnome-mpv** [comment]
It's a bit hard to tell what the problem could be based on the information you gave, but the way you normally handle events in GTK4 is by installing event controllers with [`gtk_widget_add_controller()`](https://docs.gtk.org/gtk4/method.Widget.add_controller.html). For example, if you want to handle (mouse) button press events, you would create a [`GtkGestureClick`](https://docs.gtk.org/gtk4/method.Widget.add_controller.html), add it to the widget using `gtk_widget_add_controller()`, and connect a handler to the `pressed` signal.

**Comment by Gzushgshsh** [comment]
I'm still using [GTK 3](https://github.com/GtkSharp/GtkSharp), in an [x11 environment](https://mxlinux.org/ with xfce.

DrawingArea is a widget that normally responds to most events (depending on the event masks), right?
But after setting the 'wid' option in the libmpv API with your GdkWindow it no longer responds to many events correctly (this also occurs in window forms controls when using x11).

I have celluloid installed on the system, version 0.20 which still uses GTK 3, I imagined that it used this same simple system of the 'wid' option but even so the DrawingArea used continues to respond normally to events (I confirmed using GTK_DEBUG="interactive"), so I thought it wasn't a bug in libmpv, or gtk and that I was doing something wrong

**Comment by gnome-mpv** [comment]
> DrawingArea is a widget that normally responds to most events (depending on the event masks), right?

Actually, it doesn't *normally* receive a lot of common events, including button events. You have to explicitly enable that by setting the event mask. If you look at the source code from v0.20, you can find a [list of events](https://github.com/celluloid-player/celluloid/blob/9cfab0128cd9975e026aff464a17df57ab63ce2a/src/celluloid-video-area.c#L346-L350) we had to enable.

> But after setting the 'wid' option in the libmpv API with your GdkWindow it no longer responds to many events correctly (this also occurs in window forms controls when using x11).

If events were being received before you attach the mpv window with `wid`, then the problem could be something else. I'm  not sure what it would be though. I don't recall having to do anything special other than setting the event mask.

**Comment by Gzushgshsh** [comment]
> Actually, it doesn't _normally_ receive a lot of common events, including button events. You have to explicitly enable that by setting the event mask. If you look at the source code from v0.20, you can find a [list of events](https://github.com/celluloid-player/celluloid/blob/9cfab0128cd9975e026aff464a17df57ab63ce2a/src/celluloid-video-area.c#L346-L350) we had to enable.

Yes, that's right. I took care to add the event masks I wanted, I also tested with all the possible ones enabled just in case

> If events were being received before you attach the mpv window with `wid`, then the problem could be something else. I'm not sure what it would be though. I don't recall having to do anything special other than setting the event mask.

Yes, everything was working perfectly, all events I wanted, were being received by DrawingArea before its GdkWindow was set to the 'wid' option, but after that some events are no longer received and for some strange reason, the mouse click triggers the enter-notify-event.

Here I have enabled all the event masks, and these are the events that are still received:
![image](https://github.com/celluloid-player/celluloid/assets/95548091/079272fe-c7b8-459f-a37f-145237118d81)
