### ISSUE TITLE
The `Home` key should go to the beginning of a file, Ènd`should go to the end.

### ISSUE THREAD

**Issue by HT-7** [celluloid-player/celluloid#942]
The `Home` key should go to the beginning of a file. The `End` key should go to the end. This means pressing end while paused would show the last frame of the video.

**Comment by gnome-mpv** [comment]
You can bind those keys yourself using an [`input.conf`](https://mpv.io/manual/stable/#input-conf) file:
```
HOME set percent-pos 0
END set percent-pos 100
```

I don't think many users would want to jump to the end of the file, so it doesn't warrant having it's own key by default. Jumping to the beginning of the file is already easy enough with existing keybindings.
