### ISSUE TITLE
Space key problem 

### ISSUE THREAD

**Issue by Majlo34** [celluloid-player/celluloid#943]
Overview Description:

Hello. I found small problem with space key which can be very anoying because instead of pause/play it start video from begining.

Steps to Reproduce:
1. Play movie and pres left or right arrow key ( seek backward/forward)
2. Then press pause ( it should pause video )
3. Instead of pause it will start video from beggining.

I tried this in mpv 0.37.0 and it works as expected.

Actual Results:

Expected Results:

Space key should pause/play video

Version: Celluloid 0.26 

Additional Information:

Ubuntu 24.04 , celluloid installed from Flathub.

**Comment by gnome-mpv** [comment]
Is the playlist open when this happened?

**Comment by Majlo34** [comment]
You are right, it only happens when playlist is open.
