### ISSUE TITLE
Spaces are not properly processed by arg parser

### ISSUE THREAD

**Issue by Commandcracker** [celluloid-player/celluloid#948]
Overview Description:

Steps to Reproduce:
1. `celluloid "--mpv-force-media-title=07-Ghost - The Future of Painful Thoughts is - "`

Actual Results:
Player with title "07-Ghost"
Error: Failed to apply one or more MPV options

Expected Results:
Player with title "07-Ghost - The Future of Painful Thoughts is - "

Version: 0.20

Additional Information:

**Comment by gnome-mpv** [comment]
I can't reproduce this with v0.26, so I think already fixed.

**Comment by Commandcracker** [comment]
Oh, thought I was on latest, but Debian(12) packages are always a bit behind for stability.
I'll try with v0.26 and when everything works ill close the issue.
