### ISSUE TITLE
rotate during playback

### ISSUE THREAD

**Issue by HT-7** [celluloid-player/celluloid#949]
There needs to be an option to rotate videos during playback.

Inexperienced smartphone camera users sadly make the mistake of [rotating their smartphone without restarting recording](https://www.youtube.com/watch?v=17uHCHfgs60 ). We need to account for this by letting the viewer rotate during playback.

VLC for desktop already has this ability.

**Comment by gnome-mpv** [comment]
This is already possible with custom keybindings. Something like this:
```
a cycle-values video-rotate 0 90 180 270
```

**Comment by HT-7** [comment]
Unfortunately doesn't work. I tried putting that into  `~/.config/mpv/input.conf` and `~/.config/mpv/mpv.conf` and `~/.config/celluloid/input.conf` and `~/.config/celluloid/mpv.conf` and none of them work.
