### ISSUE TITLE
reset pan and zoom with one button

### ISSUE THREAD

**Issue by HT-7** [celluloid-player/celluloid#950]
First of all, I am delighted that Celluloid (and, by extension, mpv) offer built-in pan and zoom functionality. For over a decade, the only player to have it was VLC and the pre-installed media player on Samsung Galaxy devices, and some DVD players from the 2000s (including the cheap ones with the SunPlus firmware). 

I am glad to see more players implement this important ability, and I wish all video players had this.

But the one thing I miss is an instant shortcut to go back to normal.

**Comment by gnome-mpv** [comment]
Pressing `Alt + Backspace` should reset pan/zoom settings.

**Comment by HT-7** [comment]
Amazing, didn't know that. Good to know!

Please add this to the "Keyboard Shortcuts" window. It is not listed there.
