### ISSUE TITLE
Themes not working on Sway,Arch linux

### ISSUE THREAD

**Issue by kaafir786** [celluloid-player/celluloid#953]
Overview Description:System default theme is not working in Celluloid

Steps to Reproduce:
1.Install celluloid
2.Disable Prefer dark theme in preferences
3.Install any gtk theme (materia-gtk-theme in my case)
4.Switch to that theme `gsettings set org.gnome.desktop.interface gtk-theme` (Materia-dark and Materia-light in my case)
5.All GTK Apps switch to that theme but Celluloid will not
 
Actual Results:Celluloid didn't switched theme after this all

Expected Results:It should have adapted Materia theme like other

Version:0.26

Additional Information:None

**Comment by jannuary** [comment]
Intended behaviour – apps using libadwaita and GTK4 ignore themes. You can try using the debug `GTK_THEME` enviroment variable, but it's largely unsupported.

**Comment by kaafir786** [comment]
Hmm, I also got to know about it recently.
Thanks
