### ISSUE TITLE
Feature request: add shared-memory plug for snap

### ISSUE THREAD

**Issue by thatLeaflet** [celluloid-player/celluloid#958]
My use case: I store movies on a large, slow hard drive. Due to this, it takes a fair amount of time for a movie to be initially loaded and jumping around the timeline may cause freezes. But as I have a lot of RAM, I would like to be able to copy a movie from my slow HDD to my RAM (in /dev/shm) so that the loading is much quicker. And by putting the file directly into RAM, I can avoid unnecessary writes to my SSD.

However, the snap version of celluloid does not have permission to read /dev/shm. This can be remedied  by adding the shared-memory plug. If this plug is set to private mode, then it can be autoconnected by default without needing to contact the snap store. See: https://snapcraft.io/docs/shared-memory-interface.

**Comment by sameersharma2006** [comment]
Snap Maintainer here, I have never heard or saw any use case where access to `/dev/shm`  is required, nevertheless i will look into this.

Given that this doesn't needs auto-connect its fairly a simple addition to the snap.

**Comment by sameersharma2006** [comment]
Tracking the above via https://codeberg.org/sameersharma2006/celluloid-snap/issues/3

**Comment by sameersharma2006** [comment]
@thatLeaflet  Can you check the problem is solved in the edge channel revision of celluloid ?
I have enabled that change for the edge channel , if the problem is fixed, i will push it to stable.

To upgrade to edge;
 > snap refresh celluloid --edge

**Comment by thatLeaflet** [comment]
It doesn't if trying to open it from Nautilus. Though the fault of that is probably in snapd, portal, and/or nautilus.

But it does work when opening the file directly from Celluloid, so the functionality does work. Thank you for implementing this!

**Comment by sameersharma2006** [comment]
Okay, glad to know it's working (partially :upside_down_face:  ).
I will push this change along with enhancements to the bundled ffmpeg to stable ASAP.
Hope, this can be closed ?

**Comment by thatLeaflet** [comment]
Yes
