### ISSUE TITLE
Celluloid on Fedora (Gnome - Wayland) Playback Issue Playing From WDCloud NAS

### ISSUE THREAD

**Issue by rodneybbeme** [celluloid-player/celluloid#962]
Overview Description:
Larger sized videos stutter and are unwatchable when steaming directly from WDCloud NAS. This only happens when logged in using Wayland on Fedora. Playback is fine when using Xorg.

Steps to Reproduce:
1. Open File Manager and navigate to a folder on the NAS whlie logged in to a Wayland session.
2. Double click the file that you want to play.

Actual Results:
Video plays but looks like it is playing in slow motion.

Expected Results:
Video should play normally as it does when in an Xorg session.

Version:
Celluloid 0.27 (Snap)

Additional Information:
I have tried this using the Snap, Flatpak, and Fedora native versions of the program with the same results. Of note, Celluloid does not work at all (when playing directly from the NAS) if the native Video program that comes with the initial install of Fedora is uninstalled. This includes the Snap and Flatpak versions of the program. Instead an error message is produced and nothing plays. From what I can remember, installing Totem solves this issue.

**Comment by sameersharma2006** [comment]
Snap maintainer here, i believe this seems to be a upstream issue.
Although happy to help if this is specific to snap packaging format.

**Comment by gnome-mpv** [comment]
@rodneybbeme Can you attach a [log file](https://celluloid-player.github.io/bug-reports.html)?

**Comment by rodneybbeme** [comment]
Here is a copy of the log file:
[logs.txt](https://github.com/user-attachments/files/16159800/logs.txt)

**Comment by gnome-mpv** [comment]
> Here is a copy of the log file:
> [logs.txt](https://github.com/user-attachments/files/16159800/logs.txt)

That's the system log, not Celluloid's log. You can make Celluloid emit log outputs by running `G_MESSAGES_DEBUG=all celluloid --mpv-msg-level=all=trace`. You may need to adjust the command if you're using Snap, but since the issue is reproducible with native version, it might be easier to just use that to generate the log.

**Comment by rodneybbeme** [comment]
Sorry. Here are the log files for Celluloid:
[celluloid_log_xorg_session.txt](https://github.com/user-attachments/files/16163322/celluloid_log_xorg_session.txt)

[celluloid_log_wayland_session.txt](https://github.com/user-attachments/files/16163325/celluloid_log_wayland_session.txt)

**Comment by gnome-mpv** [comment]
Did you try opening any files when you generated these logs? I don't see anything being opened in the logs.

**Comment by rodneybbeme** [comment]
> Did you try opening any files when you generated these logs? I don't see anything being opened in the logs.

Sorry again. I'm new to how logging works. Here are some logs while a video is playing:

[celluloid_log_wayland_session_direct_from_SSD.txt](https://github.com/user-attachments/files/16167354/celluloid_log_wayland_session_direct_from_SSD.txt)
[celluloid_log_wayland_session_from_NAS.txt](https://github.com/user-attachments/files/16167355/celluloid_log_wayland_session_from_NAS.txt)
[celluloid_log_xorg_session_from_SSD.txt](https://github.com/user-attachments/files/16167357/celluloid_log_xorg_session_from_SSD.txt)

I did find out in doing this that the video stil stutters when playing directly from my system SSD similar to how it does when streaming from my NAS. I included about 3 minutes of playback in each and the log for the Xorg session (where things seem to be working fine).

**Comment by gnome-mpv** [comment]
Thanks for the logs. I don't see anything unusual in there though, so it's not obvious where the problem is.

> I did find out in doing this that the video stil stutters when playing directly from my system SSD similar to how it does when streaming from my NAS. I included about 3 minutes of playback in each and the log for the Xorg session (where things seem to be working fine).

If the video always stutters on Wayland, then it sounds like the problem has something to do with Wayland rather than the NAS.

**Comment by rodneybbeme** [comment]
> Thanks for the logs. I don't see anything unusual in there though, so it's not obvious where the problem is.
> 
> > I did find out in doing this that the video stil stutters when playing directly from my system SSD similar to how it does when streaming from my NAS. I included about 3 minutes of playback in each and the log for the Xorg session (where things seem to be working fine).
> 
> If the video always stutters on Wayland, then it sounds like the problem has something to do with Wayland rather than the NAS.

Understood. Thanks for looking into it!
