### ISSUE TITLE
Page Up and Page Down shortcuts are reversed

### ISSUE THREAD

**Issue by JaneSmith** [celluloid-player/celluloid#968]
**Overview Description:**

The Keyboards Shortcut window says the following:

> Page Up / Page Down = Seek to the beginning of the previous/next chapter

The ordering here suggests that Page Up seeks to the previous chapter, and Page Down seeks to the next chapter. That is also what I would intuitively expect, as e.g. when reading a document, Page Down would go to the next section, and Page Up would scroll back up an older section.

However, in my version (0.27 via Flathub), it actually works the other way around. Page Down goes to the previous chapter and Page Up goes to the next one. It feels wrong.

**Steps to Reproduce:**

1. Open a video with chapters.
2. Press Page Down.

**Actual Results:**

The video skips back to the previous chapter.

**Expected Results:**

The video will skip to the next chapter.

**Version:**

0.27 via Flathub.

**Comment by JaneSmith** [comment]
Thanks, that fixes it as now the keyboard shortcuts window is clear.

Can I ask why you want the shortcuts to work this way around though? As I said, it seems counter-intuitive and isn't really consistent with how other software works. Of course, it's your software and you can make it how you like. Thanks.

**Comment by gnome-mpv** [comment]
> Can I ask why you want the shortcuts to work this way around though? As I said, it seems counter-intuitive and isn't really consistent with how other software works. Of course, it's your software and you can make it how you like. Thanks.

These shortcuts come from `mpv`, and I would prefer not to override them unless there's a really good reason. You can always rebind the keys if you prefer it the other way round.
