### ISSUE TITLE
No videos can be played

### ISSUE THREAD

**Issue by vitrola06** [celluloid-player/celluloid#974]
Overview Description: RPM package on Fedora 40. Whether it is an mp4 or an mkv file, it errors out saying "something happened".

Steps to Reproduce:
Open a video file, be it through the CLI or the GUI

Actual Results: 
A popup appears with the following message "Playback ended unexpectedly. Reason: something happened"
 
Expected Results:
The playback happens normally

Version:
0.27, the latest on Fedora repo

Additional Information:
[Log file](https://github.com/user-attachments/files/16826334/mpv.log) containing the process. File name has been edited to a generic "file" for privacy.

VLC can play these videos normally.

**Comment by vitrola06** [comment]
From what I could understand from the log, it seems not to be able to retrieve any property such as duration, height, width and that it is because "core not uninitialized".

**Comment by gnome-mpv** [comment]
> [Log file](https://github.com/user-attachments/files/16826334/mpv.log) containing the process. File name has been edited to a generic "file" for privacy.

For some reason, no log messages from mpv are coming through, but I see that you're already passing the right option.

Are you able to play the files with mpv?

**Comment by vitrola06** [comment]
I couldn't, but it returned something about ffmpeg. I had to install non-free ffmpeg to solve the issue, which sucks. Sorry for opening the issue, but your insight was valuable.
