### ISSUE TITLE
Flatpak advertises support for .xm, .mod, .it and .s3m (sequencer/tracker formats) but isn't able to play, Flatpak VLC is able to play them

### ISSUE THREAD

**Issue by MateusRodCosta** [celluloid-player/celluloid#979]
Overview Description:

The .desktop file advertises support for those file formats, but trying to play them results in a "unrecognized file format error"

Affected file formats: .xm, .mod, .it, .s3m

Steps to Reproduce:
1. Download some of the mentioned formats from https://modarchive.org/index.php ([example](https://modarchive.org/index.php?request=view_by_moduleid&query=140046))
2. Try to play it with Celluloid Flatpak via "Open With..." dialog

Actual Results:

"unrecognized file format error"

Expected Results:

Either the file format should be supported and the audio play, or the support shouldn't be advertised on the desktop entry file mimetype section

Version: 0.27

Additional Information: Flatpak version

**Comment by gnome-mpv** [comment]
Looks like ffmpeg needs to be [compiled with libopenmpt](https://github.com/mpv-player/mpv/issues/8466#issuecomment-761812848) to play those formats.

/cc @TingPing

**Comment by MateusRodCosta** [comment]
> Looks like ffmpeg needs to be [compiled with libopenmpt](https://github.com/mpv-player/mpv/issues/8466#issuecomment-761812848) to play those formats.
> 
> /cc @TingPing

Why not just use ffmpeg-full instead of [compiling your own ffmpeg](https://github.com/flathub/io.github.celluloid_player.Celluloid/blob/fda48dcb0f5de3e1ad7751e4c5e76d3a1b8b3cf5/io.github.celluloid_player.Celluloid.yaml#L165) then?

**Comment by TingPing** [comment]
It has been a while, but we enable some options that full didn't.


Easy to add more if needed.

**Comment by TingPing** [comment]
Also sometimes mpv needs a very new version of ffmpeg.
