### ISSUE TITLE
How to change keybinding Ctrl+o to open file browser ? 

### ISSUE THREAD

**Issue by FrankBKK** [celluloid-player/celluloid#986]
How can I change the key binding Ctrl+o to open the file browser to e.g.  MBTN_RIGHT ? 

I can not find the  input.conf command for that 

should be something like   MBTN_RIGHT    file-open

**Comment by gnome-mpv** [comment]
This should work: `MBTN_RIGHT script-message celluloid-action win.show-open-dialog((false, false))`

**Comment by FrankBKK** [comment]
You made my day !  Thank you very much !
