### ISSUE TITLE
Bug report : MPRIS client don't work

### ISSUE THREAD

**Issue by Rori324** [celluloid-player/celluloid#987]
I'm on linux mint 22, I don't know if it's only for me but the MPRIS client don't work on the player. Even through I made sure it was enable in the preference settings 

Here, I use Playerctl to issue media command but celluloid isn't recognize.

![Capture d’écran du 2024-10-11 20-05-13](https://github.com/user-attachments/assets/2254b3ac-f372-463d-92d2-8d339043fa5d)

**Comment by gnome-mpv** [comment]
I'm unable to reproduce this. Tested with a fresh install of Mint 22 in a VM.

**Comment by Rori324** [comment]
Indeed, I tested on a fresh mint install in a VM and I didn't have the issue.
I don't have error messages in my terminal, I suppose that I have just f*cked my installation. 
I will close this issue because it seams that it's not really one. 
For anyone who have the same problem, I'm sorry but you must reinstall your system.
