### ISSUE TITLE
"Toggle Fullscreen" button causes the entire window to resize

### ISSUE THREAD

**Issue by orfeasxyz** [celluloid-player/celluloid#988]
Overview Description: Current "Toggle Fullscreen" button resizes the entire window instead of the video player frame when Cellular is a floating window. This is a problem when you want to toggle the button on and off especially when the window is at the right edge of the screen and may go off bounds.

Steps to Reproduce:

https://github.com/user-attachments/assets/1f55e6f4-a20d-40ca-b421-fbdd3df99e68

Actual Results: Entire window is resizing on "Toggle Fullscreen"

Expected Results: The video player frame resizes on "Toggle Fullscreen"

Version: 0.26

Additional Information: I am running this under labwc on Wayland

**Comment by gnome-mpv** [comment]
Thanks for the report. We're switching to a new design with the playlist is overlaid on top of the video in the next release so this will no longer be an issue.
