### ISSUE TITLE
Unable to use input-ipc-server=/tmp/mpvsocket in mpv.conf

### ISSUE THREAD

**Issue by first-storm** [celluloid-player/celluloid#995]
### **Overview**

I encountered an issue with Celluloid where the `input-ipc-server=/tmp/mpvsocket` configuration doesn't seem to work as expected. I have tried both the system-installed version of Celluloid (via a package manager) and the Flatpak version with `/tmp` permissions enabled. However, in both cases, I cannot find the `mpvsocket` file in `/tmp`. 

When I add the same configuration (`input-ipc-server=/tmp/mpvsocket`) to the official `mpv.conf`, everything works as expected. I can confirm that Celluloid is successfully detecting and applying other settings like `hwdec=auto` from the `mpv.conf` file without any issues.

---

### **Steps to Reproduce**

1. Install Celluloid.
2. Add the following line to `~/.config/mpv/mpv.conf`:
   ```
   input-ipc-server=/tmp/mpvsocket
   ```
3. Specify the same `mpv.conf` in Celluloid's settings.
4. Run the following command:
   ```
   celluloid https://youtu.be/*****
   ```
5. Check if `/tmp/mpvsocket` is created.

---

### **Actual Results**

The `/tmp/mpvsocket` file is not created.

---

### **Expected Results**

The `/tmp/mpvsocket` file should be created.

---

### **Version**

Celluloid version: **0.27**

**Comment by gnome-mpv** [comment]
I can't reproduce this. The file gets created normally for me.

Do you see any error messages in [the log](https://celluloid-player.github.io/bug-reports.html)?

**Comment by first-storm** [comment]
> I can't reproduce this. The file gets created normally for me.
> 
> Do you see any error messages in [the log](https://celluloid-player.github.io/bug-reports.html)?

I didn't see any error messages here. It works again. I think it is because some wired permission issue. Sorry to bother you.
